### ISSUE TITLE
error make install

### ISSUE THREAD

**Issue by gearcapitan** [kgretzky/evilginx2#1]
└─[$] <git:(master)> sudo make install
cp: no se puede efectuar `stat' sobre './bin/evilginx': No existe el fichero o el directorio
make: *** [Makefile:20: install] Error 1
┌─[root@Gear] - [~/go/src/github.com/kgretzky/evilginx2] - [jue jul 26, 10:36]
└─[$] <git:(master)> make                               
# github.com/golang/dep/gps
../../golang/dep/gps/constraint.go:378: undefined: sort.SliceStable
../../golang/dep/gps/lock.go:31: undefined: sort.SliceIsSorted
../../golang/dep/gps/lock.go:38: undefined: sort.Slice
make: *** [Makefile:23: godep] Error 2
┌─[root@Gear] - [~/go/src/github.com/kgretzky/evilginx2] - [jue jul 26, 10:36]
└─[$] <git:(master)>

**Comment by kgretzky** [comment]
Did you run `make` first as detailed in the readme?

**Comment by gearcapitan** [comment]
![kali_linux-2018-07-31-12-59-19](https://user-images.githubusercontent.com/13740942/43477729-8e32cf2a-94c1-11e8-8387-f75ee4698f42.png)

**Comment by kgretzky** [comment]
Looks like your GO version may be outdated. You need version 1.10.

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/43505378-5f20a66a-952c-11e8-9154-86ea7b2c56c7.png)
ok, i have this problem now :/

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/43505410-76baf5c8-952c-11e8-91c2-a593005d749a.png)
ok ,i have this problem now :/

**Comment by kgretzky** [comment]
You have all the answers in the error output.

Please use this place for what it is meant to be - to report issues with the tool, not requesting free customer support.
