### ISSUE TITLE
Empty 'phish_sub' on phishlet.

### ISSUE THREAD

**Issue by ssddgr** [kgretzky/evilginx2#10]
Hi,

Thank you very much for the excellent tool :D

Trying to proxy a site with an adequate 'phish_sub' on the phishlet works fine. But what happens if I want to serve it without a sub-domain? I have tried using an empty 'phish_sub' but it doesn't work. So, for example:
{phish_sub: 'subdomain', orig_sub: 'subdomain', domain: 'domain.com', session: false, is_landing: true} --> works fine
{phish_sub: '', orig_sub: 'subdomain', domain: 'domain.com', session: false, is_landing: true} --> doesn't work for mydomain.

Just to clarify, what I am trying to do is to proxy linkedin login (for example) on my root domain, i.e. myuselessproxy.com, without a subdomain.

Cheers,

**Comment by ssddgr** [comment]
I think I have located the issue to phishlet.go:
`ret = append(ret, h.phish_subdomain+"."+phishDomain)`

An uninformed, quick and dirty workaround that I am trying is:
` if ok {
			if len(h.phish_subdomain)>0{
				ret = append(ret, h.phish_subdomain+"."+phishDomain)
			}
			if len(h.phish_subdomain)==0{
				ret = append(ret, phishDomain)
			}
		}`

However, looks like I am having an issue with SSL certificates.

**Comment by kgretzky** [comment]
Hmm you're right. Actually I never had to create a subdomain-less hostname and Evilginx is designed to always require a subdomain name.

You may be right with that workaround, but then also the retrieval of certificates like you noticed will be bugged.

**Comment by ssddgr** [comment]
Guess it is a good thing to expand the tool accordingly :)

So, the issue with the retrieval of certificates emerges in `func (p *HttpProxy) TLSConfigFromCA(ca *tls.Certificate)`?

**Comment by clr2of8** [comment]
I have the same issue with several sites. Would love a fix for the certificate portion as well. Can I just manually run letsencrypt to get the certificate for the root domain?

**Comment by kgretzky** [comment]
I've just released a new version. Empty subdomain issue should have been fixed with cc17afcfba78778210c9af6149b74f672e71d2d0

Check out the full write-up here: https://breakdev.org/evilginx-2-1-the-first-post-release-update/
