### ISSUE TITLE
New tuto for DNS config on Digital ocean

### ISSUE THREAD

**Issue by Barenchi** [kgretzky/evilginx2#100]
We need a Tuto for DNS config in digitalocean. Thank you.

**Comment by kgretzky** [comment]
Evilginx handles DNS config. You need to point nameservers in your domain provider to Evilginx server.
There is nothing to touch on DigitalOcean. Please read the blog post again to understand how Evilginx acts as a DNS by itself.

**Comment by Barenchi** [comment]
Thank you for your response, it's just the "You need to point nameservers in your domain provider to Evilginx server." that I don't understand ...
