### ISSUE TITLE
Recaptcha sitekey Error Solution

### ISSUE THREAD

**Issue by younevsky** [kgretzky/evilginx2#1003]
### Hello everyone,

**I have a question regarding fixing this recaptcha error while proxying a site using EvilGinx 3.2.0.**(_I followed an approach described on GitHub by replacing the "co" parameter, but it was not replaced when the request was sent_).

![image](https://github.com/kgretzky/evilginx2/assets/77975903/43a02b63-5b9f-4a4a-95cf-da018a2e05ee)

**Comment by M3d-Edge** [comment]
Hello i have same problem did you fix it?

**Comment by M3d-Edge** [comment]
anyone solved this issue?

**Comment by stackerofwheat** [comment]
hahaha why close when it was def not completed??
