### ISSUE TITLE
antirobot token not appended to relative urls

### ISSUE THREAD

**Issue by Menafista** [kgretzky/evilginx2#102]
Hello,

The token used to avoid scans is not appended to relative urls.
From what I see, it may not be a problem in some browsers and everything will work fine, but in Safari (iOS) I get a lot of unauthorized requests error in the console, and if those links are important, the page get broken. 

You can check this for example in Instagram:
`<script type="text/javascript" src="/static/bundles/base/Polyfills.js/13758d0151d9.js" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="/static/bundles/base/Vendor.js/fd511240bc76.js" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="/static/bundles/base/en_US.js/64597f3768f2.js" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="/static/bundles/base/ConsumerCommons.js/350b5e8f3dde.js" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="/static/bundles/base/Consumer.js/c7548aaadfb8.js" crossorigin="anonymous"></script>
  | <script type="text/javascript" src="/static/bundles/base/FBSignupPage.js/b5844558e291.js" crossorigin="anonymous" charset="utf-8" async=""></script>
  | <script type="text/javascript" src="/static/bundles/base/LoginAndSignupPage.js/94f77dfd8e0c.js" crossorigin="anonymous" charset="utf-8" async=""></script>
`

**Comment by Menafista** [comment]
Hello,
After few more tests, it seems that it happens on every iOS browsers:
Tests I made:
 Chromium Desktop: **OK / 1 unauthorized access with ios user-agent for /data/manifest.json (relative url in source code**
Firefox Desktop **OK / OK** 

Safari iOS/ Chrome iOS/ Firefox iOS: **unauthorized for:**
/static/bundles/base/Vendor.js/fd511240bc76.js
/static/bundles/base/en_US.js/2bcafcf913e3.js
/static/bundles/base/ConsumerCommons.js/350b5e8f3dde.js
/static/bundles/base/Consumer.js/c7548aaadfb8.js

From what I can see at least. The page doens't loads because those are important javascripts.

see view-source:https://www.instagram.com/accounts/login/ line 229 for reference

To bypass this, it is possible to append https://www.instagram.com before these to load the original js, but of course the page will load but will not work properly.

**Comment by kgretzky** [comment]
As strange as it sounds, Safari on iOS may not be saving the cookies when the page is loaded, but only after all the external assets are loaded. Assets are then loaded without the validation cookie being present in the request.

Does it work fine after you press "Reload" first time, right after you open the website for the first time and it shows missing content? It would then mean that after first load, the cookies are sent properly.

1. Did you check on Safari on OSX?
2. Does it behave the same way on iOS for any phishlet that comes bundled with Evilginx? (e.g. Linkedin)

**Comment by kgretzky** [comment]
I think I am able to reproduce this also on Chrome with the twitter phishlet. Seems that the `/manifest.json` which is loaded in `<head>` is not loaded, because the cookies are not sent at that time.

I have an idea how to fix this using `Referer` HTTP header. Will post here once I confirm it is fixed.

Thanks for reporting this!

**Comment by kgretzky** [comment]
I found the real cause of the issue.

1. By default requests to `<link ref="manifest" ...>` will never send cookies with the request. This is why I detected the unauthorized error when accessing twitter via Evilginx proxy.
2. The instagram resources you mentioned all have `crossorigin="anonymous"` attached to their HTML tag, which means that the browser should never send cookies with those requests for security reasons. Check here: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

You can create a `sub_filter` to remove all `crossorigin="anonymous"` strings from HTML content and it should load the resources nicely from that point, sending all validation cookies with each request.

**Comment by Menafista** [comment]
Oh yeah thank you, I just confused noreferer and crossorigin and because it was working on the others browsers I missed that.
Do you still plan to implement a referrer solution for manifest.json? (even if it can be patched individualy with sub_filters by adding the key, and that it's not a crucial file)
