### ISSUE TITLE
Amazon Error

### ISSUE THREAD

**Issue by osterhagenchemnitz** [kgretzky/evilginx2#104]
This is the error that you will get it when you click on sign in button:

Please Enable Cookies to Continue

To continue shopping at Amazon.com, please enable cookies in your Web browser.

Once you have enabled cookies in your browser, please click on the button below to return to the previous page.

**Comment by martinxsas** [comment]
Hello

Please send your skype or other id for talk about this

**Comment by osterhagenchemnitz** [comment]
>           Hello
> Please send your skype or other id for talk about this

ICQ: 744957727

**Comment by martinxsas** [comment]
I added..and here is my icq  740466101 

On 19-11-2018 21:41, osterhagenchemnitz wrote: 

>> Hello
>> 
>> Please send your skype or other id for talk about this
> 
> ICQ: 744957727 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/kgretzky/evilginx2/issues/104#issuecomment-440051505
[2]
