### ISSUE TITLE
Port 53 error 

### ISSUE THREAD

**Issue by Barenchi** [kgretzky/evilginx2#106]
[18:22:16] [inf] loading phishlets from: /usr/share/evilginx/phishlets/
[18:22:16] [inf] loaded phishlet 'facebook' made by @mrgretzky from 'facebook.yaml'
[18:22:16] [inf] loaded phishlet 'linkedin' made by @mrgretzky from 'linkedin.yaml'
[18:22:16] [inf] loaded phishlet 'outlook' made by @mrgretzky from 'outlook.yaml'
[18:22:16] [!!!] Failed to start nameserver on port 53

I execute this : 

root@ubuntu-s-1vcpu-1gb-lon1-01:~# netstat -tunalp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1701/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1444/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1444/sshd
udp    43008      0 127.0.0.53:53           0.0.0.0:*                           1701/systemd-resolv

So what to do ?

**Comment by kgretzky** [comment]
This is unrelated to Evilginx. Please use Google or StackOverflow.

**Comment by Zeus19971997** [comment]
Hey , I have a problem too. failed to start name serveur on port 53

**Comment by Zeus19971997** [comment]
acme: Error -> One or more domains had a problem:
[m.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.recona1.com - the domain's nameservers may be malfunctioning, url: 
[static.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for static.recona1.com - check that a DNS record exists for this domain, url: 
[www.recona1.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://www.recona1.com/.well-known/acme-challenge/5_gAn_sY4pdIE94wZmG3oU9eliwLkEiXiJy9lzF0O5s [64.227.105.244]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ub", url:       this is the error I got

**Comment by Zeus19971997** [comment]
[11:29:33] [inf] enabled phishlet 'paypal'
[11:29:33] [inf] setting up certificates for phishlet 'paypal'...
[11:29:33] [war] failed to load certificate files for phishlet 'paypal', domain 'recona1.com': open /var/root/.evilginx/crt/recona1.com/paypal.crt: no such file or directory
[11:29:33] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[11:29:51] [!!!] acme: Error -> One or more domains had a problem:
[b.stats.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for b.stats.recona1.com - check that a DNS record exists for this domain, url: 
[c.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for c.recona1.com - check that a DNS record exists for this domain, url: 
[c6.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for c6.recona1.com - check that a DNS record exists for this domain, url: 
[hnd.stats.recona1.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for hnd.stats.recona1.com - check that a DNS record exists for this domain, url: 
[recona1.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://recona1.com/.well-known/acme-challenge/nLzr5-RfNX-IerG53NouH30zd1fRsYL9XG9mBLnCi8Q [64.227.105.244]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ub", url:
