### ISSUE TITLE
Is this issue phishlet related? (Not asking for phishlet help)

### ISSUE THREAD

**Issue by hootyjeremy** [kgretzky/evilginx2#1062]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I am having issues with my first install which I'm doing locally for purposes of understanding session cookie stealing to bypass MFA. I can get a page to load but there are some issues with the login process and I am just trying to figure out if it is phishlet related. **I don't want help with correcting a phishlet if this is the source of the problem**. I just want to check if what I'm seeing is happening because of a phishlet. 

The problem: I had assumed that since all traffic is reverse-proxied, that all domains listed in the network tab of dev tools would begin with the domain name configured in evilginx. But I am seeing calls to actual servers which doesn't seem like I should be seeing this.  Should this not be happening? Should all domains be pre-pended with the one configured for evilginx phishlet/lures?

![image](https://github.com/kgretzky/evilginx2/assets/68588318/11cf161e-a011-4b74-82ac-873eab7d750e)

Thanks.

**Comment by Bullybnizz** [comment]
My Telegram handle @NoRemorse1011

**Comment by hootyjeremy** [comment]
I'm not trying to get involved in a Telegram chat. I just need a public comment answer if anybody can help me out here.

**Comment by matejsmycka** [comment]
yes, all domains should be in phishlet,  otherwise it wont work.

**Comment by hootyjeremy** [comment]
Oh, I see. I was hoping this was a turnkey thing instead of "some assembly required" so that I could just learn something quick about how to mitigate against cookie theft but it sounds like I'm going to have to deep dive into phishlet tailoring and maybe even source code. At least the repository is a good running start.

**Comment by gballer01** [comment]
> yes, all domains should be in phishlet, otherwise it wont work. If your domain is not proxied, then it is badly configured, I have Microsoft phishlet with MFA working, however i think its against rules to post it,

Please I would love to get in touch with you!! I have issue with mfa bypass!!
