### ISSUE TITLE
Can't find self-signed certs

### ISSUE THREAD

**Issue by CaseyCJohnston** [kgretzky/evilginx2#108]
Not sure if I'm missing something obvious here...  I am running evilginx2 2.1.0 in developer mode (following the breakdev guide), but the self-signed certificates do not appear to have been generated. I am getting an error message when trying to browse to the location of the created files that no such file or directory exists. I have already run the program, so I believe the certs should have been created. 

Any assistance is greatly appreciated.

**Comment by kgretzky** [comment]
Did you look in `$HOME/.evilginx` ?

**Comment by CaseyCJohnston** [comment]
I attempted to, but it does not look like that directory was created. Are there any logs that may indicate what is going wrong? Or is there something that I did incorrectly that could cause the behavior?

**Comment by kgretzky** [comment]
Please check that you have environment variables properly set up for your user account.
If `$HOME` is not set then this is an issue.

**Comment by CaseyCJohnston** [comment]
It looks like $HOME, $PATH, and $GOPATH are all set correctly. Do you have any other suggestions?

**Comment by kgretzky** [comment]
The directory must be created, otherwise Evilginx can't save configuration and the files it uses.
Please post output of `ls -al $HOME` and `ls -al $HOME/.evilginx`.

What OS and distro are you using?

**Comment by CaseyCJohnston** [comment]
I ended up just creating self-signed certs and creating $HOME/.evilginx manually. I'm running Ubuntu 18.04.1 in VMware. I currently have the tool working to the point where it satisfies my needs. Thank you.
