### ISSUE TITLE
Amazon Phislet not work on new Version 2.2.0 same error

### ISSUE THREAD

**Issue by silcockmitchell** [kgretzky/evilginx2#111]
Amazon Phislet not work on new Version same error (redirect to original site) not intercepted any password or cookies

**Comment by kgretzky** [comment]
Phishlets were not addressed in the update, but the framework itself. Phishlets are not maintained and are up to authors to be fixed. You can also try fixing it and contribute.

**Comment by silcockmitchell** [comment]
I am looking at the cookie problem from their website, could evilginx2 pass this by activating inside another browsing agent ?
