### ISSUE TITLE
Feature request: Better control of sent cookies

### ISSUE THREAD

**Issue by n0whereman** [kgretzky/evilginx2#114]
Hi there,

I could not find a related issue/feature request and thought this might be helpful.
Some pages include (huge) javascripts that are meant to help with analytics. The scripts create and set Cookie, which can reveal our phishing domain, e.g.:
```
_mixpanel={"distinct_id": "123412312","$initial_referrer": "our.phising.site",
"$initial_referring_domain": "our.phising.site","New User": "","Application": "","Edition": "","SKU": ""};
```
It can be solved with a workaround, which requires users to change the incriminating javascript but that's not very generic and can be very daunting, especially when the script is a huge mess.
It could be easier to instruct the evilginx (some phislet configuration) to NOT include certain Cookie values. 
What do you think ? 

Yours truly,
Martin

**Comment by kgretzky** [comment]
Thanks for the suggestion. For now, I'm not sure what to do with it as if I do an automatic replacement it may accidently break functionality of some websites.

I'll keep it as a feature request and maybe will return to it in the future.
