### ISSUE TITLE
 Failed to start nameserver on port 53

### ISSUE THREAD

**Issue by idk451** [kgretzky/evilginx2#116]
Hello,
when i run evilginx2 with the ./main an error message appears "can not start the name server on port 53" and another one with "listen tcp: 443: bind: permission denied" do you know what it is is of ?
thank you for answering me if you can

**Comment by kjblack** [comment]
Run as sudo

**Comment by NoShortNaame** [comment]
Thank you for the big work @kgretzky !
I have the same issue displaying :

[!!!] Failed to start nameserver on port 53

Even being Root. I searched a service listening on port 53 but the only one is 'systemd-resolved' in charge of ... DNS

Am I wrong somewhere ?
