### ISSUE TITLE
recaptcha problem !

### ISSUE THREAD

**Issue by evilginx** [kgretzky/evilginx2#117]
hello kuba.. thanks you for evilginx 2.2 project...Trying to make phishlets for paltalk.com ...I created phishlets..I created a certificate with evilginx...site opened and wrote my username and password..but the page does not progress when I press the forward button..page protected by google recaptcha..The site key in the lower-right corner writes is incorrect...what should i write to proxy_host and sub_filters section for google recaptcha ??

real login page = https://commerce.paltalk.com

**Comment by kgretzky** [comment]
Recaptcha requires a dedicated phishlet on its own and it is not easy to do, because of many implemented protections in it. There is no easy way to proxy the recaptcha validation.
