### ISSUE TITLE
instagram cookies problem !

### ISSUE THREAD

**Issue by CyberTheReape** [kgretzky/evilginx2#119]
hello kuba... i did a new phishlets for instagram. password and usernames are coming...but cookies don't come..

example 1 :

according to my research :
cookies that appear before you log in yet = csrftoken,mcd,mid,rur

Cookies seen after login = ds_user_id,sessionid,shbid,shbts,urlgen

now I combine them all in this way :

auth_tokens: 
  - domain: '.instagram.com'
    keys: ['csrftoken','mcd','mid','rur','ds_user_id','sessionid','shbid','shbts','urlgen']

I'm experimenting but no cookies are coming and the page is not redirected..

example 2 :

But when I do it like this, it only catches 1 cookie and redirects the page

auth_tokens: 
  - domain: '.instagram.com'
    keys: ['.*,regexp']

but 1 cookie does not work to log on...this code only catches 1 cookie = ['.*,regexp']
Why is this happening ?  (excuse me i am speaking bad english......i am speaking with google translate)

![ekran goruntusu 2018-11-25 18 49 07](https://user-images.githubusercontent.com/42475284/48981309-abc7ae00-f0e4-11e8-92b2-0f0144b99bac.png)

**Comment by Lglaplante** [comment]
Mind sharing the phishlets ?

**Comment by AyoubElya** [comment]
Please ?

**Comment by XBALTI** [comment]
if you can create a phishlets for me i will pay you 100 $ btc 
this my email : yassin.balti2229@gmail.com

**Comment by Lglaplante** [comment]
You don't need to pay
Once you understood where and when to put parameters, they are pretty easy to make

**Comment by AyoubElya** [comment]
@Lglaplante oh.. So help us please, send a sample 👍 !

**Comment by princenasario** [comment]
Phishlet Please

**Comment by bojanrodic** [comment]
I am testing this phishlet and it is not working
It just not send anyting, not even credintials
i tested from computer PC too, because i saw you wrote that it does not work from mobile.
