### ISSUE TITLE
Problem getting started

### ISSUE THREAD

**Issue by Santa131** [kgretzky/evilginx2#12]
Set up your server's domain and IP using following commands:
config domain yourdomain.com
config ip 10.0.0.1

Have problem -  [err] config: invalid syntax: [domain ***********d.com config ip ***.161.**.195]
Help me pls

**Comment by kgretzky** [comment]
This doesn't make sense at all.

**Comment by Santa131** [comment]
Why? I do on the basis of your manual

**Comment by kgretzky** [comment]
Domain has to be a valid registered domain (by you) and you need to specify a valid IP of your external server.

It seems you are just copy-pasting what is in the blog.

**Comment by Santa131** [comment]
figured out) 
[inf] setting up certificates for phishlet 'linkedin'...
[13:24:01] [war] failed to load certificate files for phishlet 'linkedin', domain 'authorization-icloud.com': open /root/.evilginx/crt/authorization-icloud.com/linkedin
.crt: no such file or directory
