### ISSUE TITLE
evilginx does not properly capture credentials

### ISSUE THREAD

**Issue by hollow1** [kgretzky/evilginx2#120]
Hi man, very nice project!

I experience the following issue: evilginx does not capture the credentials, but captures the cookies.
Note that I successfully login, using captured cookies.
Part of yaml config:

```credentials:
  username:
    key: ''
    search: '"username":"([^"]*)'
    type: 'json'
  password:
    key: ''
    search: '"password":"([^"]*)'
    type: 'json'
```

Post request (modified) it supposed to parse :
```
POST /api/v1/authn HTTP/1.1
Host: domain.com
Cookie: <omited>

{"username":"user@domain.com","options":{"warnBeforePasswordExpired":true,"multiOptionalFactorEnroll":true},"password":"password"}
```
In debug I see that evilginx successfully sends this request:
```
[14:58:47] [dbg] POST: /api/v1/authn
[14:58:47] [dbg] POST body = {"username":"user@domain.com","options":{"warnBeforePasswordExpired":true,"multiOptionalFactorEnroll":true},"password":"password"}
```

But it never recognizes the parameters as login and password. 
Am I missing something?

**Comment by kgretzky** [comment]
Hey! That indeed was a bug with 2.2.0 release.
You need to pull lastest changes from `master` branch and version 2.2.1 has that fixed.
