### ISSUE TITLE
Timeout during connect(likely firewall problem)

### ISSUE THREAD

**Issue by Lglaplante** [kgretzky/evilginx2#121]
When trying to enable the Amazon phishlets( or any other phishlets) I always get this error: 
"Timeout during connect(likely firewall problem)"
Validation for www.amazon.fr.phishdomain.ml:80
Resolved to:
      [myPublicIp]
Used: [myPublicIp]

Nameservers are set to point to the server Ip configured in Evilginx (both ns1 and ns2)

I opened port 80 to make sure it IS opened
I changed several times the A DNS record + IP nameservers to see if it was the IP doing this, always got the same error

Any idea on why I keep getting this error ?

**Comment by kgretzky** [comment]
I cannot help with that. You need to troubleshoot the connection yourself.
All I can say that there is no known bug and this is all result from improper configuration.
Read the blog post again and refer to guides how to properly set up custom nameservers.
