### ISSUE TITLE
Resolved. please close

### ISSUE THREAD

**Issue by AntonyGormley** [kgretzky/evilginx2#126]
resolved

**Comment by Lglaplante** [comment]
You sure there is a Youtube Phishlet ?
Anyway just look at a phishlet and you will understand pretty quickly (also do a Inspect Element on logins pages and you will understand more)

**Comment by AntonyGormley** [comment]
https://www.youtube.com/watch?v=GDVxwX4eNpU

**Comment by AntonyGormley** [comment]
there is a explication on this video but is to short.....
