### ISSUE TITLE
Port 53 is used by other service or you need root privileges.

### ISSUE THREAD

**Issue by git78** [kgretzky/evilginx2#127]
_Originally posted by @kgretzky in https://github.com/kgretzky/evilginx2/issues/125#issuecomment-442965219_

okay, thanks, but how can I close the listening service on the port 53 ?

**Comment by AntonyGormley** [comment]
kill command

**Comment by wikijm** [comment]
https://www.admintome.com/blog/turning-off-systemd-resolvd/
