### ISSUE TITLE
I can't catch cookies

### ISSUE THREAD

**Issue by evilginx** [kgretzky/evilginx2#128]
hello kuba. i did a new phishlet.but I have some problems.I have 3 different domain names when I look at the cookies of the site.

exapmle :

    .phis.com
    www.phish.com
    .www.phish.com     #first line has dot mark ...but after logging in this domain name appears in cookies

did everything but could not catch the cookies..I can catch cookies with just one method, but it is doesn't work ..

only this is working , but not enough to log in

example :
       - domain: 'www.pish.com'
         keys: ['JSESSIONID','.*,regexp']

I tried changing all methods, but none worked.

There are 9 cookies >>>  .phish.com
but although there are 9 cookies for this domain, evilginx cannot catch cookies ( .phish.com )

what may be the problem ? Can 3 domain names for cookies be written to the phishlet file??

exapmle : 

     - domain: '.pish.com'
       keys: ['cookies'']
     - domain: 'www.pish.com'
       keys: ['JSESSIONID','.*,regexp']
     - domain: '.www.pish.com'
       keys: ['cookies']

i have one last question ..

Can we use both sections  for cookies? ['. *, regex'] 

example :

       - domain: '.pish.com'
         keys: ['.*,regexp']
       - domain: 'www.pish.com'
         keys: ['.*,regexp']

good night !

**Comment by kafkaesqu3** [comment]
i've been having the same problem. I haven't been able to get my phishlets to recognize the session tokens, even with '.*'

temporary bypass is to run in debug mode

**Comment by evilginx** [comment]
@kafkaesqu3 it is not working yet?

**Comment by hypnoticpattern** [comment]
Did you add an auth_urls section? If there is at least one regexp evilginx needs to understand when the user logged in using auth_urls

**Comment by evilginx** [comment]
I've added some url addresses, I wrote in the sub_filter section.

I need 3 different cookies to sign in..
    .phish.com     <<<< i need cookies for this 
    www.phish.com <<< i need cookies for this 
    .www.phish.com <<< i need cookies for this

I can only capture all cookies with the following method

   - domain: '.pish.com'
     keys: ['.*,regexp']
maybe i can add 1 cookie name next to regexp......
but I don't know if I can catch "www.phish.com" and ".www.phish.com" cookies with this method..
I think with the above method I can only lick ".phish.com" cookies..

do you have an idea? @hypnoticpattern
