### ISSUE TITLE
Cannot Phish the Credentials for Amazon

### ISSUE THREAD

**Issue by Yash0day** [kgretzky/evilginx2#130]
The framework is working fine for Outlook or Linkedin phishlets, But getting nothing for Amazon.

![amazon4](https://user-images.githubusercontent.com/24827905/49515865-1a172800-f8be-11e8-991b-f3f33d5747ff.PNG)

The Phishing site is working fine but after the victim enters his credential, the `submit` button of the Phishing site lands to the original Amazon site - `https://amazon.com/ap/sign`.

The "session" section of the framework shows like this:

![amazon5](https://user-images.githubusercontent.com/24827905/49517103-5435f900-f8c1-11e8-9916-2bfd1784de0c.PNG)

My question is what is happening behind the scene?How to get the framework working for phishing using Amazon phishlet?

**Comment by brendancboyle** [comment]
Can you provide your phishlet and logs with the `-debug` flag on?

**Comment by rent48bnb** [comment]
I have the same problem
![phish](https://user-images.githubusercontent.com/44444786/50001155-d1600e80-ff50-11e8-92b6-d3b63e6e78fc.JPG)

**Comment by maisonmargiela0** [comment]
I have the same problem!!!
CAN ANYONE RESPOND TO THIS PROBLEM PLEASE??

THANK YOU!!

**Comment by maisonmargiela0** [comment]
> 
> 
> I have the same problem
> ![phish](https://user-images.githubusercontent.com/44444786/50001155-d1600e80-ff50-11e8-92b6-d3b63e6e78fc.JPG)

HI rent48bnb,

Did you solve the problem? I have the same issue!

Thank you

**Comment by rent48bnb** [comment]
No, I try now to make a new phishlets of airbnb...but I don't know to make
it....you have idea?
Thanks you

**Comment by kgretzky** [comment]
Phishlet author needs to fix it if he/she wants. You can submit a fix as a PR if you want to contribute. Closing since there is no solution coming.
