### ISSUE TITLE
Logging problem

### ISSUE THREAD

**Issue by xerox1122** [kgretzky/evilginx2#131]
I have a website where the login form is similar to outlook, you first enter the username click next, password login. I made a phishlet that works i get the session cookie but there is a problem logging the username and password.
The username is sent through a POST of a variable called x that has the following form: [username, null,null]. After you click next and go to the password field, the value of the pass is sent through the same parameter x with the form [encrypteduser, password,null].
If there is a 2FA the end parameter is x[encrypteduser, encryptedpass, code]
How do i log the user and pass? If i log them as x i get both username and password as the last string.

**Comment by kgretzky** [comment]
I can't help much without seeing exact packet contents.

All I can suggest is that you use regular expressions to extract the data that you want from POST values.

**Comment by princenasario** [comment]
Could you please help me with the instagram phishlet?
