### ISSUE TITLE
Add debug info when force_post is successful

### ISSUE THREAD

**Issue by AntonyGormley** [kgretzky/evilginx2#132]
Hello,
there is anyway to see if the force post was successful ? Anything in the debug mode?

force_post:  
  - path: '/sessions'
    search:
      - {key: 'session\[user.*\]', search: '.*'}
      - {key: 'session\[pass[a-z]{4}\]', search: '.*'}
    force:
      - {key: 'remember_me', value: '1'}
    type: 'post'

**Comment by kgretzky** [comment]
Hi. I believe there is no output on that now. I'll add that to TODO, to add some info when it triggers in debug output.
