### ISSUE TITLE
Encoding of token parameter causing redirect

### ISSUE THREAD

**Issue by kafkaesqu3** [kgretzky/evilginx2#133]
I am trying to get evilginx to handle the following redirect so I can have a link that looks like a docs link that redirects to the login page. This is the actual redirect on `docs.google.com`: 

```
HTTP/1.1 302 Found
Content-Type: application/binary
Location: https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=https://docs.google.com/&followup=https://docs.google.com/&emr=1
```

Here is a `sub_filter` i have written to handle it. 

```  
  - {
    triggers_on: 'docs.google.com', 
    orig_sub: 'docs', 
    domain: 'google.com', 
    search: 'https:\/\/{hostname}\/', 
    replace: 'https://{hostname}/', 
    mimes: ['text/html', 'text/javascript', 'application/json']
  }
```

Unfortunately, this is encoding the token parameter in my request, causing the client to issue this request. 

```
GET /ServiceLogin?service=wise&passive=1209600&continue=https://docs.google.com/document/d/1D84nxp0ej2f_10/edit?eu%3D9842&followup=https://docs.google.com/document/d/1DspK2FchGn_10/edit?eu%3D9842&ltmpl=docs
Host: accounts.phishing.time
```

Is there a way to prevent evilginx2 from encoding the token parameter? I can't seem to get a regex to ignore this

**Comment by kgretzky** [comment]
I'm not sure I understand the issue.
`sub_filters` only manipulate the content of HTTP response body, they do not affect the URL of HTTP requests.

**Comment by kafkaesqu3** [comment]
It is my understanding that `sub_filters` should apply to `Location` header in HTTP response (I believe this happens at https://github.com/kgretzky/evilginx2/blob/71dd650723906b38b9fe837d8ab330d19cbeef14/core/http_proxy.go#L437

Would it not make sense to make sure the token value isn't encoded?

**Comment by kgretzky** [comment]
Did you test this issue with version 2.3?
