### ISSUE TITLE
Help my phishlets don't captured nothing (mail, pass or cookies)

### ISSUE THREAD

**Issue by rent48bnb** [kgretzky/evilginx2#142]
Help my phishlets sellercentral.amazon.de don't captured nothing (mail, pass or cookies)...any help please

**Comment by kgretzky** [comment]
Probably something changed on the website and you can wait for the author to fix the phishlet or you can try to fix it yourself.

**Comment by rent48bnb** [comment]
can you teach me to make a phishlets?

>
