### ISSUE TITLE
Evilginx2 behind internet box

### ISSUE THREAD

**Issue by Cedrik76** [kgretzky/evilginx2#145]
Hi to the community, 

I want to use Evilginx2 behind my internet box. All I need is to redirect port 53, 80and 443 to my computer?

if not, how can I have a public IP address directly accessible from my computer to avoid port forwarding? with a modem + SIM card?

**Comment by BaTuC** [comment]
Yes, you should do this.
But the questions is : do you really want to ? :-D

**Comment by BaTuC** [comment]
I think it is better not to use your home address to host phishing pages. Personal belief.
You can use your own cloud server. Besides kgretzky offers a promo code at Digital Ocean on https://github.com/kgretzky/evilginx2   #Installation

**Comment by kgretzky** [comment]
Yes. I advise to set up an external VPS for this. Configuring network setup is out of scope of this issue tracker - try stackoverflow.
