### ISSUE TITLE
Getting credentials value

### ISSUE THREAD

**Issue by BaTuC** [kgretzky/evilginx2#147]
Hi everybody,
I managed to create mu first page on my evilginx2 instance, I get the facebook's cookies and I can import them into my browser and connect.
When I display my sessions I have: 
    password : true
      tokens : captured

is it possible to have the password value in clear text?
Is it just for facebook phislet or other display creds ?
Thank you. Thank you.

**Comment by kgretzky** [comment]
I haven't tested the Facebook phishlet for a long time. Not sure if it still works.

**Comment by BaTuC** [comment]
Hi, I've resolved this problem by my own.
It's seems that the FB phishlet is still ok. However creds are shown only if user do not have MFA activated.

**Comment by kgretzky** [comment]
Thanks for info! Good to know!
