### ISSUE TITLE
Instagram Phishlet

### ISSUE THREAD

**Issue by princenasario** [kgretzky/evilginx2#153]
I just finished working on an Instagram phishlet. It works perfectly fine. How should I send it so that it comes up in the main branch of this git?

**Comment by diewithurlie** [comment]
https://help.github.com/articles/about-pull-requests/   maybe this can help

**Comment by ahhh** [comment]
You can navigate [here](https://github.com/kgretzky/evilginx2/tree/master/phishlets), then click "Create New File", to do it via the GUI
