### ISSUE TITLE
can't get certificate on virtual kali

### ISSUE THREAD

**Issue by drjekill4** [kgretzky/evilginx2#159]
Hi/ I have encountered problem with obtaining cert for my site
I'm running site on gitlab server with default ip 35.185.44.232 
I have set it up from web interface on my windows10 host system and evilginx commands are put in terminal in kali rolling on vb
congif domain username.gitlab.io
config ip 35.185.44.232 
I get error urn-acme-error-unauthorized-status-403

**Comment by kgretzky** [comment]
`gitlab.io` doesn't seem to be the domain you own. You need to register a new domain yourself and point its nameservers to your external server where evilginx is running.
