### ISSUE TITLE
Evilginx does not work without internet access

### ISSUE THREAD

**Issue by dozernz** [kgretzky/evilginx2#161]
Evilginx requires internet access to start. Without internet access, it blocks on an error like
```
[17:42:00] [!!!] certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org on 192.168.1.1:53: read udp 192.168.1.2:52799->192.168.1.1:53: i/o timeout
```
This also happens even with the `-developer` flag used to run it locally.
As far as I can tell, the connection lets-encrypt is for the ACME client used to automatically obtain certificates. 

Evilginx would be useful without using internet access, for phishing on only internal networks where internet access is not available or needs proxy access, as well as for testing when internet access is not available or desired.

Checked with go 1.11 and evilginx2 built from master branch.

**Comment by kgretzky** [comment]
Thanks! Will check it out.

**Comment by maisonmargiela0** [comment]
Hello,

Great job guys but unfortunatelly for me I am beginner with Kali Linux. I have these 2 problems. Please some one help me:
 1st
root@kali:~/evilginx2# go get -u github.com/kgretzky/evilginx2
root@kali:~/evilginx2# cd $GOPATH/src/github.com/kgretzky/evilginx2
root@kali:~/go_projects/src/github.com/kgretzky/evilginx2# make
make: dep: Command not found
make: *** [Makefile:8: deps] Error 127

2nd
            domain : vvf-c.com
                 ip : 192.187.29.41
       redirect_key : jn
   verification_key : gn
 verification_token : ce26
       redirect_url : https://www.youtube.com/watch?v=dQw4w9WgXcQ

: phishlets hostname linkedin vvf-c.com
[13:09:18] [err] unknown command: phishlets

THANK YOU FOR HELPING ME!!!

**Comment by Ondrik8** [comment]
Hi very good project!)

my problem(((

`[01:46:00] [inf] loading phishlets from: /root/go/src/github.com/kgretzky/evilginx2/phishlets
[01:46:00] [!!!] certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org: Temporary failure in name resolution
root@vm512400:~/go/src/github.com/kgretzky/evilginx2#`

screenshot:   http://prntscr.com/mfhhqy       http://prntscr.com/mfhilr    http://prntscr.com/mfhjcs   http://prntscr.com/mfhjwx

**Comment by IonizeCbr** [comment]
any progress on this ?

There are instruction to disable everything on port 53 for example `systemd-resolved`

then the 
`[!!!] certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org: Temporary failure in name resolution`

just fails therefore these instructions are contradictory is Evilginx supposed to have its own internal DNS resolver in go or something ?

**Comment by HachimanSec** [comment]
Hi everyone, 

I just tried to containerise evilginx2 and received a similar issue. However, I can manually wget the directory. 

Any idea?
[```
13:37:42] [inf] loading phishlets from: ../phishlets/
[13:37:42] [!!!] certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority

/app/bin # wget https://acme-v01.api.letsencrypt.org/directory
Connecting to acme-v01.api.letsencrypt.org (104.111.246.175:443)
directory            100% |*****************************************************************************************************************************************************|   658  0:00:00 ETA
/app/bin # ls
directory  evilginx
/app/bin # cat directory
{
  "2HuMuVOhLok": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
```

**Comment by HachimanSec** [comment]
Just solved it, it was an issue on my end. Simply ca-certs have been missing. Didn't got that one in the beginning.

```
app/bin # apk add  ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20190108-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 6 MiB in 15 packages
```

**Comment by arinze12345** [comment]
> Evilginx requires internet access to start. Without internet access, it blocks on an error like
> 
> ```
> [17:42:00] [!!!] certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org on 192.168.1.1:53: read udp 192.168.1.2:52799->192.168.1.1:53: i/o timeout
> ```
> 
> This also happens even with the `-developer` flag used to run it locally.
> As far as I can tell, the connection lets-encrypt is for the ACME client used to automatically obtain certificates.
> 
> Evilginx would be useful without using internet access, for phishing on only internal networks where internet access is not available or needs proxy access, as well as for testing when internet access is not available or desired.
> 
> Checked with go 1.11 and evilginx2 built from master branch.

i can help you with the issue..rickorkins@gmail.com...it works but they wont let you know that it does so.....email me rickorkins@gmail.com
