### ISSUE TITLE
Instagram phishlet for mobile

### ISSUE THREAD

**Issue by princenasario** [kgretzky/evilginx2#163]
I have made an instagram phishlet. It works perfectly on desktops, capturing both credentials and cookies but it does not work on mobile platform. What changes should i make to the script? it already has the phish_sub with 'm' and the triggers in sub_filters to 'm.instagram.com'. Why is it not working? Script in Pull request

**Comment by kgretzky** [comment]
Please wait for Evilginx 2.3. It should make most of the changes automated and it may fix the issue you are having with redirecting to mobile login page.

**Comment by bojanrodic** [comment]
I am testing this phishlet and it is not working
It just not send anyting, not even credintials
i tested from computer PC too, because i saw you wrote that it does not work from mobile.

**Comment by princenasario** [comment]
@bojanrodic all the configurations are perfect. If you think that it is not working, I can send you a video of it working perfectly.

**Comment by zenaze** [comment]
> EDITED
> ALL WORKS
> Only think is if you have 2factor auth than it freezes on where it should continue after prompting code.
> you can test yourself if you want.

Please could you share your working instragram.yaml phishlet?
i managed to get mine to work but it still doesnt work on mobile devices.
