### ISSUE TITLE
Running Evilginx in the background

### ISSUE THREAD

**Issue by princenasario** [kgretzky/evilginx2#164]
How do i keep Evilginx running in the background without having to be connected the whole time? My Putty session disconnects after a while though i have the putty settings to send tcp requests every 1 minute

**Comment by kgretzky** [comment]
You need to run evilginx in a `screen` or `tmux` session for it to stay active after disconnecting.

**Comment by princenasario** [comment]
I'm using windows. My putty session disconnects from my droplet (digitalocean) which I use for Evilginx2. What should I do? @kgretzky
