### ISSUE TITLE
Feature idea - add postprocessing handler

### ISSUE THREAD

**Issue by ntrippar** [kgretzky/evilginx2#166]
# Idea
so lets imagine have a scam for x site, but you know that when the user logs in the token will be valid for x minutes,  could be nice to have a generic way to add in the config file when a user logs in execute that path and send over the stdin a json with the data that the evilnginx2 got so the external program can fetch data do more work

## why im chosing a path and not implement plugins in go?

the main idea with this is not limit to people that only code in GO. so anyone can implement some extension in python/rust or whatever they want.

**Comment by kgretzky** [comment]
Thanks! This is a very good idea. Definitely will keep that on the list!

**Comment by maisonmargiela0** [comment]
Hello,

Great job guys but unfortunatelly for me I am beginner with Kali Linux. I have these 2 problems. Please some one help me:
1st
root@kali:/evilginx2# go get -u github.com/kgretzky/evilginx2
root@kali:/evilginx2# cd $GOPATH/src/github.com/kgretzky/evilginx2
root@kali:~/go_projects/src/github.com/kgretzky/evilginx2# make
make: dep: Command not found
make: *** [Makefile:8: deps] Error 127

2nd
domain : vvf-c.com
ip : 192.187.29.41
redirect_key : jn
verification_key : gn
verification_token : ce26
redirect_url : https://www.youtube.com/watch?v=dQw4w9WgXcQ

: phishlets hostname linkedin vvf-c.com
[13:09:18] [err] unknown command: phishlets

THANK YOU FOR HELPING ME!!!
