### ISSUE TITLE
unable to obtain certificate

### ISSUE THREAD

**Issue by jesse234** [kgretzky/evilginx2#167]
hello bro great work nice one , but evilginx 2 is never for noobs i have tried to setup evilginx for weeks now and i have explored all ideas (tutorials) i still cant get any phishlets work because i cant get a certificate from lets encrypts , you have created a create tool but i think you should elaborate more on how to set it up because it is not as easy as you think it is . and for the record, GOOD JOB

**Comment by maisonmargiela0** [comment]
Hello,

Great job guys but unfortunatelly for me I am beginner with Kali Linux and I have the same problem I think. Please some one help me: I have this issue

[www.vvf-cc.info] acme: Error 400 - urn:acme:error:dns - DNS problem: NXDOMAIN looking up A for www.vvf-cc.info
Error Detail:
	Validation for www.vvf-cc.info:80
	Resolved to:
		
	Used: 


[14:56:22] [err] [fls-na.vvf-cc.info] acme: Error 400 - urn:acme:error:dns - DNS problem: NXDOMAIN looking up A for fls-na.vvf-cc.info
Error Detail:
	Validation for fls-na.vvf-cc.info:80
	Resolved to:
		
	Used: 


[14:56:22] [err] [images-na.vvf-cc.info] acme: Error 400 - urn:acme:error:dns - DNS problem: NXDOMAIN looking up A for images-na.vvf-cc.info
Error Detail:
	Validation for images-na.vvf-cc.info:80
	Resolved to:
		
	Used: 


[14:56:22] [!!!] failed to obtain certificates


THANK YOU FOR HELPING ME!!!

**Comment by kgretzky** [comment]
You need to set up Evilginx VPS as a nameserver for your domain.
