### ISSUE TITLE
Running Evilginx in the Background. Windows 10

### ISSUE THREAD

**Issue by princenasario** [kgretzky/evilginx2#168]
I'm using Windows 10. How do i keep Evilginx running in the background without having to be connected the whole time? On using bitvise SSH client, my session stays active but my terminal gets disconnected resulting in the closing of the script Evilginx2. What should I do?

**Comment by kgretzky** [comment]
Please use google to check how to use SSH with keep-alives and get help with the SSH client that you use.
Question not relevant to tool itself.
