### ISSUE TITLE
I can not get anything with amazon pishlet!! Does not work!

### ISSUE THREAD

**Issue by maisonmargiela0** [kgretzky/evilginx2#169]
Good job guys.
All your phishlets work for me with droplet ubuntu besides the amazon phishlet.
The amazon pshishlet does not work properly.
Can some one put a video or something with amazon phishlet working?

Thank you for fixing it or to reply me with a solution!
![phishlets issue](https://user-images.githubusercontent.com/46847414/51444901-6ac3d280-1cfe-11e9-9338-565a42a2e653.jpg)

**Comment by kgretzky** [comment]
Please contact the phishlet author. I am not supporting phishlets made by other people. Thanks.

**Comment by maisonmargiela0** [comment]
Do you know how to hide the evilginxh url phishlets for everyone , every
html, you know like you put robots.txt with disallow everysite to read your
information. Something that only the person who have your link can access
it no other robots.

Thank you very much!!!

**Comment by maisonmargiela0** [comment]
Do you know how to hide the evilginxh url phishlets for everyone , every
html, you know like you put robots.txt with disallow everysite to read your
information. Something that only the person who have your link can access
it no other robots.

Thank you very much!!!
