### ISSUE TITLE
Facebook login does not submit on mobile devices

### ISSUE THREAD

**Issue by kjblack** [kgretzky/evilginx2#17]
First of all..... Epic. This tool is incredible and I'm very excited for the "phishlets how-to"!

The facebook phishlet does not work when visiting the phishing link from a a mobile device.
Pressing submit appears to have no action from the device at all.

Testing on Chrome (android) and Safari (iphone)

Thanks

**Comment by kjblack** [comment]
Thanks,

I work for a company that provide penetration testing services. 
I can see this tool proving some real value add for our engagements in addition to the other types of phishing we currently provide.

Naturally, the facebook (and other "personal" account) phishlets are cool but we are very keen to get some enterprise phishlets working such as o365 and a howto guide to build our own (NetScaler) etc.

thanks

**Comment by embutidox** [comment]
Hi, I am trying your awesome tool, but I have the same problem with mobile devices.

Do you see the mobile JS ? is it the same as Desktop or not?

Thx in advance.

**Comment by jevranaberejit** [comment]
I have same problem, does not work on cellphone.
has anyone fixed bug durring this for cellphone ?

**Comment by laurentkeusch** [comment]
Same issue happening on desktop chrome and mobile chrome !

**Comment by gautiermorel** [comment]
Any news ? :)

**Comment by kgretzky** [comment]
I won't be fixing this, so it is up to the community to submit a PR.

**Comment by Amzkuush** [comment]
Thank's let us know when the bug will be fixed :)

**Comment by gautiermorel** [comment]
Hmm, for quick updates - I recently trie to find a workaround for mobile devices.
However, I think facebook manages to detect that the requested content will be used as a potential phishing attack. I have 2 reasons to believe that way:

- 1. When you click "install app" from the banner, it will redirect to a kind of "malicious detected form"
- 2. I shared the link throw a message app  and as auto-generated thumbnail i got : https://www.youtube.com/watch?v=dQw4w9WgXcQ (Rick Astley - Never Gonna Give You Up (Video)) - probably a kind of easter egg from facebook developers ?

**Comment by kjblack** [comment]
>
> That YouTube link is the default redirect page on evilginx when a request
> is made to the webserver that doesn't contain the correct URI.


It's best to change this when using on an actual engagement.

**Comment by chuoh** [comment]
> That YouTube link is the default redirect page on evilginx when a request is made to the webserver that doesn't contain the correct URI. It's best to change this when using on an actual engagement.

how do you solve this whats the correct uri
