### ISSUE TITLE
Unusual Login Attempt. Instagram

### ISSUE THREAD

**Issue by princenasario** [kgretzky/evilginx2#172]
My Digital Ocean droplet is situated at a nearby city from my place. When I use the instagram phishlet,  I get a suspicious login attempt for which we need to verify using email or a sms. Is there any way to bypass that ? and even if i cross the unusual login screen, my page doesnt redirect.

**Comment by kgretzky** [comment]
Ask instagram support how you can bypass that. Question is not relevant to the tool.
