### ISSUE TITLE
Site can't be reached 

### ISSUE THREAD

**Issue by hackison** [kgretzky/evilginx2#176]
Hey bro i followed this video that has been posted in one of you issue session 
( VIDEO LINK: https://www.youtube.com/watch?v=blVRs39DAmA )
and i followed all the steps and at last i used lures to get the url but when i try to access the usrl it is showing sit cant be reached what shall i do mow please help me guys 

Here is the screen shots 
![screenshot from 2019-01-23 03-26-07](https://user-images.githubusercontent.com/39798618/51568818-a1e1e180-1ec0-11e9-9858-93e692e01a55.png)
![screenshot from 2019-01-23 03-30-59](https://user-images.githubusercontent.com/39798618/51568819-a27a7800-1ec0-11e9-9c56-2b37ee1ada0b.png)
![Uploading Screenshot from 2019-01-23 03-34-17.png…]()

**Comment by hackison** [comment]
Bro Should i add all those three in /etc/hosts ??

**Comment by hackison** [comment]
by the way how can i delete the hostname that i previously created . because i would like do do it fresh :)

**Comment by kgretzky** [comment]
Best to understand what you are doing first.

https://www.siteground.com/kb/how_to_use_the_hosts_file/

**Comment by hackison** [comment]
how can i remove the hostname that i created ( outlook.testing-outlook.tk ) . I tried to delete all evilginx files from my linux and freshly installed. But after that also evilginx is displaying the hostname when i start a new evilginx.

**Comment by hackison** [comment]
thank you let me do 

> Best to understand what you are doing first.
> 
> https://www.siteground.com/kb/how_to_use_the_hosts_file/

thank you ill try it once again

**Comment by hackison** [comment]
Bro solved i have done it ....!!! but there is request keep  on going in my terminal ( unauthorized access from mozilla ) like that its going

**Comment by olulabyrinth** [comment]
Am currently having the same issue, have edited the host file. But still "The connection has timed out

An error occurred during a connection to " Please help

**Comment by usethisname1419** [comment]
im getting 'site can't be reached' i think i have everything set up correctly. I created A records using my hostname pointing to VPS public IP, i added get-hosts into /etc/hosts, disabled services running on 53, evilginx shows no errors when running and when creating the lure, when i use that link it says 'site can't be reached'
