### ISSUE TITLE
Google.yaml attention

### ISSUE THREAD

**Issue by elktarni** [kgretzky/evilginx2#180]
Hello Everyone 
and thanks to the team EVILGINX for creating that awesome bypass f2a
I just wanna a Help please with phishlets google
here is the code  : https://github.com/elktarni/google.yaml/blob/master/google
can anyone make some edit for it 
I encountered some issue

**Comment by ewhitman1** [comment]
@kgretzky if you have google phishlet then why don't you release it?

**Comment by ewhitman1** [comment]
@kgretzky yeah!
how about a penthouse, a mansion, an oil rig and also how about an island ohhh and i forgot a chartered plane :D :) lol...
[gtest.txt](https://github.com/kgretzky/evilginx2/files/2790780/gtest.txt)

i am just stuck at tap yes functionality...  request timed out error

**Comment by kgretzky** [comment]
The request timed out error happens due to Google's security protection hidden in obfuscated JS code.

**Comment by ewhitman1** [comment]
any idea what I can do in that ?

**Comment by kgretzky** [comment]
Find it and bypass it :)

**Comment by ewhitman1** [comment]
@kgretzky just for a li'l help should I look for that protection part in obfuscated JS?

**Comment by kgretzky** [comment]
Yes. Then when you find it, you should replace it with something else using `sub_filters`.

**Comment by ewhitman1** [comment]
ohh! thankyou
btw @kgretzky you do have working google phishlets. Am I Right?

**Comment by kgretzky** [comment]
Yes, but I decided not to share it to not get us all closer to the apocalypse.

**Comment by ewhitman1** [comment]
@kgretzky I can understand about that apocalypse :smile: 
@kgretzky how to bypass csrf policy error in apple?

**Comment by kgretzky** [comment]
Not sure. Try to add hostnames triggering CORS to `proxy_hosts`.

**Comment by ewhitman1** [comment]
Have added that CORS to proxy_hosts, will give it a try.
@kgretzky have you tried making apple or icloud ?

**Comment by ewhitman1** [comment]
@kgretzky Hi, able to remove timed out issue from google but after tapping yes on my device and matching the number shown , I am unable to submit it

**Comment by ewhitman1** [comment]
Loading failed for the <script> with source “https://apis.gooogle.identity-log.com/js/base.js”. error in browser console

**Comment by elktarni** [comment]
hey @maisonmargiela0 
please contact me at contac@elktarni.com

**Comment by littlephild** [comment]
@ewhitman1 did you managed to finish google phishlet. kindly share. I am a beginner and the documentation for creating the phishlet is not suitable for beginners.

**Comment by lucidpsimc** [comment]
@ewhitman1 tried your txt file and get hung up on my dev terminal with a 
`WARN: Cannot handshake client ssl.gstatic.com EOF`
On my test device it will show me a login page but all links are dead. Any suggestions?

**Comment by stackerofwheat** [comment]
> @kgretzky Hi, able to remove timed out issue from google but after tapping yes on my device and matching the number shown , I am unable to submit it

@ewhitman1 were you able to fix this? i'm using your google1.yaml file and have same issue. Google sends prompt to phone but when I tap the number on the screen it doesn't forward me to next page. Or sometimes I get a timeout error. Let me know if there is edit to phishlet which can fix this.

**Comment by WWWWSS** [comment]
I want to know, at the moment, the work of phishlets for google exists????

**Comment by nileshpawar0212** [comment]
[10:09:25] [err] failed to load phishlet 'google.yaml': missing `login` section

getting this error

**Comment by alirezadanali** [comment]
> The request timed out error happens due to Google's security protection hidden in obfuscated JS code. Only happens for push notifications.

i know its an old message, but i want to know if you have successfully bypassed this then at least i know its doable, looking at it for a while all i could is stop the error. it wont submit

**Comment by anoldluna** [comment]
@kgretzky  why does the cookies sessions expire too quickly ? not even up to 30 minute, it you dont use the cookies asap it will expire and wont be able to use it
