### ISSUE TITLE
 Do you have dynamic hot loading the yaml Configuration file

### ISSUE THREAD

**Issue by vsyour** [kgretzky/evilginx2#184]
Hi kgretzky,

First:Excellent project!!
second my request.:
Is there a way to dynamically hot loading the  yaml configuration file?
Now you need to restart the main program of evilginx2 once you change the  yaml configuration file.

Thanks for your help!

**Comment by kgretzky** [comment]
Hey @vsyour !

Yes, this is a great suggestion. I plan to add it in one of the future minor updates. I know how annoying it is when developing phishlets at the moment.
