### ISSUE TITLE
Redirection after tokens intercepted is not working on version 2.3

### ISSUE THREAD

**Issue by SamantasFOxy** [kgretzky/evilginx2#186]
hello,
after the tokens intercepted and the auth url is reached the redirection don't work.
Anybody have this problem?

[07:23:51] [+++] [0] detected authorisation URL - tokens intercepted: /profile
[07:23:55] [imp] [0] redirecting to URL: https://google.com (1)

Even i have this ([07:23:55] [imp] [0] redirecting to URL: https://google.com (1)) on debug screen it is not working. User remain on proxy server ,don't redirect to google for example.
The same  phishlet on 2.2 version working fine. On 2.3 it is not working
"Try not to set the redirect URL to the URL of the website you are running phishing on. It will constantly try to replace the original URL with the phishing one, creating an infinite loop.
This will be fixed in Evilginx 2.3, making the redirect trigger only once." 
This is not a solution. The redirect is not the same site and there is no infinite loop.
Like i said on the the 2.2 version on Evilginx is working fine but on 2.3 is not. Capture user name ,password ,tokens but user remain on the proxy site don't redirect. Any suggestion ? Anybody ?

**Comment by maisonmargiela0** [comment]
> 
> 
> hello,
> after the tokens intercepted and the auth url is reached the redirection don't work.
> Anybody have this problem?
> 
> [07:23:51] [+++] [0] detected authorisation URL - tokens intercepted: /profile
> [07:23:55] [imp] [0] redirecting to URL: https://google.com (1)
> 
> Even i have this ([07:23:55] [imp] [0] redirecting to URL: https://google.com (1)) on debug screen it is not working. User remain on proxy server ,don't redirect to google for example.
> The same phishlet on 2.2 version working fine. On 2.3 it is not working
> "Try not to set the redirect URL to the URL of the website you are running phishing on. It will constantly try to replace the original URL with the phishing one, creating an infinite loop.
> This will be fixed in Evilginx 2.3, making the redirect trigger only once."
> This is not a solution. The redirect is not the same site and there is no infinite loop.
> Like i said on the the 2.2 version on Evilginx is working fine but on 2.3 is not. Capture user name ,password ,tokens but user remain on the proxy site don't redirect. Any suggestion ? Anybody ?

HEllo!! I have the same problem and also this Warn: : 2019/01/28 10:44:33 [235] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
2019/01/28 10:44:33 [234] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
2019/01/28 10:44:33 [236] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
2019/01/28 10:44:34 [237] WARN: Cannot handshake client www.amazon.com EOF
2019/01/28 10:44:34 [240] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF

Did you solved something?

Thank you!!

**Comment by SamantasFOxy** [comment]
> 

> > hello,
> > after the tokens intercepted and the auth url is reached the redirection don't work.
> > Anybody have this problem?
> > [07:23:51] [+++] [0] detected authorisation URL - tokens intercepted: /profile
> > [07:23:55] [imp] [0] redirecting to URL: https://google.com (1)
> > Even i have this ([07:23:55] [imp] [0] redirecting to URL: https://google.com (1)) on debug screen it is not working. User remain on proxy server ,don't redirect to google for example.
> > The same phishlet on 2.2 version working fine. On 2.3 it is not working
> > "Try not to set the redirect URL to the URL of the website you are running phishing on. It will constantly try to replace the original URL with the phishing one, creating an infinite loop.
> > This will be fixed in Evilginx 2.3, making the redirect trigger only once."
> > This is not a solution. The redirect is not the same site and there is no infinite loop.
> > Like i said on the the 2.2 version on Evilginx is working fine but on 2.3 is not. Capture user name ,password ,tokens but user remain on the proxy site don't redirect. Any suggestion ? Anybody ?
> 
> HEllo!! I have the same problem and also this Warn: : 2019/01/28 10:44:33 [235] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
> 2019/01/28 10:44:33 [234] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
> 2019/01/28 10:44:33 [236] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
> 2019/01/28 10:44:34 [237] WARN: Cannot handshake client [www.amazon.com](http://www.amazon.com) EOF
> 2019/01/28 10:44:34 [240] WARN: Cannot handshake client images-na.ssl-images-amazon.com EOF
> 
> Did you solved something?
> 
> Thank you!!

Nope . I use the version 2.2 as a temporary solution. you have ICQ?

**Comment by maisonmargiela0** [comment]
No. I don't have Please write me here maisonmargiela0@gmx.fr

Thx

**Comment by kgretzky** [comment]
@SamantasFOxy which phishlet? Amazon phishlet was known to have issues with redirect.

**Comment by SamantasFOxy** [comment]
Thanks for your response. It is not Amazon. It is another phishlet made my me.
 Even i use Amazon (modified by me) on 2.2 is working perfectly but on 2.3 is not (don't do redirect ).
If my judgement is right then is the phishlet is working on 2.2 and on the 2.3 is not where is the problem on 2.3? 
Only thing i did was to modify the 2.2 phishlet to 2.3 version (landing page modify , and login add).
Can you please give me some suggestions? 
There is no connection loop for sure......



> @SamantasFOxy which phishlet? Amazon phishlet was known to have issues with redirect.

**Comment by SamantasFOxy** [comment]
sorry i closed by mistake.......

**Comment by SamantasFOxy** [comment]
@kgretzky you have any suggestion for this issue?

**Comment by kgretzky** [comment]
Amazon phishlet is not tested and its author is not updating it. Please submit PR when you manage to fix it. Closing for now.
