### ISSUE TITLE
lures redirect url does not work

### ISSUE THREAD

**Issue by maisonmargiela0** [kgretzky/evilginx2#187]
HELLO!!

lures redirect url does not work. It remains on the "fake" URL after the credentials token.

I think it is a evilginx2 error.
Please help!

Thx,

**Comment by kgretzky** [comment]
You probably used a redirect URL that you are proxying so it was correctly replaced with a phishing URL.

**Comment by SamGurdus1** [comment]
How do you setup a redirect using lures?

**Comment by kgretzky** [comment]
`help lures`

**Comment by curiousm3** [comment]
lures edit redirect_url <id> <redirect_url>

**Comment by SamGurdus1** [comment]
I tried redirecting to https://reddit.com, but after the username and pass were inputted, it just gave me an error and said incorrect username/password. I checked the lure, and it had changed the redirect url.

**Comment by maisonmargiela0** [comment]
> 
> 
> You probably used a redirect URL that you are proxying so it was correctly replaced with a phishing URL.

Hi kgretzky,

I don't understand what do you mean by this. Does not work for me. I tried with amazon.com and google.com
THe redirect does not work!

THank you for your efftor!!

**Comment by kgretzky** [comment]
You did not provide enough information. Please send more details or I will need to close.
Believe me, if redirection didn't work, I'd notice and fix it.

**Comment by maisonmargiela0** [comment]
What more ifnormation do you need Kretzy? it does not redirect version 2.3
but on evilginx 2.2 it is working.
I don't know where is the problem because I am not a developer.
Thank you for your effort!

**Comment by pielgrzym** [comment]
Some sites heavy on redirects from oauth/saml don't work with lure redirect. Basically after capturing auth tokens is complete proper message is displayed in evilginx console (for example: `[11:31:42] [imp] [0] redirecting to URL: https://reddit.com (1)`) but the redirect does not happen on the site itself - haven't got time to debug this fully but I suspect some single page apps can just ignore some responses and keep on rolling (outlook UI - I'm staring at you!). It's worth experimenting with js injection in this scenario.

**Comment by pielgrzym** [comment]
Here is an ugly-ass workaround if you haven't  got time to debug some clientside js etc.
You have to define a custom lure paramerer: `lures edit 0 params rurl=http://reddit.com` and this js will be triggered 2s after the login page loads (remember to adjust trigger rules to match the final page). The wait helps if cookie setting is delayed and prevents evilginx from missing a token :)

```
js_inject:
  - trigger_domains: ["www.victim-site.com"]
    trigger_paths: ["/yay-i-managed-to-login"]
    script: |
            function gimmesleep(ms) {
              return new Promise(resolve => setTimeout(resolve, ms));
            }
            async function redir() {
              await gimmesleep(2000);
              window.location.href = "{rurl}";
            }
            redir()

**Comment by maisonmargiela0** [comment]
Hello Jakub,

I don't understand how to do it. It does not work this command lures edit 0
params rurl=http://reddit.com
Sorry but I am noobie:(

Thx,

**Comment by maisonmargiela0** [comment]
The redirect is wroking fine now.. GOOD JOB

Can anybody help me with a phishlet? I made everything for amazon.it phishlet but does not take cookies.

Thx

**Comment by maisonmargiela0** [comment]
Hi,

Did you used js injected javascript that pre-fills the target's email on
amazon phishlet?
I tried to use it but it does not work for me. Can you please help me?

Thx,

**Comment by narcotic401** [comment]
js injected javascript that pre-fills  not works for gmail too! if anyone found anything help me

**Comment by DSUN01** [comment]
i did this 
lures edit redirect_url <1> <https://login.live.com>
and i got this 
[err] lures: edit: strconv.Atoi: parsing "<1>": invalid syntax
what may be the problem

**Comment by xpsmile** [comment]
> The redirect is wroking fine now.. GOOD JOB
> 
> Can anybody help me with a phishlet? I made everything for amazon.it phishlet but does not take cookies.
> 
> Thx

How did you do it? I’m having the same issue

**Comment by kpomeroy1979** [comment]
> You did not provide enough information. Please send more details or I will need to close. Believe me, if redirection didn't work, I'd notice and fix it.

That would be nice if this was true. The redirect_url in the lure does not work. Something is broken after chanting the redirect code from 302 to JavaScript
