### ISSUE TITLE
Evilginx behind an nginx proxy

### ISSUE THREAD

**Issue by tomruk** [kgretzky/evilginx2#188]
I would like to run evilginx behind an nginx proxy but i couldn't find a way to do it. Evilginx listens on port 443, is there an option to change that?

I have a server which has stunnel, sslh, nginx configured.
Here is the configuration of these services:

stunnel (listens on external ip, port 443) -> sslh (listens on 127.0.0.1:3000 and redirects http requests to nginx on 127.0.0.1:4000, if the packet is an ssh, it redirect the packet to port 22) -> nginx

Also nginx redirects specific http requests to 127.0.0.1:5000 which is metasploit that runs to receive connections.
I would like to run evilginx on port 6000 and redirect specific requests such as /login to 127.0.0.1:6000

Is there a way to do that?

**Comment by SamantasFOxy** [comment]
search on google for that. this is not the evilginx problem
