### ISSUE TITLE
 Timeout during connect (likely firewall problem)

### ISSUE THREAD

**Issue by moekugd** [kgretzky/evilginx2#189]
Hello i tried to use evilginx2 with freenom domain but i get always this error " Timeout during connect (likely firewall problem)
" i tried and with other hosts same thing :( any solutions how to fix
im using azure microsoft server
is there any solution
is the fault of my server or domain?

**Comment by moekugd** [comment]
Hello i tried to use evilginx2 with freenom domain but i get always this error " Timeout during connect (likely firewall problem)
" i tried and with other hosts same thing :( any solutions how to fix

**Comment by moekugd** [comment]
im using azure microsoft server
is there any solution
is the fault of my server or domain?

**Comment by kgretzky** [comment]
Register a real domain on namecheap and point the nameservers to your VPS IP. It doesn't work probably because you are using free domains through freenom nameservers.

**Comment by moekugd** [comment]
u sure its fault of domain?

**Comment by SamantasFOxy** [comment]
the domain was the problem ?

**Comment by kgretzky** [comment]
The problem is freenom and the fact that you didn't set your VPS to be the domain's nameserver.

**Comment by moekugd** [comment]
i actually setted with set hostname-ctl mydomain.tk

**Comment by curiousm3** [comment]
I've used freenom and it works , maybe you forgot to point the domain name to your vps ip?

**Comment by jeretc** [comment]
Make sure port 80 is not blocked by your service provider. Once you get that fixed, you should be able to generate the cert.

**Comment by kgretzky** [comment]
FAQ https://github.com/kgretzky/evilginx2/wiki/FAQ
