### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by ewhitman1** [kgretzky/evilginx2#190]
how to bypass apis.google.com & content.googleapis.com ? @kgretzky

**Comment by kgretzky** [comment]
What is this question even about?

**Comment by ewhitman1** [comment]
@kgretzky about google phishlet...
getting stuck in bypassing above said url

**Comment by jesse234** [comment]
really ?????? that must be evilginx v15.1

**Comment by kgretzky** [comment]
What do you want to bypass? I don't understand.
