### ISSUE TITLE
Question regarding input id

### ISSUE THREAD

**Issue by ewhitman1** [kgretzky/evilginx2#191]
Hi @kgretzky ,
Can we use input#id in credentials --> username --> key , for those input fields where input name ain't given and only input#id is given?

**Comment by ewhitman1** [comment]
@kgretzky when submitting the data in apple phishlet error code returns 404 and request url it shows is https://idmsa.domain.com/appleauthhttps://idmsa.domain.com/auth , which shoud be https://idmsa.domain.com/appleauth/auth

**Comment by kgretzky** [comment]
You are asking for help in developing the phishlet, which is out of scope, since I don't have the answers you seek.
