### ISSUE TITLE
Using lures?

### ISSUE THREAD

**Issue by SamGurdus1** [kgretzky/evilginx2#192]
I am following a tutorial on setting up evilginx2, but it uses the old phishlets get-url method. What would be the equivalent using lures of "phishlets get-url reddit https://reddit.com/"?

**Comment by ewhitman1** [comment]
lures get-url <lures_id>

**Comment by ewhitman1** [comment]
for lures usage you can use command: help lures

also you can visit: https://breakdev.org/evilginx-2-3-phishermans-dream/

**Comment by SamGurdus1** [comment]
@ewhitman1 What is the lures_id?

**Comment by ewhitman1** [comment]
you need to create lures id for each phishlet
lures create <phishlet name>

**Comment by SamGurdus1** [comment]
@ewhitman1 Thanks, that worked. Is there any way to specify the redirect like with the old command?

**Comment by clhefton** [comment]
@SamGurdus1 `lures edit redirect_url <id> <redirect_url>`. To find the ID of your lure just type `lures`. `help lures` is your friend, although I thank @ewhitman1 for the link, which I never would have found since it's not in the README or wiki. Incidentally, the `get-url` command is also not in the `help lures` output, only in the blog post, but that seems to be the only one missing from help (see core/terminal.go)

**Comment by jepunband** [comment]
hi need some help please .. after getting the lures, lures get-url 0 .. the address (URL) generated not displaying any page on browser .. not sure if i have done this correctly?
![lures](https://user-images.githubusercontent.com/46950575/52642207-81cc9d80-2f15-11e9-80ed-e03d06ebbd1f.png)

**Comment by kgretzky** [comment]
Please make sure your DNS and nameserver settings are set up correctly. Not enough information.

**Comment by jepunband** [comment]
hi got this to work after editing the etc/hosts file. Web page can now be displayed.. but website/phishlet twitter not displaying correctly like it should.

**Comment by pushkar31** [comment]
Hi,
Anyone worked on changing the landing page for 5 seconds and then the main phishlet URL to open.
My phishlet is working fine, but now I want to load two custom images first and then the actual URL.
