### ISSUE TITLE
evilginx2 only as a mirror

### ISSUE THREAD

**Issue by h3xp1017** [kgretzky/evilginx2#194]
is it possible to run evilginx2 only as a mirror? without intercepting passwords but with manual code injection? do i still need to write a phishlet for this? how to do this?

**Comment by kgretzky** [comment]
Sorry, I don't quite understand the question.

**Comment by h3xp1017** [comment]
I want to use evilginx only as a proxy but with inserting my own js code into proxified pages. Is it possible?

**Comment by kgretzky** [comment]
You can use the `js_inject` parameter introduced with version 2.3.0.
