### ISSUE TITLE
isp blocks port 80 

### ISSUE THREAD

**Issue by jesse234** [kgretzky/evilginx2#195]
please i have tried to get a signed cert from lets encrypt but my isp blocks port 80 , please is there a way i can work around this issue ? 
[twitter.com.login-reply.cf] acme: Error 400 - urn:acme:error:connection - Fetching http://twitter.com.login-reply.cf/.well-known/acme-challenge/6ZiriupqyPa2fUj4HAzClYCQqiTY2_OE-4B9XCvd7LY: Timeout during connect (likely firewall problem)

and can i use a manually signed cert using certbot dns-01 ?

**Comment by kgretzky** [comment]
Use Namecheap and not Freenom and you should be good.
