### ISSUE TITLE
evilginx2 blocks iframes

### ISSUE THREAD

**Issue by SamGurdus1** [kgretzky/evilginx2#196]
I would like to mask the domain of my phishing site by creating an iframe under my nice short domain, of my evilginx page, but it seems to be blocking showing up inside iframes. I would like to be able to create an iframe of my evilginx2 page. Is this something I can change/is this a setting that can be edited?

**Comment by kgretzky** [comment]
Usually websites prevent from being loaded in iframes. Doubt it is an issue with evilginx.

**Comment by SamGurdus1** [comment]
Looks like this can be changed with the X-Frame-Options header in a regular website. I'm not sure how to change this in evilginx though.
