### ISSUE TITLE
facebook password problem

### ISSUE THREAD

**Issue by bojanrodic** [kgretzky/evilginx2#197]
Hello, i test it under few accounts of me and my friends
all captures session without problem
but only one saves real password
others have false in password field.
First it shows password than after it grabs token than it just keeps false.
i can post photo as proof if needed.
same happends on instagram

**Comment by kgretzky** [comment]
Could be a bug in a phishlet, but that is unlikely to be fixed by me. If anyone can send a PR with a fix, I will merge it.
