### ISSUE TITLE
Unable to configure DNS

### ISSUE THREAD

**Issue by juouy** [kgretzky/evilginx2#202]
Hi,

This is my first try on evilginx2 and i'm having some problems.

My server -> 1.1.1.1
My domain -> testdomain.com

1. I bought the domain and went to namecheap panel. I added custom ns1 and ns2 records like this, pointing to 1.1.1.1

https://i.imgur.com/IkrFlVo.png

2. I set custom dns servers to ns1.testdomain.com and ns2.testdomain.com for the domain.

https://i.imgur.com/M8VYOTb.png

3. I have verified by using "WHOIS" that the new nameservers are updated. They point now to ns1.testdomain.com and ns2.testdomain.com

4. I make sure no ports are running on 53/80/443 and run evilginx. I set domain in config to testdomain.com and ip to 1.1.1.1. 

5. I enable linkedin phishlets set custom host - linkedin.testdomain.com  and use lure to generate URL.

6. The domain does not load.

I assume that local DNS handler of evilginx should resolve the domain testdomain.com, correct?
Because when i try to resolve that domain using "dig" utility it does not provide any answers:

https://i.imgur.com/GNfhWdn.png

Am i forgetting about something or doing something wrong?

I'm using -developer and -debug flags

**Comment by kgretzky** [comment]
Hey. Why did you set nameservers to `1.1.1.1`?
You should set the nameservers IP to where you have Evilginx installed on external server.

**Comment by jeretc** [comment]
point the nameserver to your IP address. Example, let's say your IP address is 139.130.4.5

ns1.testdomain.com = 39.130.4.5
ns2.testdomain.com = 39.130.4.5

![ns](https://user-images.githubusercontent.com/20941239/52697153-cdca2180-2fab-11e9-8c85-cb32bc27cdee.png)

**Comment by kgretzky** [comment]
Did you enable the phishlet that you want to use? `phishlets enable <phishlet>`

**Comment by juouy** [comment]
> Hey. Why did you set nameservers to `1.1.1.1`?
> You should set the nameservers IP to where you have Evilginx installed on external server.

Of course this is just the example. 
I realized that the problem was issued to the fact that i have to access the domain using subdomain defined in phishlet file.

instead of twitter.mydomain.com like login.twitter.mydomain.com

**Comment by jelledesnelle** [comment]
@juouy could i get in contact with u?

**Comment by firestarter2021** [comment]
hello 
I bought a domain name from namecheap and a droplet from digitalocean. I pointed the nameservers ns1.digitalocean.com  and ns2.digitalocean.com to my domain name. Apparently, everything worked quite well. Then, I launched evilginx2. it keeps telling "Failed to start nameserver on port 53". I run some code on the terminal to stop port 53. It did actually stop. Now, everytime i want to start a phishlet, evilginx tell me that there is an acme error DNS problem and all that.... eventually, I carry on creating the lures aand when I get the url and try it on my web browser it simply does not connect. Nothing comes up. What is the problem??? I don't know.....
Please, tell me what should I do to make evilginxs run properly.

**Comment by srand2** [comment]
@firestarter2021 did you ever resolve this issue? Im running into the same problem @kgretzky 

  `  "Failed to start nameserver on port 53"  `

**Comment by firestarter2021** [comment]
No. I did not resolve the problem. Still the same problem. Acme problem.

**Comment by srand2** [comment]
perhaps this will help https://miloserdov.org/?p=4225 @firestarter2021

**Comment by bl1lnk** [comment]
cme: Error -> One or more domains had a problem:
[m.www.example.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for m.www.example.xyz - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for m.www.example.xyz - check that a DNS record exists for this domain, url:
[www.www.example.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.www.example.xyz - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.www.example.xyz - check that a DNS record exists for this domain, url:

i bough my domain and my vps on namecheap but i got this error  . in CUSTOM DNS  what should i choose ?
1) Namecheap basic DNS
2) NameCheap WebHosting DNS 
3) Custom DNS 

if custom dns what should i type there guys ?
