### ISSUE TITLE
certification (most likely firewall)

### ISSUE THREAD

**Issue by jepunband** [kgretzky/evilginx2#203]
hi, 

phishlets enable facebook  -  gives me the error below:

[static.facebook.com.testfb.ml] acme: Error 400 - urn:acme:error:connection - Fetching http://static.facebook.com.testfb.ml/.well-known/acme-challenge/KYW5m6iWDAuvpC_Pvqik5wHbHljO2oTNw0fY4nShXJQ: Timeout during connect (likely firewall problem)

Error Detail:
	Validation for m.facebook.com.testfb.ml:80
	Resolved to:
		218.x.x.x
	Used: 218.x.x.x

same for the : m.facebook.com.testfb.ml , static.facebook.com.testfb.ml, www.facebook.com.testfb.ml

--------

any ideas on how to solve this please?

**Comment by nonuser33** [comment]
I have the same problem and no one have an answer

**Comment by jepunband** [comment]
Hi the issue was port 80. Make sure port 80 is open. Some service provider blocks port 80.

**Comment by jeretc** [comment]
The issue is Port 80. Make sure your service provider has not blocked port 80. You can use an online site to check it like..

canyouseeme.org

**Comment by kgretzky** [comment]
FAQ https://github.com/kgretzky/evilginx2/wiki/FAQ

**Comment by tokiijnr** [comment]
Error: I could not see your service on 197.210.54.142 on port (80)
Reason: Connection timed out


yes port 80 is blocked on mine what do i do?
