### ISSUE TITLE
Failed to obtain certificates

### ISSUE THREAD

**Issue by Aditrix** [kgretzky/evilginx2#206]
Hi, i had get this error failed to obtain certificates
mondomaine.ga is running 
but i have this errror : 
[https://imgur.com/a/ossTb0v](url)

**Comment by forsatus** [comment]
You need to create a dns entry for 
m.insttagram.ddns.net
and for 
www.insttagram.ddns.net

**Comment by Aditrix** [comment]
I can't 
[https://imgur.com/a/8zbUOw1](url)

**Comment by Aditrix** [comment]
@kgretzki i think taht its because my domain IS directing to my router configuration page 
How Can i solve this ?

**Comment by kgretzky** [comment]
Check the blog to learn how to set up your nameservers. The whole setup is invalid.

**Comment by forsatus** [comment]
If your host is behind your routeur, write your demain on /etc/hosts
