### ISSUE TITLE
Phishlet Twitter not displaying correctly

### ISSUE THREAD

**Issue by jepunband** [kgretzky/evilginx2#208]
hello,
Phishlet twitter not displaying correctly .. 
![twitter](https://user-images.githubusercontent.com/46950575/52648406-72535180-2f21-11e9-90a4-9ffda0fc7b5e.png)

**Comment by kgretzky** [comment]
Check web inspector in your browser. Clearly it is only able to load the main domain and cannot access any subdomains.

**Comment by jepunband** [comment]
that is because  

twitter.com
api.twitter.com
abs.twitter.com << -- does not exists.

i got the above info from doing phishlets get hostname twitter
