### ISSUE TITLE
got the SLL certificate but website is offline

### ISSUE THREAD

**Issue by vendom2k** [kgretzky/evilginx2#209]
i set up everything and i got the SLL certificate. but if i go to the link it doesn't work?? can anyone help me
![evilginx screen github](https://user-images.githubusercontent.com/47578609/52672017-db849600-2f1c-11e9-9501-f636b23db6bb.PNG)
![unbenannt](https://user-images.githubusercontent.com/47578609/52672027-e2130d80-2f1c-11e9-9d2b-5bea34ba884c.PNG)

**Comment by nonuser33** [comment]
How did you get the SSL certificate? I have an error when I try

**Comment by kgretzky** [comment]
FAQ https://github.com/kgretzky/evilginx2/wiki/FAQ
