### ISSUE TITLE
Phishlets

### ISSUE THREAD

**Issue by yahirlevine** [kgretzky/evilginx2#21]
I have play around with the phishlets. I have created few phishlets for few websites. Some are working with no error, some have an error.

1. The phishing url doesnt display anything.
2. The phising url just redirect to google.com without the login page.
3. The token are not saved, only username and password.
4. I cannot create a working phishlet for website who doesnt have a subdomain name.

**Comment by kgretzky** [comment]
1-3: Can't help you with that as the subject is to broad for me to have a simple answer. Analyze the existing phishlets and try to work it out.
4: This is a known bug, will be fixed. #10

**Comment by kunalbahl** [comment]
Where can i get google and yahoo phishlets ? Can anyone help ??
