### ISSUE TITLE
Pass URL parameters to the proxied site

### ISSUE THREAD

**Issue by 1trevor** [kgretzky/evilginx2#210]
I need to pass a particular query string as a URL parameter to the site I am proxying. I have tried adding parameters to the phishing url generated by get-url, but those aren't passed to the backend site. I don't see any way to add URL parameters to the phishlet.

Is there a way to accomplish this?

**Comment by kgretzky** [comment]
Did you try adding GET parameter to `login -> path` in your phishlet?
It should redirect to this specific login page URL and the GET parameters should be preserved.

**Comment by 1trevor** [comment]
Thanks. I added the parameters I need in the landing_path in the phishlet and that worked.
