### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by rent48bnb** [kgretzky/evilginx2#211]
I have a phishlets, but the tool captures only 2 keys of 17 keys, why? any help please

here is the keys 
['bev','jitney_client_session_updated_at','_csrf_token','jitney_client_session_id','jitney_client_session_created_at','_user_attributes','cereal_exp','_pt','_aat','abb_fa2','alfc','alfces','jlp3','rdu','rclmd','roles','_airbed_session_id']

![2keys](https://user-images.githubusercontent.com/44444786/52797664-00911a00-307f-11e9-8931-d4d12d85100b.JPG)

**Comment by kgretzky** [comment]
This is seriously not enough info to provide any help.
