### ISSUE TITLE
 recaptcha validation 

### ISSUE THREAD

**Issue by littlerfv56** [kgretzky/evilginx2#215]
Hello sir,

Please tick the box for «I am not a robot».

Is a solution or phishlets to bypass google recaptcha?

There is away to proxy the recaptcha validation ?

error : for the site owner: domain not valid for the site key

**Comment by jaredxx1** [comment]
I'm having the same issues: recaptcha & cloudflare.
Example website (both recaptcha & cloudflare) : www.webhostingtalk.com

**Comment by maisonmargiela0** [comment]
Hello Everybody! Did anyone solve this situation?? with Recaptcha. I am having the same problem with www.libero.it
