### ISSUE TITLE
Do sub_filters support replace on Http Headers?

### ISSUE THREAD

**Issue by juouy** [kgretzky/evilginx2#217]
I'm trying to rewrite phishlet.
However at one part of the process user receives a 302 redirect that is part of http header.

Can we use sub_filters to rewrite 302 response redirects or they only apply to response content?

**Comment by juouy** [comment]
Below is the example i'm struggling with:

I'm trying to create google phishlet, however based on the location the server where evilginx is hosted on. It redirects to google domain based on server geolocation, eg. google.co.uk while phishlet was created for google.com

Everything works almost perfectly except of single moment where user receives following 302 redirect response:

https://i.imgur.com/qr1MoRh.png

For some reason evilginx doesn't rewrite this url even though i have following subfilters defined:

```
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/accounts/', replace: 'https://{hostname}/accounts/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/accounts/', replace: 'https://{hostname}/accounts/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.co.uk', orig_sub: 'accounts', domain: 'google.co.uk', search: 'https://{hostname}/accounts/', replace: 'https://{hostname}/accounts/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.co.uk', orig_sub: 'accounts', domain: 'google.co.uk', search: 'https://accounts\.google\.co\.uk', replace: 'https://{hostname}/accounts/', mimes: ['text/html', 'application/json']}
```
Is there anything wrong with my sub_filters here?

**Comment by kgretzky** [comment]
The TLDs will vary between countries. You need to make sure Evilginx redirects user before google tries to redirect to one of the regional domains.

You may want to make sure to try out version `2.3.1`, just pull latest from master, as I added some fixes to how redirection happens after session is successfully captured.
