### ISSUE TITLE
Page not found after creating lure

### ISSUE THREAD

**Issue by schuesslerf** [kgretzky/evilginx2#222]
Hey,

I just got a new domain to test this out. 

I basically have my web server up running (Apache). 

This is just for testing purposes of course. Lets call the domain "mydomain.com".

What I tried now is the following commands:

```
config domain mydomain.com
config ip 123.456.789.123
phishlets hostname twitter mydomain.com
phishlets enable twitter
lures create twitter
lures get-url 0
```

All succeeded with no error, but when trying to visit the site, the page is not found, the normal base url mydomain.com is working though.

Am I missing something here?

**Comment by IonizeCbr** [comment]
yeah nowhere explains to set the target url and nowhere explains how to use lures

**Comment by schuesslerf** [comment]
I just shut down apache, please see my other issue (or link it) now, because I can't get a certificate from LetsEncrypt as it seems.

**Comment by schuesslerf** [comment]
Okay, problems solved, it works now, needed to add a few more dns records. You can close both issues.

**Comment by kgretzky** [comment]
Just a reminder, you can close issues you open yourself.
