### ISSUE TITLE
Wrong url 

### ISSUE THREAD

**Issue by florian74600** [kgretzky/evilginx2#225]
hello sorry i had a problem with the publication . 
my problem is quite simple but i can figure out the solution.

when i look at my lures , the phishlet and the redirect URL both says instagram in my case, but when i create a link, it says the domain i create and not the one of instagram... to be clear , the link looks like that "www.icecream.gq/bm..laTC" (i wont put the whole link) instead of "www.instagram.com/..."

any solution for that ? :/

**Comment by kgretzky** [comment]
Didn't I already reply to that in another issue? Why did you repost it?

**Comment by florian74600** [comment]
Because you don't help me .. you basically just tell me something very obvious and you close my post ... I'd appreciate a bit more help

**Comment by kgretzky** [comment]
> the link looks like that "www.icecream.gq/bm..laTC" (i wont put the whole link) instead of "www.instagram.com/..."

The issue is very obvious for me. There is no way the phishing link will contain the original `www.instagram.com` domain, unless I didn't understand what you meant.

**Comment by florian74600** [comment]
I might explain wrong but when I saw some other project like that , theh basically have their website target URL before their domain so basically I think it looks like that for exemple : www.instagram.com.icecream.gq but I'm not sure .. when they write get-lurs or get-url they have a link that pops up with their website target and not their domain .. I'm not sure if I'm clear
