### ISSUE TITLE
Created phishlets 

### ISSUE THREAD

**Issue by mac4533** [kgretzky/evilginx2#226]
I created a new phishlets and It works perfectly over my laptop however when I try the link on my phone it states “ warn: cannot handshake client over ssl.gastatic.com eof and also cannot read TLS request from mitm’d client

**Comment by kgretzky** [comment]
I'm very sorry to hear this.

**Comment by bojanrodic** [comment]
@mac4533 can you leave your email?

**Comment by ArunDinfinity** [comment]
It's just u didn't use the mobile version of the webpage for desktop for example t will start with www.instagram
But for mobile it will start With m.instagram
