### ISSUE TITLE
FQDN not working, Name servers, inaccessible.

### ISSUE THREAD

**Issue by kaigouthro** [kgretzky/evilginx2#227]
For some reason, i can't get my domain provider to use ns1.DOMAIN.com

there is no other way to get my domain to load?

login.DOMAIN.com/*  works... anything subdomain.DOMAIN.com/* works.

but DOMAIN.com doesn't load anything.

this is an issue.

why is there no9 setting to default accept the FQDN and forward it to a sub-domain?

**Comment by kgretzky** [comment]
You broke my heart.
