### ISSUE TITLE
Javascript via src

### ISSUE THREAD

**Issue by Horders** [kgretzky/evilginx2#233]
Hello!
Is it possible to inject multiply javascripts to pages via src, instead of writing javascript code in phishlet js_inject.
And maybe there is possability to choose where to put it in landing page? For example before <body> and/or after </body>.
If it is not possible without you customazing the core, please say where i should to dig and search. 
Thank you.

**Comment by kgretzky** [comment]
Currently it is only possible to inject via `js_inject` in the phishlet as you saw.
For specifics please refer to the wiki: https://github.com/kgretzky/evilginx2/wiki/Phishlet-File-Format-(2.3.0)
