### ISSUE TITLE
Socks5 proxy not working with Evilginx

### ISSUE THREAD

**Issue by valexvictor** [kgretzky/evilginx2#235]
@kgretzky hey i have configured evilginx on my vps and i have applied socks proxy on my vps via proxychains so that every traffic pass through my socks5 proxy , But evilginx traffic is not passed through it. Does evilginx support Socks proxy. is it possible that end user can see as traffic come to him through my socks5 proxy rather than my server proxy . basically i want my server proxy to be hidden from end users.

**Comment by kgretzky** [comment]
Hey! It should be possible, but evilginx doesn't support socks proxy natively, so you need to figure it out yourself.
