### ISSUE TITLE
Lures url

### ISSUE THREAD

**Issue by jelledesnelle** [kgretzky/evilginx2#236]
Hello,
I am testing Evilginx2 on my localhost. My config domain is phishing-domain.com
But here is my problem: If i create a new lure for as example okta it says okta.phishing-domain.com

I just want only phishing-domain.com, instagram works fine but okta and many other phishlets the url starts with root domain name such as okta. I dont know why?

Kind regards,

**Comment by bedilbek** [comment]
You have to create one subdomain for each phishlet, because your **phishing-domain.com** identifies your main domain for all other phishlets, I think it is not correct to assign main domain to any phishlet

**Comment by jelledesnelle** [comment]
On localhost it does not matter i think. But instagram phishlets it is phishing-domain.com and for many other phishlets it is automaticly for example okta.phishing-domain.com

**Comment by jelledesnelle** [comment]
Got it
