### ISSUE TITLE
How to GZIP evilginx responses?

### ISSUE THREAD

**Issue by Horders** [kgretzky/evilginx2#239]
Hi, @kgretzky 
I need to gzip evilginx's response if response of original resourse is also gzip'ed.
Could you explain how to do it, please?
Otherwise it takes a lot of time to load content by browser because some files of original resourse a pretty big.

**Comment by kgretzky** [comment]
Actual proxying is handle by `goproxy` library, so this is out of scope of evilginx functionality at the moment.
