### ISSUE TITLE
Google phishlets

### ISSUE THREAD

**Issue by Jusote** [kgretzky/evilginx2#241]
could you do a Google phishlets for evilginx2?

**Comment by HackerTutor** [comment]
follow this guide https://www.youtube.com/watch?v=579OVkzaCTE&feature=youtu.be

This is not an issue and should be closed.

**Comment by Jusote** [comment]
Thank you for the link of the video but there are no phishlets in this video and I can not find anything about it on the internet. could someone write the code of a Google phishlets? thank you and sorry for the misspelling because I use a translator

**Comment by HackerTutor** [comment]
The video shows how to create phishlets. If you want someone to do programming for you, hire a programmer. This isn't the forum to ask for this.
