### ISSUE TITLE
Failed to obtain certificates (Error 400)

### ISSUE THREAD

**Issue by 9426** [kgretzky/evilginx2#243]
Hi guys!
I can't get the SSL/TLS certificates from LetsEncrypt.
I can ping from another machine the domain, I tried to disable my firewall, as I red in some other similar issues but I still couln't make it.
I got this error message:

[23:12:24] [err] [www.linkedin.com.france-fr.cf] acme: Error 400 - urn:acme:error:connection - Fetching http://www.linkedin.com.france-fr.cf/.well-known/acme-challenge/ogR_qkzDwwGDEb35YVz6Pp-PKtInhoIIFUJ0rlUC3tA: Timeout during connect (likely firewall problem)
Error Detail:
	Validation for www.linkedin.com.france-fr.cf:80
	Resolved to:
		(my public IP)
	Used: (my public IP)

Thanks for your help! ^^

**Comment by Molowogan** [comment]
Im having the same issue.especially with Amazon,linkedin and. reddit.I only obtain certifates on facebook,twitter and instagram.Is their security getting better or what is happening?

**Comment by Molowogan** [comment]
Please someone should help ASAP.

**Comment by kgretzky** [comment]
Definitely noone "should". Refer to LetsEncrypt manuals - your issue is out of scope of this project.
