### ISSUE TITLE
Several issues on local testing

### ISSUE THREAD

**Issue by bedilbek** [kgretzky/evilginx2#244]
Firstly, thanks for providing amazing tool for penetration testing.

I have come up with several issues while testing google authorization on local environment with **-developer** and **-debug** options:

- You set explicitly XMLHttpRequest header **Access-Control-Allow-Origin** with value '*'. So browser always tells to fix when credentials mode is on
- I found interesting bug i guess, for some reason order of _phish_sub_ records in `.yaml`  matters for the parser. For example,  if first _phish_sub_ is **accounts.google.com** and last _phish_sub_ is **accounts.youtube.com**, redirection will not work to main subdomain **accounts.google.com**, but instead will redirect to **accounts.youtube.com**. Maybe i understood something incorrectly in docs, but it is happening to me.
- and for some other reason what is working in google-chrome not working on firefox, i don't know why some buttons are not being triggered on press in Firefox, however with same lure it is working in google-chrome, it happens on login page: **/signin/v2/identifier**, also it maybe my mistake, thus sorry if it is stupid question

Thanks for your time and consideration.

**Comment by kgretzky** [comment]
Hey @bedilbek !

Thanks for sharing your findings.

1. Can you elaborate exactly what is the browser's message to fix? What is the credentials mode exactly?
2. This will normally happen if you duplicate values of `phish_sub` in any entry. You can use something else than `accounts` for the second entry. I'd use just `phish_sub: 'youtube'` and it will work fine.
3. I haven't seen any similar issues, but I will check.

**Comment by bedilbek** [comment]
Thank you for your reply and help @kgretzky.

Now I understand that `phish_sub` values should be unique, because configuration was working unpredictably wrong)

Let me clarify my findings about the CORS issue:
Browser's error message was the following:
> The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Thank your for your time and consideration. I am looking forward for your response.
