### ISSUE TITLE
Outlook phishlet missing correct domain? (goproxy related "Cannot write TLS response body from mitm'd client")

### ISSUE THREAD

**Issue by HachimanSec** [kgretzky/evilginx2#248]
Hi, 

I just tried out the latest version (2.3.0) of evilginx2 and played with outlook and o365 phishlets. 

Strangely both fail, I assume because a domain is missing in the yaml (I am not really sure about this yet, as I just have to work my head around the config files).

When I open a browser, I see the login and password screens just as expected. However when I click on the submit of the password, I receive an error from Microsoft:
<img width="525" alt="screen" src="https://user-images.githubusercontent.com/20123996/54721350-12744a00-4b62-11e9-8990-9faefc016c62.png">
```
request-id 7d3deb1f-d842-4d91-b45e-833d6510c12e
X-Auth-Error Microsoft.Exchange.Clients.Security.MSSPErrorException
X-OWA-Version 15.20.1709.16
X-FEServer AM0PR05CA0071
X-BEServer AM0P195MB0276
Date:20/03/2019 21:40:05
```

Any ideas if the yaml needs to be adjusted?

At the same time the console gives continuous TLS errors
2019/03/20 21:39:55 [121] WARN: Cannot handshake client outlook.live.com remote error: tls: unknown certificate
2019/03/20 21:39:55 [124] WARN: Cannot handshake client login.live.com remote error: tls: unknown certificate

**Comment by kgretzky** [comment]
Please try to use the latest 2.3.1 version from `master` branch and see if it fails the same way.

**Comment by HachimanSec** [comment]
Thanks Kuba. Will do so later today!

**Comment by HachimanSec** [comment]
PS: Maybe something to add. I am working on a Docker environment for training of some NGOs and journalists, combining Evilginx with GoPhish etc. 

Can this problem be somewhat related to a Dockerized environment?

**Comment by HachimanSec** [comment]
I got the latest version 2.3.1

The config is the following for O365 (TLS handshake errors still appear)
```
: lures edit redirect_url 0 https://www.office.com
[15:36:48] [inf] redirect_url = 'https://www.office.com'

: lures get-url 0

https://login.o365.my.<domain>.rocks/VAmKAUBZ

: lures 0

     phishlet : o365
         path : /VAmKAUBZ
 redirect_url : https://www.office.com
         info :
     og_title :
      og_desc :
     og_image :
       og_url :

: 2019/03/21 15:36:57 [057] WARN: Cannot handshake client login.microsoftonline.com remote error: tls: unknown certificate
2019/03/21 15:36:58 [060] WARN: Cannot handshake client www.office.com remote error: tls: unknown certificate
2019/03/21 15:37:02 [063] WARN: Cannot handshake client login.microsoftonline.com remote error: tls: unknown certificate
```
I receive the following error by MS (this also happens when I change the redirect_url to www.office365.com)
<img width="635" alt="Screenshot 2019-03-21 at 16 38 50" src="https://user-images.githubusercontent.com/20123996/54764317-d1c71000-4bf7-11e9-9f18-89f2c5cbcaff.png">

**Comment by HachimanSec** [comment]
I setup the outlook Phishlet with similar problems:

2019/03/21 15:48:31 [004] WARN: Cannot handshake client outlook.live.com remote error: tls: unknown certificate
2019/03/21 15:48:32 [006] WARN: Cannot write TLS response body from mitm'd client: write tcp 172.17.0.0:443-><MyIP>:53317: write: connection reset by peer

The config is:
```
phishlets hostname outlook outlook.my.<domain>.rocks
[15:44:39] [inf] phishlet 'outlook' hostname set to: outlook.my.<domain>.rocks
[15:44:39] [inf] disabled phishlet 'outlook'
: phishlets enable outlook
[15:44:39] [inf] enabled phishlet 'outlook'
[15:44:39] [inf] developer mode is on - will use self-signed SSL/TLS certificates for phishlet 'outlook'
:
: lures create outlook
[15:44:53] [inf] created lure with ID: 1
: lures 1

     phishlet : outlook
         path : /FuXQdMXb
 redirect_url :
         info :
     og_title :
      og_desc :
     og_image :
       og_url :

: lures get-url 1
https://outlook.outlook.my.<domain>.rocks/FuXQdMXb
```

**Comment by HachimanSec** [comment]
The screenshot for the error mentioned above
<img width="553" alt="Screenshot 2019-03-21 at 16 52 03" src="https://user-images.githubusercontent.com/20123996/54765363-a8a77f00-4bf9-11e9-8c99-6503e5bb72fb.png">

**Comment by HachimanSec** [comment]
Hi Kuba,

I just tried it on a local Kali box and there it works. These errors seem to be related to the container I have build. 
Pretty strange and quite unfortunate, as I would need to have multiple of them.

Any idea in which direction I can look to solve this? I am quite new to Docker unfortunately. 
Best
Tom

**Comment by kgretzky** [comment]
Wow. Thanks for all this information. I will try to look into it as it is indeed strange.
I've never experienced this behavior before.

**Comment by HachimanSec** [comment]
Sure, I try to learn something from this and make it, hopefully, a bit easier for you ;)
Let me know if there is something I can test. 

I also attach my modified Dockerfile FYI
```
FROM golang:alpine AS build

MAINTAINER HachimanSec

ENV SRC_DIR $GOPATH/src/github.com/kgretzky

RUN apk add --update ca-certificates && \
  apk add --no-cache --update git bash build-base && \
  rm -rf /var/cache/apk/*

WORKDIR $SRC_DIR

RUN git clone https://github.com/kgretzky/evilginx2 evilginx2

WORKDIR $SRC_DIR/evilginx2

RUN make

#final stage
FROM alpine AS prod

WORKDIR /app

COPY --from=build /go/src/github.com/kgretzky/evilginx2/phishlets ./phishlets/
COPY --from=build /go/src/github.com/kgretzky/evilginx2/bin .

RUN apk add ca-certificates

VOLUME ["/app/phishlets/"]

VOLUME ["/root/.evilginx/crt/"]

EXPOSE 443 80 53/udp

ENTRYPOINT ["/app/evilginx"]

```

**Comment by kgretzky** [comment]
I noticed this line:
```
[15:44:39] [inf] developer mode is on - will use self-signed SSL/TLS certificates for phishlet 'outlook'
```
Are you running Evilginx with developer flag? This will only use self-signed certificates which will result in TLS errors.

**Comment by HachimanSec** [comment]
Actually both. I tried it with developer and with the LetsEncrypt certs.

What I noticed is the difference in the missing line:
`2019/03/21 16:36:31 [041] WARN: Cannot handshake client outlook.live.com remote error: tls: unknown certificate
`
This one appears on the Docker version with --developer but not on my Kali box, also with --developer.

I assume the TLS errors originate exactly because of what you mentioned, the self signed certs. To verify this I will run it with LetsEncrypt again.

Any idea why there is the handshake error with unknown tls certificate?
I dont get why this fails. The docker container is capable of reaching the host outlook.live.com, as tested with curl. 
In kali the same compiled version of Evilginx2 works

**Comment by HachimanSec** [comment]
Hey @kgretzky 
I just tried it again with the "official" Letsencrypt certs. 
Just as you said, the TLS error is gone. 

However the redirect error still exists. Interestingly enough, the login page for the username and the second page for the password works. Username and password is captured too. 

The third page is then broken. 

I tried it with two different users, one with OTP enable and one without.
In both cases the behaviour is the same, the first two pages work and third one breaks. Whether the third page is supposed to be the OTP page or the final inbox page. 

<img width="535" alt="Screenshot 2019-03-23 at 15 40 29" src="https://user-images.githubusercontent.com/20123996/54867592-0ebf0e00-4d82-11e9-90a6-ae21df98b762.png">

**Comment by HachimanSec** [comment]
Hi @kgretzky 
a quick update. I rebuild the whole docker image with the default settings from GitHub. Unfortunately no change. 

Something I noticed during testing, and maybe that's helpful. 
Before the error page, I see a the username a second time. Seems kinda strange to me. Could this be a rerouting issue or something?
```
21:19:52] [imp] [0] [outlook] new visitor has arrived: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15 (217.22.143.24)
[21:19:52] [inf] [0] [outlook] landing URL: https://outlook.ms.my.phishing.rocks/verify
[21:20:08] [+++] [0] Username: [victim@outlook.com]
[21:20:08] [+++] [0] Password: [PASSWORD]
[21:20:08] [+++] [0] Username: [victim@outlook.com]
```

**Comment by kgretzky** [comment]
I haven't updated the outlook phishlet for several months now and it is very possible that they did some additional security checks.
It looks that they have finally added the detection of malicious `window.location` value, which is currently the only way to secure the website against mitm proxying.

If you see the error message printed from the web server, it means the certificate works.

**Comment by HachimanSec** [comment]
I just checked it on my local Kali Linux box. It totally works fine there. 
This is truly strange. 

Local evilginx2 (2.3.1) - works
Docker evilginx (2.3.1) - OTP screen breaks

This is super strange. What would make evilginx break running inside a container. 
Any idea where I could start debugging?

**Comment by HachimanSec** [comment]
@kgretzky I think I found the problem (even though I am not able to explain it).

I used a DigitalOcean droplet for my tests. To analyse further, I installed evilginx 2.3.1 directly onto the droplet (no docker). 
There it displays the very same error page. Hence I conclude that the error is neither related to evilginx nor to docker, but to the way DO droplets work. Even though I totally have no idea what issue that could be...

**Comment by StratoMusic** [comment]
So were you able to fix this and how? I have only tested with setup in server from onecloud, experiencing the same issue...

**Comment by StratoMusic** [comment]
@HachimanSec   any help with this man? i am still facing this issue, in my local kali and hosting in one cloud.

Please let me know how you fixed

**Comment by Yulia1991lab** [comment]
Hi @HachimanSec,

Can you please share your email address?, badly need a little help with outlook yaml.

Thanks

**Comment by wilsonfisk77** [comment]
Hello,

Any update on this outlook issue ?
i have been facing the same issue for a long time as described by @HachimanSec 

Thanks

**Comment by TeddyBlue** [comment]
anybody made headway on this?
