### ISSUE TITLE
Domains Other than the base domains are not being proxied. 

### ISSUE THREAD

**Issue by hash3liZer** [kgretzky/evilginx2#258]
I built a phishlet for google and unfortunately it didn't work. So, i went through each independent request by setting up a proxy in place and to my surprise, some hosts which should be proxied as have specified in the phishlet were not proxied and they ended up in generating some errors. My question is why for example, if i want to redirect url to domain `google.com`, then why if specify another host `gstatic.com` in `proxy_hosts` section, it would not redirect. While it should be something like `ssl.gstatic.com.fakedomain.com` when it was `ssl.gstatic.com` which is real. How do i solve this. This is really a problem. 

Or even better if you can guide me how to cancel a request.

**Comment by lofthotel** [comment]
Please add for talk
salamalecu@jabber.ru

**Comment by kgretzky** [comment]
Set up separate subdomain under the phishing domain that will map to the other real domain.
