### ISSUE TITLE
Outlook / o365 Error

### ISSUE THREAD

**Issue by rundmc99** [kgretzky/evilginx2#259]
Previously we had the outlook and o365 phishlets working properly, however we came back after a week or so and encountered the following issues:

- For outlook, once we get to the Microsoft login page and attempt to sign-in we get an immediate error: "There was an issue looking up your account. Tap Next to try again."
- For o365, the error screen attached appears on the next page. "We're unable to complete your request."

![Screenshot_2019-04-04_13-59-31](https://user-images.githubusercontent.com/49263678/55562723-1668a600-56e4-11e9-8e1d-bf576cccb130.png)

We made no changes from when we had it working previously. Any help would be appreciated.

**Comment by thehappydinoa** [comment]
I am having the same issue.

**Comment by xviiixxix** [comment]
I have this same issue

**Comment by kgretzky** [comment]
Phishlets require constant updates. If you figure it out, please submit a PR.

**Comment by thehappydinoa** [comment]
I will see what I can do.

**Comment by thehappydinoa** [comment]
Also @JamesCullum do you have any ideas or time to chat?

**Comment by JamesCullum** [comment]
@thehappydinoa At what step do you receive this error?
Do you have a phishlet URL to try it out?

**Comment by thehappydinoa** [comment]
@JamesCullum can I DM you the url?

**Comment by JamesCullum** [comment]
@thehappydinoa Send me the URL via email to nicolas.giese@web.de - if needed we can use that for all other communications.

**Comment by JamesCullum** [comment]
@kgretzky So my two test accounts still work fine. @thehappydinoa had the issue that he entered non-existant email accounts, which will create errors on O365 anyways, as the associated company configuration can't be retrieved.

Unless anyone has a working lure and demo username/password, it is impossible for me to debug this.

@rundmc99 Can you check if your issue is similar to the one from @thehappydinoa ? If not, could you provide me with the needed details?

**Comment by thehappydinoa** [comment]
Ah, so my issue was testing with an Outlook email rather than an Office 365 email. Apologies for any confusion.

**Comment by thehappydinoa** [comment]
@rundmc99 I think this issue has been solved.

**Comment by frdaz** [comment]
Work fine with ADFS, but i'v warn when i identify to idp, "cannot handshake client **domain.com** remote error: tls: unknow certificate"

anyone have got this ?

**Comment by StratoMusic** [comment]
How did you guys solved this?

I am getting this same error in o365

and this other https://github.com/kgretzky/evilginx2/issues/248 in outlook

@thehappydinoa
