### ISSUE TITLE
Evilginx with serverless tech??

### ISSUE THREAD

**Issue by uviman** [kgretzky/evilginx2#262]
Is it possible to use evilginx with serverless ?

**Comment by kgretzky** [comment]
What?

**Comment by JamesCullum** [comment]
Serverless is not actually serverless, it's just a managed server stack. It depends on that stack if you can run it.

Take a look at this for a similar setup. Every stack that can run binaries should work: https://serverless.com/blog/framework-example-golang-lambda-support/

**Comment by kgretzky** [comment]
@JamesCullum Thanks for clarification! My bad, didn't know that :)

Closing since I think the answer was provided.
