### ISSUE TITLE
Blockchain phishlet

### ISSUE THREAD

**Issue by mincemeatstrike** [kgretzky/evilginx2#263]
Can someone make a blockchain phishlet please i have tried to make it for about 4 hours, but i can't get it to work. I am willing to pay you for it!

**Comment by bojanrodic** [comment]
That is not issue.
Write to wishlist.

**Comment by oaredece** [comment]
icq 10777333

**Comment by kgretzky** [comment]
Is this a troll? :) Do you want some machine learning with that?

Before posting you should've read guidelines that this is not phishlet support service channel.
