### ISSUE TITLE
Evilginx2 enter in red spam very fast

### ISSUE THREAD

**Issue by lofthotel** [kgretzky/evilginx2#266]
I have a problem with evil.I don't know why enter very fast in spam (blacklisted my domain) I use domain from namecheap for phishilets gmail

**Comment by xviiixxix** [comment]
@lofthotel can you please provide me with gmail phishlets?

**Comment by lofthotel** [comment]
add salamalecu@jabber.ru for talk

**Comment by kgretzky** [comment]
I'm pretty sure Google figured out you want to break the law and they prevented you from doing so! Win!
