### ISSUE TITLE
get-url not working for me

### ISSUE THREAD

**Issue by xviiixxix** [kgretzky/evilginx2#267]
I get this warning when i try to get url..

: phishlets get-url outlook https://account.live.com
[22:01:01] [war] `get-url` is deprecated - please use `lures` with custom `path` instead

Someone should please help me out with this.

**Comment by thehappydinoa** [comment]
Try using `lures create linkedin` then `lures get-url <id>`.

**Comment by xviiixxix** [comment]
@thehappydinoa i'm new this, can you please type the command to use

**Comment by xviiixxix** [comment]
Someone should please help me with this as soon as possible.

**Comment by thehappydinoa** [comment]
First type: `lures create linkedin` then type `lures get-url 0`.

**Comment by xviiixxix** [comment]
Worked. thanks alot..
