### ISSUE TITLE
Modlishka reverse proxy like

### ISSUE THREAD

**Issue by HsounaZinoubi** [kgretzky/evilginx2#271]
can you add a feature like https://github.com/drk1wi/Modlishka that reverse proxy a website and in phishlets we have to put only the input id to be captured?
or even better in command line arg
that will be a great feature

i m drunk i think i am talking to Modlishka , my bad sorry dude :)

**Comment by kgretzky** [comment]
What ID? Can you post more details and some examples?

**Comment by HsounaZinoubi** [comment]
in evilginx capturing creds is like this in conf file:
credentials:
  username:
    key: 'email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
we have to set the input name and a general regex to capture it like '(.*)'
it will be more easy if that will be the same here and with command line arg and in conf file if you can do it without the base64 encoding of corse.
and it will be better of you use xpath insteade of regex because it is more easy
