### ISSUE TITLE
help with JS inject

### ISSUE THREAD

**Issue by bojanrodic** [kgretzky/evilginx2#273]
I do not want to ask for help to make phishlet, i allready made few of them for testing, but now i am currious about gmail what is tricky with that, can you explain me what i need to look for exacly for obfuscated JS on gmail login page, than to inject some JS there.
If you can just write little about it, i belive most of people would than understand and even not bother you.
So as gmail has that kinda protection and we are not used to make that, we need just little advice ;
Not that i need it honestly, it is just hard to live with that i can't make that ;)

**Comment by JamesCullum** [comment]
There are two ways to tackle it - rewrite the Javascript that is served or replace it.
You will need to see how much functionality is left when you replace it, so stripping existing one might often be the better choice.

Take a look at my Protonmail phishlet to see how to get around advanced JS protections.

**Comment by bojanrodic** [comment]
Hehe, you answered in right time, i said myself let me compare all phislets to see which one has JS inside, and your and few others had, but your seems to be biggest with much code, reading it i remmembered that cookies are not important for protonmail.

**Comment by micahunder** [comment]
Testing Evilginx2, which is supposed to help me bypass 2FA on web servers by using the MITM proxy phishing attack.
I run into problems with web servers using Cloud fare based JavaScript security to mitigate MITM proxy phishing techniques such Evilginx2.

This leaves my phishing domain hanging on cloud fare's DDOS protection page with the text below.

Checking your browser before accessing cloudflare-protected.site.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by Cloudflare
Ray ID:

Anyway i can use this to bypass this issue?

**Comment by JamesCullum** [comment]
@micahunder Please create a separate issue for this separate topic.

**Comment by horllste** [comment]
> I do not want to ask for help to make phishlet, i allready made few of them for testing, but now i am currious about gmail what is tricky with that, can you explain me what i need to look for exacly for obfuscated JS on gmail login page, than to inject some JS there.
> If you can just write little about it, i belive most of people would than understand and even not bother you.
> So as gmail has that kinda protection and we are not used to make that, we need just little advice ;
> Not that i need it honestly, it is just hard to live with that i can't make that ;)

Hey @bojanrodic

**Comment by solomon-ey** [comment]
inbox me for solution chieflyx@gmail.com
