### ISSUE TITLE
Cant access to my login web page 

### ISSUE THREAD

**Issue by asadsf5959** [kgretzky/evilginx2#276]
i have an issue when im trying to entry to my phishing adress (outlook) then there is no any 
outlook login web site there is just an youtube video displays on my screen how can i fix this when im typing phishlets get-url outlook https://www.youtube.com (for example) then 
![Screenshot from 2019-04-12 23-58-18](https://user-images.githubusercontent.com/49343531/56078039-eb82ef80-5d7e-11e9-9363-6a5c95fd8f14.png)

**Comment by oaredece** [comment]
lures create outlook
lures get-url 0


this is all

**Comment by asadsf5959** [comment]
thanks for help btw how can i make a redirect url like victim when logs in after that how he can go to my website am i should make lures get-url www.redirecturl.com ?

**Comment by oaredece** [comment]
just type help lures ...

**Comment by asadsf5959** [comment]
thanks for everything really now working perfectly
