### ISSUE TITLE
Evilginx2 doesn't setup a Allow-Control-Allow-Origin header if not already in response

### ISSUE THREAD

**Issue by hash3liZer** [kgretzky/evilginx2#280]
I am writing a phishlet for blockchain.com, the problem is that the website uses `CSP-Policy` to prevent cross origin requests and `evilginx2` strips the `CSP-Policy` but it never sets the `Access-Control-Allow-Origin` header at all if not already sent by the server in the respone. And since the request is already cross origin, the browser is preventing the request. 

My question is how could i set a new header `Access-Control-Allow-Origin`? I tried using `sub_filters` but no chance. I also tried setting up the same fake subdomain for both of the cross domains but it only messed up everything. Below is the code from second attempt: 

```
- {phish_sub: 'login', orig_sub: 'login', domain: 'blockchain.com', session: true, is_landing: true}
- {phish_sub: 'login', orig_sub: '', domain: 'blockchain.info', session: true, is_landing: false}
```

**Comment by hash3liZer** [comment]
I made a quick fix by altering the line 475 in `http_proxy.go` file: 

```
if (allow_origin == "" || allow_origin != "") {
    ....
}
```

**Comment by HsounaZinoubi** [comment]
hi @hash3liZer 
i try your fix but when i open the phishing url i got a looping login page
can you share your phishlet please

**Comment by hash3liZer** [comment]
That's strange that you are getting a looping page. It is supposed not be like this and for the phishlet, It's almost done, just a little work and then i am gonna upload it.

**Comment by hash3liZer** [comment]
@HsounaZinoubi Here you go, i've uploaded them on github: https://github.com/hash3liZer/phishlets

**Comment by HsounaZinoubi** [comment]
@hash3liZer thanks but i thin i am too late please send it by email
souna@zinoubi.com

**Comment by alirezadanali** [comment]
Please help with your blockchain phishlets been trying getting errors 
alireza.danali@gmail.com
