### ISSUE TITLE
can't compile on windows -> path error

### ISSUE THREAD

**Issue by narcotic401** [kgretzky/evilginx2#281]
PS C:\Users\Amanda\Downloads\evilginx2-2.3.0\evilginx2-2.3.0> go build main.go

main.go:11:2: cannot find package "github.com/kgretzky/evilginx2/core" in any of:
        C:\Go\src\github.com\kgretzky\evilginx2\core (from $GOROOT)
        C:\Users\Amanda\go\src\github.com\kgretzky\evilginx2\core (from $GOPATH)
main.go:12:2: cannot find package "github.com/kgretzky/evilginx2/database" in any of:
        C:\Go\src\github.com\kgretzky\evilginx2\database (from $GOROOT)
        C:\Users\Amanda\go\src\github.com\kgretzky\evilginx2\database (from $GOPATH)
main.go:13:2: cannot find package "github.com/kgretzky/evilginx2/log" in any of:
        C:\Go\src\github.com\kgretzky\evilginx2\log (from $GOROOT)
        C:\Users\Amanda\go\src\github.com\kgretzky\evilginx2\log (from $GOPATH)

**Comment by thehappydinoa** [comment]
You should run `go get -u github.com/kgretzky/evilginx2` to solve this error.

**Comment by narcotic401** [comment]
Tnx it works !

**Comment by thehappydinoa** [comment]
Glad to help, please close if the issue is fixed 😊
