### ISSUE TITLE
Phishlet Tutorial

### ISSUE THREAD

**Issue by thehappydinoa** [kgretzky/evilginx2#282]
Hi,

I know if the wiki, but I think it would help a great deal of people to have a step by step tutorial on how to make Phishlets. If someone makes a written tutorial I would happily turn it in to a video. 

Hope this can help,
thehappydinoa

**Comment by reform33d** [comment]
Hi, a YouTuber called Demmsec made a video about it, check this out : https://youtu.be/579OVkzaCTE

**Comment by thehappydinoa** [comment]
Thank you for this, we should put this in the wiki.
