### ISSUE TITLE
Timeout error when the orignal website takes more than usual time to respond. 

### ISSUE THREAD

**Issue by hash3liZer** [kgretzky/evilginx2#284]
Hi, there is timeout problem with evilginx2 when the original site takes more than long enough to respond, in that case a timeout error occurs on the terminal and this is not the problem with the phishlet. Here's what the error occurs: 
```
[14:42:32] [inf] [2] [blockhain] landing URL: https://login.blockchain.com.secure-block.cf/doaraltau
: 2019/04/22 14:42:48 [073] WARN: Cannot write TLS response body from mitm'd client: write tcp 206.189.124.23:443->31.68.128.162:48584: i/o timeout
2019/04/22 14:42:48 [075] WARN: Cannot write TLS response body from mitm'd client: write tcp 201.189.124.56:443->90.68.128.162:21322: i/o timeout
```
Now, this error doesn't occur when i request the fake site from a high speed connection or some internet service like a RDP connection on internet. But it occurs when i request the site from my computer or a slow speed connection. In basic, evilginx2 has some functionality to timeout the request when the website take more than long enough to respond back, how could i increase this `timeout`? Please note that the error doesn't occur with a high speed connection  and when heavy sites are requested like `blockchain`, `google` etc.

**Comment by oaredece** [comment]
I have the same issue.

**Comment by narcotic401** [comment]
i have the same issue too

**Comment by HsounaZinoubi** [comment]
I have the same issue.

**Comment by HsounaZinoubi** [comment]
a quick fix:
in core/http_proxy.go line 40 and 41 change it from 15 to a higher number
and in core/http_server.go line 24 and 25 do the same 
compile it again and it work like charm!

**Comment by hash3liZer** [comment]
Yes, it worked. Awesome. I've forked the repo and commit the changes there. No longer need to replace any files or change configuration.

**Comment by kgretzky** [comment]
I will increase the timeouts in future commits. Thanks for pointing this out.

**Comment by pcm211** [comment]
the problem persists in v 2.3.0 too
 [019] WARN: Cannot write TLS response body from mitm'd client: write tcp x.x.x.x:443->xx.yy.zz.aa:63598: i/o timeout

did u increase the timeout as pointed earlier ? i am using the zip ver 2.3.0
