### ISSUE TITLE
Evilginx created website getting blocked by Google

### ISSUE THREAD

**Issue by reform33d** [kgretzky/evilginx2#285]
Hi, i recently used the tool, created a test instagram website but  i immediately had my browser(Google) blocking it and recognizing it as Phishing page. 
![image](https://user-images.githubusercontent.com/49880908/56517674-c55b0d80-653d-11e9-98ad-0325f34fd093.png)

How can i bypass it ?

**Comment by thehappydinoa** [comment]
I believe Google Chrome blocks by domain, I would check to see if your domain is on a blacklist.

**Comment by reform33d** [comment]
Indeed you are right, i just saw that the domain was in spamhaus blacklist, but do you know why it is in ? It has been caused by the use of evilginx right ?

**Comment by thehappydinoa** [comment]
It means spamhaus or another organization saw suspicious traffic coming from your ip/domain.

**Comment by thehappydinoa** [comment]
Please close as this is an issue with your domain and not Evilginx

**Comment by Akshaykerkar** [comment]
Provide command in you evilginix "blacklist unauth on"
