### ISSUE TITLE
Cookie can't login?

### ISSUE THREAD

**Issue by ArunDinfinity** [kgretzky/evilginx2#287]
The session cookie from instagram phishlets is not working?
I import the cookie to cookie editor and refresh the login page but 
It's doesn't login??

Sorry if I distrub you 😶

**Comment by narcotic401** [comment]
i had that prob, i delete all break (new line) maybe this helps you:
on editor after select regex check ,replace all \r\n with nothing , all comes to one line.
if your problem was this kinda,hope be solved.

**Comment by ArunDinfinity** [comment]
Let me check if it's the problem
