### ISSUE TITLE
Why js-inject Not Working in Prefilling username and pushing next button in gmail? 

### ISSUE THREAD

**Issue by narcotic401** [kgretzky/evilginx2#288]
i tried to create PreDefined user for gmail account , just asks password for target , using js-inject but it's never worked!!!
but i Cleared chrome cache , and create new bookmark (page) in google.com login page ! instead url i add this java code and it worked when i pushed ! 

why js-inject not works!!! ???
and i dont think its server/client side problem! and my os is windows server 2012.

**Comment by narcotic401** [comment]
when i set the param it prefilled linkdin but not fillied gmail why?
and why i cant push next button in gmail pls hep me.

**Comment by narcotic401** [comment]
well i made my self , it works great - any one wants ask me: amandalekhaym@gmail.com

**Comment by ewhitman1** [comment]
@narcotic401 can you send me gml phishlet?
