### ISSUE TITLE
502 Bad Gateway with appleid.apple.com website

### ISSUE THREAD

**Issue by reform33d** [kgretzky/evilginx2#293]
Hi, i just created a phishlet for appleid.apple.com wesite, i set up it on Evliginx and i'm now having this error while loading the url on my browser 
![image](https://user-images.githubusercontent.com/49880908/57200159-5abbc000-6f88-11e9-9131-89c7bf53a821.png)

here is the mega link for the phishlet download : https://mega.nz/#!qfAyGYhY!21dbyZocFVcgIFUo_PmShVOxczeGlr8c_kYXDO6ZwjE

Could someone check it and tell me why i may have this error ? 
I don't actually know if it's an apple security measure or if it comes from a potential bad phishlet configuration. 

Thanks anyways.

**Comment by XBALTI** [comment]
you forget some domains: 
apple.com
appleid.cdn-apple.com
add this domains to your phishlets
