### ISSUE TITLE
Hiring someone for appleid.account.com Phishlet

### ISSUE THREAD

**Issue by reform33d** [kgretzky/evilginx2#294]
Hi, i've been trying for few days to make an appleid.account.com phishlet which would work with Evilginx but unluckily without any result as i'm constantly having a "502 Bad Gateway" error while launching the evilginx url.
Therefore, i've decided to ask for someone's help and i'd be paying $15 (PP or BTC)  to the person who makes me a working phishlet specific to the url mentionned above. If you're interested, you can contact me on my email: mathislamour75014@gmail.com

I'm obviously aware that this kind of post may not be appropriate for this github section and i actually apologize for that, to be honest, i couldn't think of an other place to ask for this type of so specific request.

Sorry for the inconvenience again, i'll close this post as soon as i find someone to write the phishlet.

Thanks.

**Comment by safehammer** [comment]
You are too nasty, and cheap same time. Please remove this l4m3r from here.
