### ISSUE TITLE
Captcha problem

### ISSUE THREAD

**Issue by gelabertdionisio432** [kgretzky/evilginx2#299]
First of all you really deserve a huge respect, great work, congrats!

I am trying to create my own phishlets but i am always stuck at recaptcha if the site uses it. Recaptcha is checking the domain being used via API keys. If the domain is not in allowed list then recaptcha doesnt work at all. Any suggestions on this issue ?

**Comment by M3d-Edge** [comment]
i have same problem did you solved this issue?
