### ISSUE TITLE
evilginx2 description uses poor English

### ISSUE THREAD

**Issue by trentprynn** [kgretzky/evilginx2#30]
The evilginx2 Github repository description is currently "Standalone man-in-the-middle attack framework used for phishing login credentials along with session cookies, alowing to bypass 2-factor authentication." The english in this is poor and it should be written. An example new description could be as follows.

"Standalone man-in-the-middle attack framework used for phishing login credentials along with session cookies allowing for the bypass of 2-factor authentication mechanisms."

**Comment by joshdodger197** [comment]
> The **English** in this is poor, and should be **rewritten**.

His English is better than your Polish 👍

**Comment by kgretzky** [comment]
Haha, ok.

"allow for" does sound better. Thanks for input - fixed!

**Comment by trentprynn** [comment]
Great! Thanks for putting this out, hoping to contribute in the near future!
