### ISSUE TITLE
where sessions stored

### ISSUE THREAD

**Issue by saddawe2424** [kgretzky/evilginx2#301]
he,
can anyone tell me where sessions stored i like to send on email.
thanks

**Comment by HsounaZinoubi** [comment]
Just type "sessions"

**Comment by saddawe2424** [comment]
i know that i say i need to send on email than i need to write script but its fine ..in script i need path to get data where those sessions stored in files..

**Comment by HsounaZinoubi** [comment]
check:
~/.evilginx/data.db
it is sqlite db

**Comment by saddawe2424** [comment]
bro i try but not get any file i install using https://github.com/kgretzky/evilginx2/releases and its not any go path and i find path of phishlets at /usr/share/evilginx/phishlets but in evilginx folder here on phishlets folder can you help me to find path its ubuntu 18 .

**Comment by HsounaZinoubi** [comment]
Check your home directory for a folder name:
.evilginx

**Comment by saddawe2424** [comment]
![image](https://user-images.githubusercontent.com/35268406/57919892-32e72900-78b3-11e9-86d8-5af60189a421.png)

**Comment by saddawe2424** [comment]
you see image ?

**Comment by HsounaZinoubi** [comment]
did you install evilginx ?
send the output of command:
evilginx -h

**Comment by saddawe2424** [comment]
![image](https://user-images.githubusercontent.com/35268406/57967761-05b27d80-797c-11e9-9773-49cf12306b50.png)
all is fine also i getting email passwords but where stored ...i install evilginx using this https://github.com/kgretzky/evilginx2/releases i just download and run install.sh ...

**Comment by HsounaZinoubi** [comment]
you can get all sessions data by typing :
sessions
and they are stored in the file system in this file:
~/.evilginx/data.db
or in your current directory:
.evilginx/data.db

**Comment by 234-cell** [comment]
Can you help me on how to run this program

**Comment by 234-cell** [comment]
> you can get all sessions data by typing :
> sessions
> and they are stored in the file system in this file:
> ~/.evilginx/data.db
> or in your current directory:
> .evilginx/data.db

Can you help me on how to run this program please

**Comment by 234-cell** [comment]
> ![image](https://user-images.githubusercontent.com/35268406/57967761-05b27d80-797c-11e9-9773-49cf12306b50.png)
> all is fine also i getting email passwords but where stored ...i install evilginx using this https://github.com/kgretzky/evilginx2/releases i just download and run install.sh ...

Can you help me on how to run this program please
