### ISSUE TITLE
issue with twitter certificates

### ISSUE THREAD

**Issue by tokiijnr** [kgretzky/evilginx2#306]
![Screenshot from 2019-05-22 18-13-33](https://user-images.githubusercontent.com/49600154/58194612-ebe7a200-7cbd-11e9-863d-38580fa5090f.png)

**Comment by dfarrall** [comment]
This is not an issue with the Twitter certificates, it's Lets encrypt telling you that you're rate limited. Read the URL included in the error.

**Comment by tokiijnr** [comment]
ok see this other error 400
everything seems to be correct
![Screenshot from 2019-05-24 04-29-57](https://user-images.githubusercontent.com/49600154/58339453-8d4b3100-7e41-11e9-85fa-bfd8c7d53d74.png)

**Comment by tokiijnr** [comment]
![Screenshot from 2019-05-24 04-33-57](https://user-images.githubusercontent.com/49600154/58339584-d1d6cc80-7e41-11e9-9510-cf62b0a64e55.png)

**Comment by tokiijnr** [comment]
@kgretzky , @byt3bl33d3r
