### ISSUE TITLE
Redirect error & Captcha ERROR for site owner: Invalid domain for site key

### ISSUE THREAD

**Issue by yahirlevine** [kgretzky/evilginx2#31]
I created a phishlet few days ago and it worked fine!.
first error
phishlet get-url go https://www.google.com will take me to the real website login after i enter my credidential.

second error
After i login i get the Captcha
ERROR for site owner: Invalid domain for site key

**Comment by kgretzky** [comment]
Are you posting an issue related to your own private phishlet that noone else can test or confirm?
