### ISSUE TITLE
O365 Error

### ISSUE THREAD

**Issue by alimukarramm** [kgretzky/evilginx2#311]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*<First of all thanks a lot for such an amazing tool. I successfully phished most of the sites but without harming others. I solely do for education or for my organization purpose. When using the O365 phishlet, I am having below error
[18:33:17] [war] [o365] unauthorized request: https://login.outlook.office365.mail.niicrosofts.ca/ (Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4) [198.148.79.10]. 
However, I successfully edit the O365 Phishlet, I do get the login screen and then I diverted to my organization login page but upon supplying the password, I am not allowed to access further. FYI, we are using ADFS. Any help is greatly appreciated. Thanks.>*

Thanks!
--

**Comment by JamesCullum** [comment]
Did you enable ADFS and put the organizations ADFS domain into the phishlet?
