### ISSUE TITLE
Targeting a custom website

### ISSUE THREAD

**Issue by CG-root** [kgretzky/evilginx2#312]
Is it possible to use evilginx without a phishlet. As part of a penetration test, I'm trying to target a custom VPN system in which I can't know what will be the name of the cookie. Therefore, does evilginx can "understand" when the user was successfully authenticated and catch all the set cookies  in order to offer them for impersonation?
Thanks !

**Comment by lean0x2F** [comment]
+1 to this request! Half the time I don't have any clue about what the interesting cookies are as I don't have a valid user (red teaming).

I'm modifying the source code to save all the cookies after the credentials have been submitted, but it would be nice to have that as a configuration parameter.

Great tool by the way, I really appreciate the time you took to build this!

**Comment by lean0x2F** [comment]
I'm sorry I missed that regex on cookies have already been implemented!

@CG-root check this: https://breakdev.org/evilginx-2-1-the-first-post-release-update/

**Comment by vajdis** [comment]
hey, does it work for you with those regex? i was testing it and it just told me cookies were captured but it didnt store them since program thought its not the end of catching i guess :D

**Comment by lean0x2F** [comment]
Same here, I ended up logging all the requests with a reverse proxy in front of evilginx :(

**Comment by vajdis** [comment]
@lean0x2F like using another reverse proxy and evilginx at the same time?
