### ISSUE TITLE
Running multiple instance of same phishlet showing SSL Error

### ISSUE THREAD

**Issue by tanyahaden91** [kgretzky/evilginx2#320]
Hello,

I tried to duplicate a phishlet, change the name of the phishlet and gave it a new hostname and it gets ssl as well but when I try to run both shows ssl error and when I disables one then the other works fine.

Please guide what changes I should do so that both fine at the same time.

Thanks 
Tanya

#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!
--

**Comment by safehammer** [comment]
it will load the first phishlet crt, when you disable it, the other will work. just one at a time. might be because of goproxy library lack of features to support multiple certifcate loading.
