### ISSUE TITLE
Error 400 - urn:acme:error:connection - dns

### ISSUE THREAD

**Issue by jepunband** [kgretzky/evilginx2#322]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*<I CONFIRM>*

Thanks!
--

hi @kgretzky

the issuse :

[18:31:47] [inf] enabled phishlet 'instagram'
[18:31:47] [inf] setting up certificates for phishlet 'instagram'...
[18:31:47] [war] failed to load certificate files for phishlet 'instagram', domain 'instagram.com.fake-insta.live': open /root/.evilginx/crt/instagram.com.fake-insta.live/instagram.crt: no such file or directory
[18:31:47] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[18:31:56] [err] [www.instagram.com.fake-insta.live] acme: Error 400 - urn:acme:error:connection - dns :: DNS problem: NXDOMAIN looking up A for www.instagram.com.fake-insta.live
Error Detail:

[18:31:56] [err] [m.instagram.com.fake-insta.live] acme: Error 400 - urn:acme:error:connection - dns :: DNS problem: NXDOMAIN looking up A for m.instagram.com.fake-insta.live
Error Detail:

[18:31:56] [!!!] failed to obtain certificates
[18:31:56] [inf] disabled phishlet 'instagram'

what i've done so far:

1. purchased a domain "fake-insta.live" (example).
2. made sure port 80 is open.
3. added ns1 , ns2 and point to an ip(external).

   ns1.fake-insta.live  115.87.x.x
   ns2.fake-insta.live  115.87.x.x

4. added A record.

   @      115.87.x.x
   www  115.87.x.x
   
5. added CNAME record.

   m.instagram        fake-insta.live
   www.instagram    fake-insta.live

-----------

└──╼ $nslookup fake-insta.live
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	fake-insta.live
Address:  115.87.x.x
   
   
Is there anything else i've left out? Any help will be much appreciated. thanks.

**Comment by jepunband** [comment]
**[update]** fixed the above error! no worries..

**Comment by techieagle** [comment]
> **[update]** fixed the above error! no worries..

how you fix it?

**Comment by azamet90** [comment]
acme: Error -> One or more domains had a problem:
[m.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.xxx.xxx, url: 
[static.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.xxx.xxx, url: 
[www.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.facebook.com.xxx.xxx, url:





same problem i have how to fix?

**Comment by rrnamitesh** [comment]
> acme: Error -> One or more domains had a problem:
> [m.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.xxx.xxx, url:
> [static.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.xxx.xxx, url:
> [www.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for [www.facebook.com.xxx.xxx](http://www.facebook.com.xxx.xxx), url:
> 
> same problem i have how to fix?

did you find a solution?

**Comment by adisunshine1978** [comment]
I have the same problem can someone advice a solution

**Comment by bl1lnk** [comment]
any update 2022 !!

**Comment by jeretc** [comment]
https://github.com/kgretzky/evilginx2/issues/296#issuecomment-505259964
