### ISSUE TITLE
Lures redirect Cors Policy ACAO error

### ISSUE THREAD

**Issue by Coronon** [kgretzky/evilginx2#323]
* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!
--

Hi there,
As I was making another phishlet I encountered a problem with the lure redirect after everything is intercepted request. For my Icloud.com phishlet I already had to make changes to the core/http_proxy.go file for the 'Access-Control-Allow-Origin' part, but I just can't figure out how to change the ACAO policy of the lure redirect to not be empty. With an empty ACAO I get the following error: 

`Access to XMLHttpRequest at 'https://somewhere.over.rainbow/' (redirected from 'https://www.phishingurl.com/') from origin 'https://www.phishingurl.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

After further investigation, it seems like the browser is blooking the request, because it cant find any ACAO header on 'https://somewhere.over.rainbow'. Is there any way of circumnavigating this behavior?

Cheers
Coronon

**Comment by ghemoo** [comment]
Hi @Coronon for 2 months I have been trying to create the phislet for icloud but without success, can you help me please? if you want I can pay in btc. Feel free to contact me to ghemo@protonmail.com thanks
