### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by nickrh75** [kgretzky/evilginx2#324]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

I CONFIRM

Thanks!
--

New user here, did everything according to the readme, installing the binary release on a an ubuntu 18.04 vps and pointing ns1.mydomain.com and ns2.mydomain.com to its IP.

But when launching always get this resolution error:

> certdb: get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get json "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: dial tcp: lookup acme-v01.api.letsencrypt.org: Temporary failure in name resolution

**Comment by nickrh75** [comment]
solved

**Comment by adisunshine1978** [comment]
how did you solve it ….I am getting the same error
