### ISSUE TITLE
where to install evilginx?

### ISSUE THREAD

**Issue by uviman** [kgretzky/evilginx2#328]
Hi/ Where should I install evilginx : on localhost or digitalocean server?

**Comment by thehappydinoa** [comment]
I would use any remote VPS (Digital ocean, AWS, Google) as using localhost would require you to port forward making your network insecure.

**Comment by azamet90** [comment]
> I would use any remote VPS (Digital Ocean, AWS, Google) as using localhost would require you to port forward making your network insecure.

is it not posible to do it with tunneling? if yes then can you send me any tutorial links for doing that?
