### ISSUE TITLE
Instagram phishlet not redirecting nor capturing cookies

### ISSUE THREAD

**Issue by xMG-ReduX** [kgretzky/evilginx2#329]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

**I CONFIRM**

Thanks!
--

Hi,
i managed to get the site working just fine but when i put in my own login to test (which had 2FA) it just showed a message in red saying cannot connect to instagram and to check your internet connection and won't redirect nor capture the cookies, however it did capture username & password just fine. Is this a problem with the .yaml phishlet itself or on IG's end?

![Screenshot-2019-7-4 Login • Instagram](https://user-images.githubusercontent.com/33795485/60694253-60ebf100-9e92-11e9-8bea-184740bac6f0.png)

**Comment by rzmpzgeviii** [comment]
@5ky1ar  did you manage to fix it? Got the same!
