### ISSUE TITLE
EvilGinx2 - Adding HOSTNAME for (Custom) Phishlet NOT WORKING 

### ISSUE THREAD

**Issue by kingroot34** [kgretzky/evilginx2#334]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!
--

**Comment by kingroot34** [comment]
Hello, 

I have sent you an email regarding the problem with a screenshot proof 

I have created my own phishlet 

The moment  I want to set up a hostname (using the readme file) it comes back with an error 

it then asks that i use <domain> in this format for it to be taken in by Evilginx2, HOWEVER, once I enable the phishlet I receive, (acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: Invalid character in DNS name).

This problem is coming from when you try to set up a hostname for the phishlets where Evilginx2 does not take into consideration the domain name unless it is written in this way <domain>

please check my email which I have sent you or let me know if you would like me to  post the screenshot here for you to check it out 

Thank you for taking the time to read this 

Ps: Also I have a problem getting into the -developer mode when I start Evilginx2, if you can check this out also will be great 

Once again thank you for taking the time to read this

**Comment by iamtelo** [comment]
UNRELATED. id like insight on how you created your phishlet. i created mine but it doesnt show up on the phishlets list. any suggestions?

**Comment by kingroot34** [comment]
> 
> 
> UNRELATED. id like insight on how you created your phishlet. i created mine but it doesnt show up on the phishlets list. any suggestions?

hello, 

Please send me an email for us to conversate ;)

**Comment by digitalnomadist** [comment]
I CONFIRM

**Comment by digitalnomadist** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> _I CONFIRM_
> 
> ## Thanks!

I CONFIRM
