### ISSUE TITLE
Change (All User Agent) To (Static) -> Windows NT

### ISSUE THREAD

**Issue by macronc4** [kgretzky/evilginx2#337]
How to change all (ios/Android) User agents to : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by macronc4** [comment]
i solve it

**Comment by Anonymoushawk** [comment]
@macronc4  how did you do it ?

**Comment by horllste** [comment]
How is this possible? Can you help?

**Comment by macronc4** [comment]
Yes bro but now it's for sale 100$ with all options

**Comment by horllste** [comment]
How do I contact you?
