### ISSUE TITLE
Anyone with google or gmail phishlet? I will pay drop ur icq or email.

### ISSUE THREAD

**Issue by newskl007** [kgretzky/evilginx2#341]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*<type_in_here>*

Thanks!
--

Anyone with google or gmail phishlet? I will pay drop ur icq or email.

**Comment by lofthotel** [comment]
Yes i have... please add for talk 
fullzzcc@jabb.im

**Comment by Westtri23** [comment]
@lofthotel 
Anyone with google or gmail phishlet?

**Comment by Westtri23** [comment]
@newskl007  Anyone with google or gmail phishlet?

**Comment by lofthotel** [comment]
Yes i have add me

**Comment by Westtri23** [comment]
@lofthotel how can we contact?

**Comment by lofthotel** [comment]
add me       fullzzcc (at)  jabb.im
