### ISSUE TITLE
Is it possible to use something like NGrok or Serveo?

### ISSUE THREAD

**Issue by keniobats** [kgretzky/evilginx2#35]
Hello,

First of all, congrats for such an amazing project! 
I didn't tried yet, but I would like to know if its possible to use ngrok or serveo to forward all the traffic to a more "untraceable" site. Also to avoid buying and setting up a server(mostly because of privacy issues).

Hope it makes sense for you.
Thanks in advance!

**Comment by audibleblink** [comment]
You need control over dns for the domain you're sending people to. 
To achieve something similar, you can lease a VPS, give it a domain name, set the nameservers to itself start evilginx2 and use reverse ssh tunnel from you pc.

```
ssh -fNT -R 0.0.0.0:443:127.0.0.1:443 -R 0.0.0.0:80:127.0.0.1:80 user@vpshost

**Comment by kgretzky** [comment]
Thanks!

In other words you are asking how to anonymously buy and set up servers for evilginx to not get caught while phishing people?

**Comment by keniobats** [comment]
Hello!
Shortly, yes. The main idea would be to avoid using(and buying) a VPS and just use your own computer, hiding behind something like ngrok for two reasons:

- Privacy issues(it's relatively easy to know who is behind a vps)
- Setting up the server. Perhaps it's easier to set up your own pc and launch attacks from there, than changing/buying/configuring new servers for each target to avoid being tracked down.

Hope it makes sense to you. 
Thanks for your support!

**Comment by kgretzky** [comment]
I don't have experience with using these. For Evilginx to work you need to own a domain and be able to generate SSL/TLS certificates for it. Feel free to try and let me know.

**Comment by tom770022** [comment]
Hey keniobats, did it work?

**Comment by ad7608327** [comment]
I have Weird Ques 
IF it possible to Build Service Like Ngrok And Serveo 
AND What Should I do?

**Comment by Phone-Metal** [comment]
@kgretzky is it possible to host it on localhost somehow ?
(sorry i have a bad English)

**Comment by KiltzX** [comment]
Be careful, if you don't already know, right?

https://www.youtube.com/watch?v=zjp3Y2okal4
