### ISSUE TITLE
o365 issue

### ISSUE THREAD

**Issue by jerremyfrancis** [kgretzky/evilginx2#354]
Hello,
I'm getting that error on trying to log into my account. Any help is appreciated.

=========================================================
We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
=========================================================

Thanks in advance.

**Comment by anonymonline2020** [comment]
same error, u can fixed?

**Comment by mother2110** [comment]
Was this ever solved? Is this a o365.yaml thing?
