### ISSUE TITLE
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure . I got this error in google phishlet i think google updated their policy ,any updates related to this issue?

### ISSUE THREAD

**Issue by gillufarooq** [kgretzky/evilginx2#356]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*
Thanks!
![Capture](https://user-images.githubusercontent.com/55867369/65759269-f6b2b780-e133-11e9-8e8d-dffff9b5da91.PNG)

**Comment by Delonorafrol** [comment]
Same here. Interestingly enough, it doesn't happen for the desktop version of Chrome. But it does on Android.

**Comment by Delonorafrol** [comment]
Same here. I think it has to do with new security controls implemented by Google, specifically aimed at MITM attacks. You can read more about it here: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

Key Points:

"However, one form of phishing, known as “man in the middle” (MITM), is hard to detect when an embedded browser framework (e.g., Chromium Embedded Framework - CEF) or **another automation platform is being used for authentication.** 

And Again:

"Because we can’t differentiate between a legitimate sign in and a MITM attack on these platforms, we will be blocking sign-ins from embedded browser frameworks starting in June."

I'm not good enough in Golang to say whether this is the reason, or if it's another reason. That's being said, if this is the case, it's difficult to bypass.

**Comment by gillufarooq** [comment]
@Delonorafrol  thanks for the info :)

**Comment by Yulia1991lab** [comment]
@Delonorafrol 
@gillufarooq 

Hi can you share your email address so that I can talk to you regarding some help with the same.

**Comment by gillufarooq** [comment]
@Yulia1991lab  gillufarooq@gmail.com

**Comment by gillufarooq** [comment]
@Delonorafrol  it happens on both android as well as in desktop version..

**Comment by Yulia1991lab** [comment]
@Delonorafrol yes, any suggestions?

**Comment by gillufarooq** [comment]
@Yulia1991lab have you found any solution?

**Comment by Delonorafrol** [comment]
I don't think much can be done here. It's was a great tool. However, I might be speaking out of ignorance or lack of knowledge concerning how these things work, as I'm not a programmer.

**Comment by Delonorafrol** [comment]
Is there some way we can msg each other? Does Github have a chat feature?

**Comment by gillufarooq** [comment]
Phishing attacks carried out by injecting malicious content in legitimate traffic are difficult to detect when attackers use an embedded browser framework or any other automated tool for authentication.

For example, the embedded browser framework Google offers Chromium Embedded Framework (CEF) that allows embedding Chromium-based browsers in other applications.

Google announced that starting from June, it will block sign-ins from these frameworks.

“However, one form of phishing, known as “man in the middle” (MITM), is hard to detect when an embedded browser framework (e.g., Chromium Embedded Framework – CEF) or another automation platform is being used for authentication. MITM intercepts the communications between a user and Google in real-time to gather the user’s credentials (including the second factor in some cases) and sign in.” reads a blog post published by Google. “Because we can’t differentiate between a legitimate sign in and a MITM attack on these platforms, we will be blocking sign-ins from embedded browser frameworks starting in June. This is similar to the restriction on webview sign-ins announced in April 2016.”


**https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html**

**Comment by cashpot7777** [comment]
Can you please send me gmail phishlet on stefanstamenovski13@gmail.com

**Comment by fakelawface** [comment]
Any fix yet?

**Comment by Yulia1991lab** [comment]
@fakelawface share your email address....

**Comment by redrabbiteam** [comment]
Full Solution available with me.
Contact me  
at
anonymoushawk0@gmail.com

**Comment by devilspartner** [comment]
@fakelawface 
any solution for this error please.
email id-santro5322@gmail.com

**Comment by devilspartner** [comment]
@Yulia1991lab 
any solution for this error please.
email id-santro5322@gmail.com

**Comment by devilspartner** [comment]
@gillufarooq 
any solution for this error please.
email id-santro5322@gmail.com

**Comment by devilspartner** [comment]
@gillufarooq @fakelawface  any solution bro please help

**Comment by muratsnkl** [comment]
any solutions? Please share me muratsnkl@gmail.com

**Comment by muratsnkl** [comment]
@Yulia1991lab Can you share me solutions?

**Comment by Anonymoushawk** [comment]
@muratsnkl  contact at anonymouhawk0@protonmail.com

**Comment by dr-tro** [comment]
@Yulia1991lab send your ideas please, drtro@protonmail.com

**Comment by Anonymoushawk** [comment]
@dr-tro  i have solution contact me on anonyoushawk0@protonmail.com

**Comment by barman1337** [comment]
If some has a working yaml, can he share it with me ? Bar.ivgi@yahoo.com

**Comment by GAMhackER** [comment]
Is gmail works anymore?

**Comment by obnoxiousish** [comment]
I am reviving this because I have some information regarding it.

```
:authority: accounts.google.com
:method: POST
:path: /v3/signin/_/AccountsSignInUi/data/batchexecute?rpcids=B4hajb&source-path=/v3/signin/challenge/totp&f.sid=1424135656401836681&bl=boq_identityfrontendauthuiserver_20231022.06_p0&hl=en&TL=AIBe4_L__9Vobcj4qQuVDSng6G9Sl_-svMChDCQh73hOgUkHASy5rUXJq78B2tyw&_reqid=1009868&rt=c
```

A request that looks like this will return some data like this

```
)]}'

106
[["wrb.fr","B4hajb",null,null,null,[3],"generic"],["di",118],["af.httprm",117,"-5832201465353096685",6]]
25
[["e",4,null,null,142]]
```

If it thinks your sign in is being MITM'd

But returns something like

```
)]}'

551
[["wrb.fr","B4hajb","[null,null,null,null,[null,[2,[null,[null,null,\"https://accounts.google.com/CheckCookie?continue\\u003dhttps://accounts.google.com/\\u0026checkedDomains\\u003dyoutube\\u0026checkConnection\\u03dyoutube:172:1\\u026pstMsg\\u003d1\\u026flowName\\u003dGlifWebSignIn\\u0026ifkv\\u003eywKNMVBBthoDWhbSmUjFEJsX0hLzd_2EPtiQ\\u0026theme\\u003dglif\\u0026chtml\\u003dLoginDoneHtml\\u002gidl\\u003dEgIIAA\"]]]]]",null,null,null,"generic"],["di",752],["af.httprm",751,"-877652168012664208",6]]
25
[["e",4,null,null,587]]
```

If it thinks your sign in is legitimate.

I am unsure why this is as going out of my way to ensure every request is completed without errors and properly MITM'd this still happens

I believe it is potentially some kind of javascript MITM check by grabbing the current URL of the browser and encoding it or encrypting it or hashing it etc before sending it to the server to be checked/validated

Not 100% sure and if someone ever figures it out let me know
