### ISSUE TITLE
Session Cookie

### ISSUE THREAD

**Issue by yahirlevine** [kgretzky/evilginx2#36]
Login cookie is captured on login before we enter credidential. After you login the same cookie change his value. We can`t login because the script capture the session cookie before the login and new cookie value is not captured, only the old one.

**Comment by customsync** [comment]
This issue would indirectly be resolved by the feature mentioned in [issue #24](https://github.com/kgretzky/evilginx2/issues/24). You are correct in your observation that applications react differently in how/when they set session cookies. I've thought about adding functionality to support this, but you should feel free to do the same!

**Comment by kgretzky** [comment]
Yes, this is a known issue related to #24

**Comment by yahirlevine** [comment]
Thanks guys! I am affraid i dont know how to fix this issue. I am just a hobbiest with not so many knowledge like you guys. I am trying different websites with the exemples from this script.
