### ISSUE TITLE
ACME V2 error

### ISSUE THREAD

**Issue by Akywondo** [kgretzky/evilginx2#360]
[21:33:49] [inf] requesting SSL/TLS certificates from LetsEncrypt...                                                                                                 
[21:33:49] [!!!] acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACM│············Ev2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.>*

Any thoughts on this ?

Thanks!

**Comment by cipherhat** [comment]
"acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details."

installed evilginx yesterday with no issue but am getting this error today 

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/2

how do we get the ACME v1 upgraded to v2

**Comment by kgretzky** [comment]
Thanks for reporting!

Sounds like I need to upgrade the ACME library.

**Comment by cipherhat** [comment]
has it been upgraded?

**Comment by kgretzky** [comment]
Fixed with https://github.com/kgretzky/evilginx2/commit/3d85ff9e19f4524719d55fd49133e823691e9806

**Comment by norisharma** [comment]
acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RF                                    C 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.


Still got this error its work find yesterday. i used  precompiled binary package  linux  but its not working

**Comment by muratsnkl** [comment]
I still get the same error. Is there any solution?

**Comment by oyinmbam** [comment]
🙋🏾‍♂️ Any solution yet ?

**Comment by horllste** [comment]
delete the installed version and reinstall from https://github.com/kgretzky/evilginx2/archive/master.zip


Works for me

**Comment by diewithurlie** [comment]
> delete the installed version and reinstall from https://github.com/kgretzky/evilginx2/archive/master.zip
> 
> Works for me

can share how u install it?

**Comment by Corsecco** [comment]
yup need some help too, i also have this problem ^^

*:
acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by horllste** [comment]
Chat me privately

**Comment by Corsecco** [comment]
@horllste ok, where can i send u a message ?

**Comment by 3vall** [comment]
1. Install go on your server. Follow[ these steps](https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-18-04)
2. Run these commands

```
sudo apt-get install git make
go get -u github.com/kgretzky/evilginx2
cd $GOPATH/src/github.com/kgretzky/evilginx2
make
sudo make install
sudo evilginx
```

Optional: If you face an error while running `make` command, then
open the MakeFile
remove the -mod=vendor
save it and run the make command again. Thats all

**Comment by Corsecco** [comment]
@3vall yup dude do you have Discord ? i have some questions ^^ mine is Secco#7253

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by horllste** [comment]
Sent you a request on discord
