### ISSUE TITLE
The url redirection is acting strangely

### ISSUE THREAD

**Issue by redlocks** [kgretzky/evilginx2#362]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
I CONFIRM 

Hi, I've encountered such a problem - when adding a new redirection url for lures after a successful session capture, it doesn't happen, but only after the page refresh (or sometimes immediately after clicking on a phishing link). Who's ever seen anything like it? Have you found a solution? 

Thank you in advance.
--

**Comment by redlocks** [comment]
It happens even though all the tokens are intercepted

**Comment by elagrija** [comment]
Hi Redlocks,

Believed you have crossed my stage of issue.
Can you pls look into concern i posted and could you help me to move forward.


Thanks,
Ela
