### ISSUE TITLE
Not able to get default phishing site page

### ISSUE THREAD

**Issue by elagrija** [kgretzky/evilginx2#363]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*< I CONFRIM>*

Thanks!
--
 Hi,

I couldn't manage to get the  default phishing site page of linked in page stored @evilginx server.
when loaded my domain in webbrowser, which loaded   only the "youtube URL"  stored in config.

PFB the same,
![evilginxquery](https://user-images.githubusercontent.com/13571168/66703283-97a59300-ed2e-11e9-99bf-396b195aa1d1.PNG)

Kinldy review and help me to get resolved the same.

**Comment by redlocks** [comment]
Try command: lures create <phishlet name>
This will give you your id back (you can also see it by typing lures)
Then: lures get-url <id>

**Comment by elagrija** [comment]
Thanks you

Let me try and back to you

Thanks
Ela
