### ISSUE TITLE
go get -u github.com/kgretzky/evilginx2 give me error

### ISSUE THREAD

**Issue by marceaupatu123** [kgretzky/evilginx2#364]
**I CONFIRM**

I have this error :

package evilginx2/core: unrecognized import path "evilginx2/core" (import path does not begin with hostname)
package evilginx2/database: unrecognized import path "evilginx2/database" (import path does not begin with hostname)
package evilginx2/log: unrecognized import path "evilginx2/log" (import path does not begin with hostname)

**Comment by kgretzky** [comment]
Fixed with https://github.com/kgretzky/evilginx2/commit/5afb6d95a32f64adf28a861118faa9f489bc90d9
