### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by digoblin** [kgretzky/evilginx2#368]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

I CONFIRM

Thanks!
--
Hello,
i've just cloned the repo and tried to build the image, but it appears that two files are missing, at least I can't find them in the repo.
The files required are referenced on Dockerfile's third step and are the following:
`COPY Gopkg.toml Gopkg.lock ./`

My error when building the image:
![Selection_084](https://user-images.githubusercontent.com/4185420/66825213-b9c32f00-ef41-11e9-9718-a2c1a52a1f7f.png)

Thank you for all the work done!

**Comment by kgretzky** [comment]
Hey. I've switched the project to use GO modules, which apparently broke the Dockerfile config.
Waiting for someone to fix it and publish a PR.

**Comment by redlocks** [comment]
> Hey. I've switched the project to use GO modules, which apparently broke the Dockerfile config.
> Waiting for someone to fix it and publish a PR.

Maybe it'll be helpful?
https://medium.com/@petomalina/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888

**Comment by antoineVIVIES** [comment]
Hey, I have made a pull PR to fix this issue: https://github.com/kgretzky/evilginx2/pull/424

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> I CONFIRM
> 
> ## Thanks!
> Hello,
> i've just cloned the repo and tried to build the image, but it appears that two files are missing, at least I can't find them in the repo.
> The files required are referenced on Dockerfile's third step and are the following:
> `COPY Gopkg.toml Gopkg.lock ./`
> 
> My error when building the image:
> ![Selection_084](https://user-images.githubusercontent.com/4185420/66825213-b9c32f00-ef41-11e9-9718-a2c1a52a1f7f.png)
> 
> Thank you for all the work done!

i can help you with the issue..rickorkins@gmail.com
