### ISSUE TITLE
No more Gopkg.toml file

### ISSUE THREAD

**Issue by redlocks** [kgretzky/evilginx2#378]
https://github.com/kgretzky/evilginx2/blob/99f83c3740dc95204e207a2adc71c6ec9190a613/Dockerfile#L11

Step 5/16 : COPY Gopkg.toml Gopkg.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder655881099/Gopkg.toml: no such file or directory

**Comment by redlocks** [comment]
https://github.com/kgretzky/evilginx2/issues/368

**Comment by rrnamitesh** [comment]
> #368

did you find any solution?
