### ISSUE TITLE
Feature request: configure ip, domain, phishlets hostname and url with token from the config file

### ISSUE THREAD

**Issue by redlocks** [kgretzky/evilginx2#379]
Hi, I think it would be cool to download the domain, ip, and phishlets settings from the configuration file to exclude manual input. This would make it easier and faster to deploy the server. Is this possible?

**Comment by redlocks** [comment]
For example: evilginx -p ./phishlets -c path/to/config.yaml

**Comment by arinze12345** [comment]
> Hi, I think it would be cool to download the domain, ip, and phishlets settings from the configuration file to exclude manual input. This would make it easier and faster to deploy the server. Is this possible?

i can help you with the issue..rickorkins@gmail.com

**Comment by Coronavirus27009** [comment]
Hello, really looking for someone"s guidance..

I ran these codes to get started with the evilginx2 successfully

sudo apt-get -y install git make
git clone https://github.com/kgretzky/evilginx2.git
cd evilginx2

now the next step on the github page says run "make" next but i did and it didnt go.

i am currently running it on mac terminal, i need help passing this stage.

Thank you and looking forward to getting a response from anybody.
