### ISSUE TITLE
Problem: Google phishlet

### ISSUE THREAD

**Issue by haryedison** [kgretzky/evilginx2#38]
Hi

After I'm building Google phishlet from evilginx ver 1.1, It wasn't work.
Generated link worked but Next and Forgot Password and Create Mail buttoms in the Google sign in page not worked.

I need it for my article.
Plz help me.
Thanks

**Comment by haryedison** [comment]
Plz help me.

**Comment by embutidox** [comment]
Hi.
With the imported phislet from 1.1 , I can get the credentials but I do not get the cookie. 
Maybe you know why? 
Thanks.
