### ISSUE TITLE
It's straight away not working for me!!

### ISSUE THREAD

**Issue by IAM1here** [kgretzky/evilginx2#382]
Hello, i did all the configurations correctly on my vps on aws, it's gets me the uslr after the ssl setup but when i copy and use the link , it keeps on loading and the page doesn't load at all , please let me know the possible  solution!
@kgretzky 
thanks

**Comment by IAM1here** [comment]
I am doing it for outlook!

**Comment by arinze12345** [comment]
> Hello, i did all the configurations correctly on my vps on aws, it's gets me the uslr after the ssl setup but when i copy and use the link , it keeps on loading and the page doesn't load at all , please let me know the possible solution!
> @kgretzky
> thanks

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
> Hello, i did all the configurations correctly on my vps on aws, it's gets me the uslr after the ssl setup but when i copy and use the link , it keeps on loading and the page doesn't load at all , please let me know the possible solution!
> @kgretzky
> thanks

if you are on aws, its because you have not open the ports to the public, you have to open some port to allow the connections
