### ISSUE TITLE
Feature request: Possibility of asymmetric session encryption

### ISSUE THREAD

**Issue by redlocks** [kgretzky/evilginx2#384]
Hi, I think it would be cool to be able to asymmetrically encrypt passwords and sessions when intercepting. This is necessary when evilginx is deployed on vps, which can be compromised or is not trusted. What do you think, @kgretzky?

**Comment by J3rry367** [comment]
Any movement on this? I would love to be able to have the gathered data saved to an encrypted file rather than cleartext, or an encrypted email sent to me for each submission.
