### ISSUE TITLE
EditThisCookie is it patch?

### ISSUE THREAD

**Issue by WorkenX** [kgretzky/evilginx2#388]
Hello :)

Everything is working very well. I recover cookies. I insert them with "EditThisCookie". I refresh the page and nothing at all.

have a nice day.

**Comment by WorkenX** [comment]
Oh okey thanks for your reply.

I test Cookie Editor, but i can just "add a new cookie" and not "import" like on EditThisCookie  :/

Because when i "add a new cookie" and when i paste the cookie in "cookie value", this is not work too.

**Comment by kgretzky** [comment]
Did you update to 2.3.2 from master branch? It was fixed a week ago.

**Comment by WorkenX** [comment]
No i m on EvilGinx2 2.3.0. This is maybe that :)

**Comment by siir4ever** [comment]
@kgretzky  any information the google problem 
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure

**Comment by WorkenX** [comment]
Sorry but how update to 2.3.2 from master branch?

**Comment by kgretzky** [comment]
Guys I've stated it hundreds of times everywhere, do not ask for phishlets and there is no phishlet creation service here. Create your phishlets and submit PR.

@WorkenX there is a readme

**Comment by siir4ever** [comment]
@kgretzky  we not asking about phislets , only security update , we talking about the new google update

**Comment by WorkenX** [comment]
I don't see in readme what you want to say by "2.3.2" ?

**Comment by redrabbiteam** [comment]
Solution is available with me if any one wants, please contact me

**Comment by redrabbiteam** [comment]
> Hello :)
> 
> Everything is working very well. I recover cookies. I insert them with "EditThisCookie". I refresh the page and nothing at all.
> 
> have a nice day.

Solution is available with me if any one wants, please contact me

**Comment by redrabbiteam** [comment]
Full Solution available with me.
Contact me  
at
anonymoushawk0@gmail.com
