### ISSUE TITLE
Problem with Google phishlet

### ISSUE THREAD

**Issue by HEdison** [kgretzky/evilginx2#39]
Hi

After I'm building Google phishlet from evilginx ver 1.1, It wasn't work.
Generated link worked but "Next" and "Forgot Password" and "Create Mail" buttons in the Google sign in page not worked.

I need it for my article.
Plz help me.
Thanks

[google.txt](https://github.com/kgretzky/evilginx2/files/2320403/google.txt)

**Comment by kgretzky** [comment]
If you manage to fix the buttons, it should work.
