### ISSUE TITLE
Phishlets hidden url

### ISSUE THREAD

**Issue by johankurt77** [kgretzky/evilginx2#390]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!

--
The phipshlets hide url block all the domain.com (example). You can't make it to block and redirect the domain.com and let go ahead the domain.com/random? Thanks

**Comment by johankurt77** [comment]
So all the lures path can go to ahea and will never been blocked, phishlets hidden command to block only the hostname.  Thanks

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> _I CONFIRM_
> 
> Thanks!
> 
> --
> The phipshlets hide url block all the domain.com (example). You can't make it to block and redirect the domain.com and let go ahead the domain.com/random? Thanks

i can help you with the issue..rickorkins@gmail.com
