### ISSUE TITLE
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure . I got this error in google phishlet i think google updated their policy ,any updates related to this issue?

### ISSUE THREAD

**Issue by redrabbiteam** [kgretzky/evilginx2#392]
Solution is available.
Interested persons can contact me

**Comment by StratoMusic** [comment]
how to contact you?

**Comment by redrabbiteam** [comment]
Contact me
anonymoushawk0@protonmail.com

**Comment by muratsnkl** [comment]
Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...

**Comment by redrabbiteam** [comment]
> I am also looking at this over the next week. If anyone is interested to compare notes, please drop me a line at [zoomdeveloper@protonmail.com](mailto:zoomdeveloper@protonmail.com)

anonymoushawk0@protonmail.com

**Comment by redrabbiteam** [comment]
> Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...

anonymoushawk0@protonmail.com

**Comment by muratsnkl** [comment]
> > Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...
> 
> [anonymoushawk0@protonmail.com](mailto:anonymoushawk0@protonmail.com)

Already contact you. please reply my email

**Comment by randalharris** [comment]
i have solution contact me randallharris129@gmail.com

**Comment by maisonmargiela0** [comment]
> 
> 
> Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...

Did anyone help you with the gmail phislet solution? Thank you in advance

**Comment by arinze12345** [comment]
> > Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...
> 
> Did anyone help you with the gmail phislet solution? Thank you in advance

i can help you with the issue..rickorkins@gmail.com

**Comment by arinze12345** [comment]
> > > Everyone sad i have one solutions bla bla bla... When you contact for solutions ther are say $5K $10K...
> > 
> > 
> > [anonymoushawk0@protonmail.com](mailto:anonymoushawk0@protonmail.com)
> 
> Already contact you. please reply my email

i can help you with the issue..rickorkins@gmail.com
