### ISSUE TITLE
Problems with acme

### ISSUE THREAD

**Issue by dariusplaza** [kgretzky/evilginx2#395]
Hello. Faced a problem that I can’t solve for the second day. The fact is that I successfully received the Encrypt certificate (http://prntscr.com/pqbs1d) but when I enter phishlet I get this message http://prntscr.com/pqbsu3
Please tell me what is the problem?

**Comment by pcsmith2** [comment]
Having the same issue

**Comment by dariusplaza** [comment]
Somebody know how to resolve?

**Comment by pcsmith2** [comment]
I grabbed the latest evilnginx release instead of pulled from master, it seems to have fixed the issue for now.

**Comment by dariusplaza** [comment]
Can you give me some link?

**Comment by pcsmith2** [comment]
https://github.com/kgretzky/evilginx2/releases/tag/2.3.0

**Comment by arinze12345** [comment]
> Hello. Faced a problem that I can’t solve for the second day. The fact is that I successfully received the Encrypt certificate (http://prntscr.com/pqbs1d) but when I enter phishlet I get this message http://prntscr.com/pqbsu3
> Please tell me what is the problem?

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
check your dns
