### ISSUE TITLE
having some issues with lures pls help 

### ISSUE THREAD

**Issue by DSUN01** [kgretzky/evilginx2#398]
i did this
lures edit redirect_url <1> https://login.live.com
and i got this
[err] lures: edit: strconv.Atoi: parsing "<1>": invalid syntax
what may be the problem

**Comment by arinze12345** [comment]
> i did this
> lures edit redirect_url <1> https://login.live.com
> and i got this
> [err] lures: edit: strconv.Atoi: parsing "<1>": invalid syntax
> what may be the problem

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
> i did this
> lures edit redirect_url <1> https://login.live.com
> and i got this
> [err] lures: edit: strconv.Atoi: parsing "<1>": invalid syntax
> what may be the problem

remove the <>
