### ISSUE TITLE
get-url not working for me

### ISSUE THREAD

**Issue by DSUN01** [kgretzky/evilginx2#399]
the url generated by lures get-url is not opening in my browser 
is there anything am doing wrong ?
please i need urgent help

**Comment by arinze12345** [comment]
> the url generated by lures get-url is not opening in my browser
> is there anything am doing wrong ?
> please i need urgent help

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
> the url generated by lures get-url is not opening in my browser
> is there anything am doing wrong ?
> please i need urgent help

you are using aws so you need to open the ports manually.
