### ISSUE TITLE
Having issues enabling phishlets

### ISSUE THREAD

**Issue by DSUN01** [kgretzky/evilginx2#400]
after typing this command  <phishlets enable outlook> see what i got below pls i need help

[16:56:47] [inf] enabled phishlet 'outlook'
[16:56:47] [inf] setting up certificates for phishlet 'outlook'...
[16:56:47] [war] failed to load certificate files for phishlet 'outlook', domain 'mttn.net': open /root/.evilginx/crt/mttn.net/outlook.crt: no such file or directory
[16:56:47] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[16:56:49] [!!!] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url: 
[16:56:49] [inf] disabled phishlet 'outlook'

**Comment by threst** [comment]
i need help too

**Comment by pir4cy** [comment]
stuck as well, possible solutions are updating acme, I think, but it didn't work for me, maybe I'm just doing it wrong

**Comment by DSUN01** [comment]
just buy a linux online server and run your evilginx from there or i can help you do that

**Comment by adisunshine1978** [comment]
I have ubuntu server but having the same issue

**Comment by arinze12345** [comment]
> after typing this command see what i got below pls i need help
> 
> [16:56:47] [inf] enabled phishlet 'outlook'
> [16:56:47] [inf] setting up certificates for phishlet 'outlook'...
> [16:56:47] [war] failed to load certificate files for phishlet 'outlook', domain 'mttn.net': open /root/.evilginx/crt/mttn.net/outlook.crt: no such file or directory
> [16:56:47] [inf] requesting SSL/TLS certificates from LetsEncrypt...
> [16:56:49] [!!!] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:
> [16:56:49] [inf] disabled phishlet 'outlook'

i can help you with the issue..rickorkins@gmail.com

**Comment by arinze12345** [comment]
> i need help too

i can help you with the issue..rickorkins@gmail.com

**Comment by arinze12345** [comment]
> i need help too

i can help you with the issue..rickorkins@gmail.com



> stuck as well, possible solutions are updating acme, I think, but it didn't work for me, maybe I'm just doing it wrong

i can help you with the issue..rickorkins@gmail.com

**Comment by arinze12345** [comment]
> i need help too

i can help you with the issue..rickorkins@gmail.com



> stuck as well, possible solutions are updating acme, I think, but it didn't work for me, maybe I'm just doing it wrong

i can help you with the issue..rickorkins@gmail.com

> I have ubuntu server but having the same issue

i can help you with the issue..rickorkins@gmail.com
