### ISSUE TITLE
 acme: error: 400 :: POST when configure phishlet

### ISSUE THREAD

**Issue by dev658** [kgretzky/evilginx2#401]
And i'm wondering if its not because of my domain server?(porkbun)
I did all as described, but I have this error when evilngix try to connect to secure ssl and answer negatively.

What can fix the problem?

**Comment by arinze12345** [comment]
> And i'm wondering if its not because of my domain server?(porkbun)
> I did all as described, but I have this error when evilngix try to connect to secure ssl and answer negatively.
> 
> What can fix the problem?

i can help you with the issue..rickorkins@gmail.com
