### ISSUE TITLE
acme error :/ bad english need help :(

### ISSUE THREAD

**Issue by azamet90** [kgretzky/evilginx2#405]
my english is bad that for i watch a youtube tutorial how to use it to learn what this script is doing...
not for illegal prupose i just want to understand it...
but i get this error at the end: 
acme: Error -> One or more domains had a problem:
[m.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.nodomain.ml, url: 
[static.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.nodomain.ml, url: 
[www.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.facebook.com.nodomain.ml, url:

i did these steps what this guy is doing: https://www.youtube.com/watch?v=vks33TsoTiU

what am i doing wrong to get this error? the script have a problem or me?

i think i need to share the domain right? so i edit the post for it:
output from command "config"
             domain : userpanel.ml
                 ip : 159.65.141.179
       redirect_key : mr
   verification_key : at
 verification_token : 9015
       redirect_url : https://www.google.com/

tryed with this domain https://safe-script.ml/ result same...

**Comment by azamet90** [comment]
and how to remove evilginx2 completely? i did install it local

**Comment by arinze12345** [comment]
> my english is bad that for i watch a youtube tutorial how to use it to learn what this script is doing...
> not for illegal prupose i just want to understand it...
> but i get this error at the end:
> acme: Error -> One or more domains had a problem:
> [m.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.nodomain.ml, url:
> [static.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.nodomain.ml, url:
> [www.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for [www.facebook.com.nodomain.ml](http://www.facebook.com.nodomain.ml), url:
> 
> i did these steps what this guy is doing: https://www.youtube.com/watch?v=vks33TsoTiU
> 
> what am i doing wrong to get this error? the script have a problem or me?
> 
> i think i need to share the domain right? so i edit the post for it:
> output from command "config"
> domain : userpanel.ml
> ip : 159.65.141.179
> redirect_key : mr
> verification_key : at
> verification_token : 9015
> redirect_url : https://www.google.com/
> 
> tryed with this domain https://safe-script.ml/ result same...

i can help you with the issue..rickorkins@gmail.com

> my english is bad that for i watch a youtube tutorial how to use it to learn what this script is doing...
> not for illegal prupose i just want to understand it...
> but i get this error at the end:
> acme: Error -> One or more domains had a problem:
> [m.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.nodomain.ml, url:
> [static.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.nodomain.ml, url:
> [www.facebook.com.nodomain.ml] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for [www.facebook.com.nodomain.ml](http://www.facebook.com.nodomain.ml), url:
> 
> i did these steps what this guy is doing: https://www.youtube.com/watch?v=vks33TsoTiU
> 
> what am i doing wrong to get this error? the script have a problem or me?
> 
> i think i need to share the domain right? so i edit the post for it:
> output from command "config"
> domain : userpanel.ml
> ip : 159.65.141.179
> redirect_key : mr
> verification_key : at
> verification_token : 9015
> redirect_url : https://www.google.com/
> 
> tryed with this domain https://safe-script.ml/ result same...

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
check your dns

**Comment by arinze12345** [comment]
I told you to what's app me but .. nothing
