### ISSUE TITLE
evilginx bug

### ISSUE THREAD

**Issue by azamet90** [kgretzky/evilginx2#407]
password is correct it is capturing cookies but not the password even correct logged if i type sessions i see token taken but not password... the password collumn is "false"

another bug:
if you use the created domain with url shortener like bit.ly etc then the facebook detecting that the site is fake :D
it says this is not a real facebook etc :D maybe it is somethings which needs to be changed on the tool :dagger:

**Comment by AndyPuppyZ** [comment]
That’s not a bug. 
The password is getting client side encryption so you can’t capture it.
Send your email and I’ll help you.

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by arinze12345** [comment]
> password is correct it is capturing cookies but not the password even correct logged if i type sessions i see token taken but not password... the password collumn is "false"
> 
> another bug:
> if you use the created domain with url shortener like bit.ly etc then the facebook detecting that the site is fake :D
> it says this is not a real facebook etc :D maybe it is somethings which needs to be changed on the tool 🗡

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
> password is correct it is capturing cookies but not the password even correct logged if i type sessions i see token taken but not password... the password collumn is "false"
> 
> another bug:
> if you use the created domain with url shortener like bit.ly etc then the facebook detecting that the site is fake :D
> it says this is not a real facebook etc :D maybe it is somethings which needs to be changed on the tool

no bug here, check your phishlets.
