### ISSUE TITLE
o365 phishlet re-direct issue

### ISSUE THREAD

**Issue by iknowjason** [kgretzky/evilginx2#409]
I CONFIRM

I'm trying to get the o365 phishlet working and not sure if I've stumbled across an issue anyone else has had.  I have set the lures redirect url to be https://login.microsoftonline.com.  My understanding is after evilginx captures the session token cookie, it automatically re-directs the browser to the legitimate o365.  Except it isn't.  After evilginx captures the session token the victim is still logged into phishing fake URL.  I see in logs:
[19:03:51] [+++] [1] all authorization tokens intercepted!
[19:03:52] [imp] [1] redirecting to URL: https://login.microsoftonline.com (1)

But in fact browser is still stuck on fake phishing URL.  Captured session token also doesn't work with simulated adversary.  Has anyone else stumbled across this problem?  It actually worked the first time, but now every time victim browser does not automatically re-direct to legit https://login.microsoftonline.com

**Comment by iknowjason** [comment]
User error.  This is normal behavior.  Got everything working.  Awesome tool, thank you.

**Comment by Yulia1991lab** [comment]
@iknowjason can you share your email address as I need help with o365 phishlet.

Thanks

**Comment by iknowjason** [comment]
Can you either post your question below, or put your email address below?  I'll then email you.

**Comment by Yulia1991lab** [comment]
Hi please email me at yulia19@uymail.com

**Comment by EEN421** [comment]
Hey there @iknowjason... My lure is configured but my phishlet keeps rick-rolling my target instead of doing the AiTM thing and stealing creds. Would appreciate any help. I understand this is default behaviour is a parameter is missing, can't figure out what parameter... i realize this is an ancient post. Any help would be appreciated.
