### ISSUE TITLE
some one help me with installing?

### ISSUE THREAD

**Issue by devilspartner** [kgretzky/evilginx2#410]
uilding dependency tree       
Reading state information... Done
make is already the newest version (4.1-9.1ubuntu1).
git is already the newest version (1:2.17.1-1ubuntu0.4).
The following packages were automatically installed and are no longer required:
  libopts25 sntp
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root:/tmp/evilginx2# go get -u github.com/kgretzky/evilginx2
root:@:/tmp/evilginx2# cd $GOPATH/src/github.com/kgretzky/evilginx2
root:@:~/go/src/github.com/kgretzky/evilginx2# make
build flag -mod=vendor only valid when using modules
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by mapple4145** [comment]
on skype?

**Comment by devilspartner** [comment]
> on skype?

no bro.

**Comment by arinze12345** [comment]
> uilding dependency tree
> Reading state information... Done
> make is already the newest version (4.1-9.1ubuntu1).
> git is already the newest version (1:2.17.1-1ubuntu0.4).
> The following packages were automatically installed and are no longer required:
> libopts25 sntp
> Use 'apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> root:/tmp/evilginx2# go get -u github.com/kgretzky/evilginx2
> root:@:/tmp/evilginx2# cd $GOPATH/src/github.com/kgretzky/evilginx2
> root:@:~/go/src/github.com/kgretzky/evilginx2# make
> build flag -mod=vendor only valid when using modules
> Makefile:8: recipe for target 'build' failed
> make: *** [build] Error 1

I can help you out with the installation.issue..., rickorkins@gmail.com
