### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jaylampe** [kgretzky/evilginx2#414]
So basically I did everything I had to do ad I got a link for the phishing page which is https://www.facebook.login-fr.ga/0ZPA0VDP. But when I go to the link I get the error ERR_TOO_MANY_REDIRECTS. And it looks like someone is constantly trying to access the page but nobody is. 

![image](https://user-images.githubusercontent.com/57066674/68552666-af4d6580-0419-11ea-8b06-16f4bcb3cdcb.png)

![image](https://user-images.githubusercontent.com/57066674/68552677-c429f900-0419-11ea-83da-5aa9895e6238.png)

![image](https://user-images.githubusercontent.com/57066674/68552681-cb510700-0419-11ea-8e95-9deab2fa6743.png)

I don't know where the problem is coming from. Could someone help me?

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by horllste** [comment]
I used redirect to get past that

**Comment by arinze12345** [comment]
> So basically I did everything I had to do ad I got a link for the phishing page which is https://www.facebook.login-fr.ga/0ZPA0VDP. But when I go to the link I get the error ERR_TOO_MANY_REDIRECTS. And it looks like someone is constantly trying to access the page but nobody is.
> 
> ![image](https://user-images.githubusercontent.com/57066674/68552666-af4d6580-0419-11ea-8b06-16f4bcb3cdcb.png)
> 
> ![image](https://user-images.githubusercontent.com/57066674/68552677-c429f900-0419-11ea-83da-5aa9895e6238.png)
> 
> ![image](https://user-images.githubusercontent.com/57066674/68552681-cb510700-0419-11ea-8e95-9deab2fa6743.png)
> 
> I don't know where the problem is coming from. Could someone help me?

i can help you with the issue..rickorkins@gmail.com

**Comment by horllste** [comment]
your evilginx send a ssl request, the server at the other end will send some back to verify your domains and all.
