### ISSUE TITLE
Bug authzenToken

### ISSUE THREAD

**Issue by siir4ever** [kgretzky/evilginx2#418]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

Hi when you type password for second ,three time ,  what printed is : authzenToken il the apssword field , not the real password 

Thanks 
*<type_in_here>*

Thanks!
--

**Comment by Anonymoushawk** [comment]
@siir4ever  this is not a bug when you enter valid password and login successfully ,it shows you to validate from mobile and told you press its me button ,when you press it's me button you will see authzenToken in your panel.

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> Hi when you type password for second ,three time , what printed is : authzenToken il the apssword field , not the real password
> 
> Thanks
> _<type_in_here>_
> 
> ## Thanks!

i can help you with the issue..rickorkins@gmail.com
