### ISSUE TITLE
paypal phishlets not grabbing password

### ISSUE THREAD

**Issue by DSUN01** [kgretzky/evilginx2#423]
my PayPal phishlets is not grabbing username and password how can i make it to start grabbing I need help on this

**Comment by findmeskid** [comment]
You have discord I might be able to help and I need help with something you might have setup

**Comment by findmeskid** [comment]
My discord is Findmeskid#7816

**Comment by DSUN01** [comment]
i have added you on discord

**Comment by newnewuserfirebase** [comment]
Hey guys I'm having some problems to install evilginx please add me on discord dafyman#4877
