### ISSUE TITLE
acme: Error -> One or more domains had a problem:

### ISSUE THREAD

**Issue by AlvinKuruvilla** [kgretzky/evilginx2#431]
acme: Error -> One or more domains had a problem:
[m.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for m.facebook.com.xxx.xxx, url: 
[static.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for static.facebook.com.xxx.xxx, url: 
[www.facebook.com.xxx.xxx] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.facebook.com.xxx.xxx, url:
 
I have a similar issue with the Linkedin phishlet, I also made a cname record for linkedin.my_domain_name where my_domain_name is my domain name and created two nameservers that point to the IP address of where Evilginx is running
Whenever I try to enable the Linkedin phishlet this the error I keep getting
acme: Error -> One or more domains had a problem:
[www.linkedin.alvin-testbed.club] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.linkedin.alvin-testbed.club, url:
Did i miss a step
same problem I have how to fix?

_Originally posted by @azamet90 in https://github.com/kgretzky/evilginx2/issues/322#issuecomment-550270538_

**Comment by horllste** [comment]
check your dns, this is not a problem with evilginx2
