### ISSUE TITLE
acme: Error -> One or more domains had a problem: [www.linkedin.alvin-testbed.club] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.linkedin.alvin-testbed.club, url:

### ISSUE THREAD

**Issue by AlvinKuruvilla** [kgretzky/evilginx2#432]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I confirm *
Thanks!
--
I have an  issue with the Linkedin phishlet, I also made a cname record for linkedin.my_domain_name where my_domain_name is my domain name and created two nameservers that point to the IP address of where Evilginx is running and I stopped the apache2 service
Whenever I try to enable the Linkedin phishlet this the error I keep getting
acme: Error -> One or more domains had a problem:
[www.linkedin.alvin-testbed.club] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.linkedin.alvin-testbed.club, url:
Did I miss a step
Please help and thank you in advance

**Comment by horllste** [comment]
check your dns and give it time to propagate

**Comment by AlvinKuruvilla** [comment]
It has been around 24 hours and I think the dns has propagated and I am still getting the same issue: 
acme: Error -> One or more domains had a problem:
[www.linkedin.alvin-testbed.club] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.linkedin.alvin-testbed.club, url:

In configuring Evilginx I set the domain to be alvin-testbed.club which is the domain that I bought
I set the IP address on evilginx to be the IP address of my domain which in my case was 130.245.168.129 and the domain name on Evilginx to be alvin-testbed.club which is the name of the domain
I have two nameservers as shown below, and also below is my NameCheap admin panel
Admin panel:

As you can also see I have an entry for a subdomain as a CNAME Record
*Note my hostname for the Linkedin phishlet on Evilginx is linkedin.alvin-testbed.club which is why I put that as the value for the cname record. Could the issue be that my host for the cname record, *,  is the same as one of my A Records ?

<img width="825" alt="Screen Shot 2019-12-08 at 9 31 29 AM" src="https://user-images.githubusercontent.com/46870885/70390941-beceb880-199d-11ea-9b7e-f5c347187fd9.png"> 

Nameserver Panel 
<img width="890" alt="Screen Shot 2019-12-08 at 9 32 33 AM" src="https://user-images.githubusercontent.com/46870885/70390973-02292700-199e-11ea-93af-cdb8b9fc98bd.png">
**Note: the IP address 130.245.169.51 is the IP address of the aws ubuntu machine where Evilginx is present

Please let me know what I did wrong

And thank you in advance for any help, my apologies for the lengthy comment, this is the first time I am doing something like this

**Comment by NicoBalle** [comment]
OP have you found a fix for this issue? I am currently having this problem and i'm trying to solve it.
