### ISSUE TITLE
Renew Lets Encrypt certificate

### ISSUE THREAD

**Issue by pawp81** [kgretzky/evilginx2#434]
What is the recommended way to renew the certificate issued by Lets Encrypt to evilginx created site?

**Comment by Zhenyoker** [comment]
https://github.com/kgretzky/evilginx2/issues/403

**Comment by AndyPuppyZ** [comment]
This issue was resolved in the later versions of Evilginx, you have to compile the code from source(Binary are not updated).

> #403

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
just inbox me for solution chieflyx@gmail.com

**Comment by pycoder3376** [comment]
i am facing problem while generating ssl certificate from letsenencrpyt acme error 400:

**Comment by horllste** [comment]
Are you certain you set the right DNS record for the domain?

**Comment by arinze12345** [comment]
> i am facing problem while generating ssl certificate from letsenencrpyt acme error 400:

i can help you with your problem...rickorkins@gmail.com

**Comment by arinze12345** [comment]
> What is the recommended way to renew the certificate issued by Lets Encrypt to evilginx created site?

i can help you with your problem...rickorkins@gmail.com
