### ISSUE TITLE
install evilginx 2.3.2

### ISSUE THREAD

**Issue by diewithurlie** [kgretzky/evilginx2#438]
hi, can seomeone share to me how to install the new release evilginx 2.3.2

**Comment by diewithurlie** [comment]
why become like this 

root@ubuntu-s-1vcpu-1gb-sgp1-01:~/go/src/github.com/kgretzky/evilginx2# make
build flag -mod=vendor only valid when using modules
make: *** [Makefile:8: build] Error 1

**Comment by ManjosSerj** [comment]
I have the same error to

**Comment by horllste** [comment]
Get TeamViewer then send me your email

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
google video solution but if still can't find you way, inbox me chieflyx@gmail.com

**Comment by arinze12345** [comment]
> hi, can seomeone share to me how to install the new release evilginx 2.3.2

i can help you with your problem...rickorkins@gmail.com

**Comment by arinze12345** [comment]
> I have the same error to

i can help you with your problem...rickorkins@gmail.com
