### ISSUE TITLE
evilginx 2 OPTIONS method

### ISSUE THREAD

**Issue by CraftedCat** [kgretzky/evilginx2#439]
Request URL: https://some.targett.info/wallet/e6f4020e-2c38-4fdd-8ab9-77174c357852?api_code=1770d5d9-bcea-4d28-ad21-6cbd5be018a8&ct=1576749687200&format=json&resend_code
Request Method: OPTIONS
Status Code: 302 Found
Remote Address: 10.10.10.10:443
Referrer Policy: no-referrer-when-downgrade

Responce Headers:
Connection: close
Content-Type: text/html
Location: https://www.youtube.com/watch?v=dQw4w9WgXcQ
Transfer-Encoding: chunked

how to fix, OPTIONS query?

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
inbox me chieflyx@gmail.com

**Comment by carlelmer1954** [comment]
> contact me on telegram if u guys need any help @IAmBecomeDeath

Pls bro can you give me your direct Email where I reach you....tried contacting you on telegram but don’t let me mssg you don’t know why....I need you help....can you help me out with gmail phishlets
