### ISSUE TITLE
quesion:evilginx2 localhost

### ISSUE THREAD

**Issue by azamet90** [kgretzky/evilginx2#441]
is there any tutorial for using evilginx2 from localhost, with custom domain and without port forwarding on the router maybe using tunneling?

**Comment by azamet90** [comment]
sorry i posted to wrong place :@

**Comment by gregleon** [comment]
https://breakdev.org/evilginx-2-1-the-first-post-release-update/

**Comment by azamet90** [comment]
> https://breakdev.org/evilginx-2-1-the-first-post-release-update/

this is not the answer to my question

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
this can be fix inbox chieflyx@gmail.com
