### ISSUE TITLE
o365 Phishlet not bypassing MFA, Outlook Phishlet not catching credentials

### ISSUE THREAD

**Issue by ironc0in** [kgretzky/evilginx2#444]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

**I CONFIRM**

Thanks!
--
<img width="641" alt="Screen Shot 2019-12-24 at 5 32 50 PM" src="https://user-images.githubusercontent.com/16161930/71426731-b780fd80-2673-11ea-8e86-d0b082aa7bfc.png">

----Using v2.3.3----
When I use the "**Outlook**" phishlet, it bypasses DUO MFA yet does not catch any credentials in the sessions.
With the exact same setup, when I use the "**O365**" phishlet, it catches the username/password but fails to load the MFA page with the error in the screenshot.

Neither phishlet _yaml_ files have been modified. There's no typical federations url page specific to the company with DUO. Duo security uses the generic URL in the url bar (see screenshot).

Not sure how to proceed here. Any help would be great !

**Comment by solomon-ey** [comment]
write me on chieflyx@gmail.com
