### ISSUE TITLE
error in enabling phislets error 400 no emvedded jwk in jws header

### ISSUE THREAD

**Issue by adisunshine1978** [kgretzky/evilginx2#445]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I am having the following error enabling phislets
![image](https://user-images.githubusercontent.com/59288411/71581061-908e5580-2ad1-11ea-81d0-60fad5dbba19.png)
*

Thanks!
--

**Comment by Acebond** [comment]
Your not alone I'm having the same issues. Anyone know of a solution?

**Comment by horllste** [comment]
Pm me

**Comment by Acebond** [comment]
I ended up just using an older version and everything worked. 

I did discover after getting it working that I'd forgotten to open up 53 UDP/TCP in EC2 so I'm not sure if that was causing issues.

**Comment by 3vall** [comment]
https://github.com/kgretzky/evilginx2/issues/375#issuecomment-573346433

**Comment by devil-show** [comment]
same problem here how to solve

**Comment by devil-show** [comment]
> Pm me

hy can u know how to solve this

**Comment by adisunshine1978** [comment]
The guy copied on this email can help....

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
inbox me chieflyx@gmail.com

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> *I am having the following error enabling phislets
> ![image](https://user-images.githubusercontent.com/59288411/71581061-908e5580-2ad1-11ea-81d0-60fad5dbba19.png)
> *
> 
> ## Thanks!

i can help you with your problem...rickorkins@gmail.com

**Comment by arinze12345** [comment]
> Your not alone I'm having the same issues. Anyone know of a solution?

i can help you with your problem...rickorkins@gmail.com

**Comment by arinze12345** [comment]
> same problem here how to solve

i can help you with your problem...rickorkins@gmail.com
