### ISSUE TITLE
 I need help [Google Phishlets]

### ISSUE THREAD

**Issue by Lauriannn** [kgretzky/evilginx2#446]
Hi everyone my Google phishlets don't work 100% and I don't know why.
 If anyone has a solution, I am interested.
Google shows me this error:

"This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

I eat frogs so i don't speak english perfectly, sorry for spelling. (Si un français peut m'aider ducoup sa m'aiderais beaucoup)
My email : lauriannn@protonmail.com
![1](https://user-images.githubusercontent.com/57778084/71629903-4a83df80-2c00-11ea-9af9-148037f79180.png)
![2](https://user-images.githubusercontent.com/57778084/71629822-d6e1d280-2bff-11ea-80dc-73297e42e73c.png)
![3](https://user-images.githubusercontent.com/57778084/71629826-d9442c80-2bff-11ea-991d-ebe072465f94.png)
![4](https://user-images.githubusercontent.com/57778084/71629829-dc3f1d00-2bff-11ea-82ed-93c0e1ecf96a.png)
![5](https://user-images.githubusercontent.com/57778084/71629831-df3a0d80-2bff-11ea-9d21-0cc668c0cad2.png)

**Comment by VVaReD** [comment]
same error with Modlishka, maybe google security

**Comment by horllste** [comment]
buy the solution

**Comment by VVaReD** [comment]
the question is...
the solution exists?

**Comment by horllste** [comment]
yes

**Comment by VVaReD** [comment]
yes?!? the solution exists? really?

**Comment by horllste** [comment]
yes, the solution exist

**Comment by Lauriannn** [comment]
Yes the solution exist but a lot of people try to sell me the phishlets but it is to learn and not to hack people so i will not pay more people ask me $ and another person $ 5000 lol

**Comment by VVaReD** [comment]
5000 $ ? lool

thanks for your reply, i will work on it

**Comment by lofthotel** [comment]
please add for talk about phihilet salamalecu @ jabb . im

**Comment by Lauriannn** [comment]
i have paypal phishlets if someone can exchange it for google phishlets !
My mail : lauriannn@protonmail.com
