### ISSUE TITLE
JQuery support 

### ISSUE THREAD

**Issue by Mattie777** [kgretzky/evilginx2#447]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*<I CONFIRM>*

Thanks!
--
Hello 
I have very small small question. Does latest version of Evilginx 2 support JQuery language ?
and do i have to first declare <script> src ="jquery" </script> in order to access it ? Or i can just start typing the code ? 

Thank you .

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
inbox me chieflyx@gmail.com
