### ISSUE TITLE
Parsing arguments from: lures edit og_title

### ISSUE THREAD

**Issue by nicoandmee** [kgretzky/evilginx2#449]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
I CONFIRM 

I was playing around with this tool and I've noticed I can't seem to set og_title to anything other than a single value. 

For instance: `lures edit og_title 3 Outlook` works fine.

However, `lures edit og_title 3 Outlook - free personal email and calendar from Microsoft` fails with the following error: [err] lures: incorrect number of arguments

I'm guessing maybe this is how to parsing the arguments is done, and it would be nice to be able to pass in a title that is more than one string. 

Thanks!
--

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by solomon-ey** [comment]
inbox me for solution chieflyx@gmail.com
