### ISSUE TITLE
Phishlets

### ISSUE THREAD

**Issue by h3xp1017** [kgretzky/evilginx2#45]
Hello @kgretzky, thank you for that great job, the project is amazing. Is there any documentation or guide on phishlets? I didn't found any explanation on parameters such as what is meaning of "is_landing" and why in ex. facebook.yml "phish_sub" and "orig_sub" are the same and in reddit.yml is not?

**Comment by 001mofo** [comment]
Hi h3xp1017,

Kuba provided quite a bit of information on this project in his blog post at [BreakDev](https://breakdev.org/evilginx-2-next-generation-of-phishing-2fa-tokens/)  Please have a look there, the blog post  answers your questions quite throughly. 

Hope this helps :)
