### ISSUE TITLE
Amazon capturing tokens only on desktop

### ISSUE THREAD

**Issue by marsi159** [kgretzky/evilginx2#451]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
*I confirm*
### ** Hello, I successfully enabled amazon Phishlets, its capturing only the email+password on mobile but it capturing the tokens too on desktop. is there anything I could do to fix this ? I use the default amazon phishlet on evilginx2**

![Screen Shot 2020-01-07 at 16 36 33](https://user-images.githubusercontent.com/59626311/71931778-8e309900-316c-11ea-97c7-b268838faea0.png)

Thanks!
--

**Comment by horllste** [comment]
Make your own phishlet

**Comment by marsi159** [comment]
> Make your own phishlet

very helpful! thanks!

**Comment by Herostere** [comment]
Hi @marsi159 

When I enable my amazon phislet only the Email can be write. How are you doing to have both email and password on the same page?
Thank you.

**Comment by VVaReD** [comment]
i have make my own amazon phislet, 
I don't know if it's linked, but each session captured and linked has an ip address ... (the address of our evilginx proxy), otherwise the cookie will not be validated and will ask for the password again. you must configure your server to use it in proxy with the captured session cookie.

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by symingtonwei** [comment]
> 我已经制作了自己的亚马逊phislet，
> 我不知道它是否已链接，但是捕获和链接的每个会话都有一个ip地址...（我们的evilginx代理的地址），否则cookie不会通过验证并要求再次输入密码。您必须将服务器配置为与捕获的会话cookie一起在代理中使用。



> 我已经制作了自己的亚马逊phislet，
> 我不知道它是否已链接，但是捕获和链接的每个会话都有一个ip地址...（我们的evilginx代理的地址），否则cookie不会通过验证并要求再次输入密码。您必须将服务器配置为与捕获的会话cookie一起在代理中使用。

Did you modify Amazon's yaml file?  It is difficult for evilginx to obtain Amazon cookies and passwords.
