### ISSUE TITLE
I need help [Google Phishlets]

### ISSUE THREAD

**Issue by Lauriannn** [kgretzky/evilginx2#455]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*< I CONFIRM >*

Thanks!
--
Hi everyone my Google phishlets don't work 100% and I don't know why.
If anyone has a solution, I am interested.
Google shows me this error:

"This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

I eat frogs so i don't speak english perfectly, sorry for spelling. (Si un français peut m'aider ducoup sa m'aiderais beaucoup)
My email : lauriannn@protonmail.com

![](https://user-images.githubusercontent.com/57778084/71629903-4a83df80-2c00-11ea-9af9-148037f79180.png)
![](https://user-images.githubusercontent.com/57778084/71629822-d6e1d280-2bff-11ea-80dc-73297e42e73c.png)
![](https://user-images.githubusercontent.com/57778084/71629826-d9442c80-2bff-11ea-991d-ebe072465f94.png)
![](https://user-images.githubusercontent.com/57778084/71629829-dc3f1d00-2bff-11ea-82ed-93c0e1ecf96a.png)
![](https://user-images.githubusercontent.com/57778084/71629831-df3a0d80-2bff-11ea-9d21-0cc668c0cad2.png)

**Comment by solomon-ey** [comment]
inbox me chieflyx@gmail.com

**Comment by mrWhiteCrow** [comment]
How did you solve this problem? I got the same error message using Modlishka.. Maybe gmail is implementing some new security features.

**Comment by horllste** [comment]
Yes Facebook does implement new security features, you have to bypass it

**Comment by danieldarkna1** [comment]
> Yes Facebook does implement new security features, you have to bypass it

Hi horllste..

can you please help with using for facebook? I am getting encrypted passswords for mobile

**Comment by mrWhiteCrow** [comment]
What about google?

**Comment by horllste** [comment]
Google uses protection too but it's possible to bypass

**Comment by mrWhiteCrow** [comment]
> Google uses protection too but it's possible to bypass

Can you tell me more about this?

**Comment by horllste** [comment]
What exactly would you like to know?

**Comment by Lauriannn** [comment]
it's possible to bypass google security i know someone who is actually

**Comment by VVaReD** [comment]
I develop the phishlets, but I have a problem with the checkconnection (accounts.youtube.com), how to put youtube and google in proxy at the same time, can be used 2 phishlets separately? one for google, one for youtube for checkconnection?

**Comment by lofthotel** [comment]
> 
> 
> I develop the phishlets, but I have a problem with the checkconnection (accounts.youtube.com), how to put youtube and google in proxy at the same time, can be used 2 phishlets separately? one for google, one for youtube for checkconnection?
> or is there another solution with evilginx?

add for talk  fullzzcc @ jabb . im

**Comment by Anonymoushawk** [comment]
Gmail solution available contact = anonymoushawk0@protonmail.com

**Comment by Lauriannn** [comment]
Lol you sell the solution 700$ but according to him it is "reasonable"

**Comment by VVaReD** [comment]
700$? reasonable? LOOOL really? 
where has the community that favored mutual aid?, rather than money ..

**Comment by horllste** [comment]
Just like no one gave me any hint while I was looking for the solution, I have no hints to give but if you work harder, read more on man in the middle attack, you will figure it out

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> _< I CONFIRM >_
> 
> ## Thanks!
> Hi everyone my Google phishlets don't work 100% and I don't know why.
> If anyone has a solution, I am interested.
> Google shows me this error:
> 
> "This browser or app may not be secure. Learn more
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."
> 
> I eat frogs so i don't speak english perfectly, sorry for spelling. (Si un français peut m'aider ducoup sa m'aiderais beaucoup)
> My email : [lauriannn@protonmail.com](mailto:lauriannn@protonmail.com)
> 
> ![](https://user-images.githubusercontent.com/57778084/71629903-4a83df80-2c00-11ea-9af9-148037f79180.png)
> ![](https://user-images.githubusercontent.com/57778084/71629822-d6e1d280-2bff-11ea-80dc-73297e42e73c.png)
> ![](https://user-images.githubusercontent.com/57778084/71629826-d9442c80-2bff-11ea-991d-ebe072465f94.png)
> ![](https://user-images.githubusercontent.com/57778084/71629829-dc3f1d00-2bff-11ea-82ed-93c0e1ecf96a.png)
> ![](https://user-images.githubusercontent.com/57778084/71629831-df3a0d80-2bff-11ea-9d21-0cc668c0cad2.png)

i can help you with your problem...rickorkins@gmail.com

**Comment by VVaReD** [comment]
Je suis Francais pour ma part je n' est pas dépassé le checkconnection..

**Comment by arinze12345** [comment]
quel problème avez-vous sur evilginx2 ...... discutez-moi sur Whatsapp
(929) 483-1665

**Comment by Lauriannn** [comment]
> Je suis Francais pour ma part je n' est pas dépassé le checkconnection..

Tu as le même problème que moi ?

**Comment by VVaReD** [comment]
> > Je suis Francais pour ma part je n' est pas dépassé le checkconnection..
> 
> Tu as le même problème que moi ?

je ne pense pas, pour ma part mon phislets ne marche pas du tout, le checkconnection ne valide pas ma connection, certainement parcequ il faut que je créé un server evilginx youtube, je n' en suis pas encore sure...

**Comment by arinze12345** [comment]
Je peux vous aider avec ça ...

**Comment by arinze12345** [comment]
+12565680665.. WhatsApp me

**Comment by Lauriannn** [comment]
arinze12345 sell the phishlets 1500€ LOOOOOOOOOL 
![8B7141B5-838E-4CA0-B9F4-6810A4E38682](https://user-images.githubusercontent.com/57778084/73596760-8c68b400-4525-11ea-8e7b-cb5bfbdbedc1.png)

**Comment by VVaReD** [comment]
LOOOOLLLLL 1500 oui biensur faut pas déconné

**Comment by arinze12345** [comment]
That idiot is a very big liar.... what I asked to sell for him is my own
evilginx2...which allows Gmail phishlet to work without any issues...

**Comment by arinze12345** [comment]
He wants to defame my reputation publicly...if you knew the problem, why
don't you solve it yourself....I told you..how much I render my service, I
never extorted any money from you,,and also I asked you how much you are
willing to pay...and you told me bad word's...and you never screenshoted
all the chats and conversation we had...you just took part of it.., and
posted it on GitHub..., You really are a very wicked soul,,and may God
judge you for that...,,and also never forget that I paid someone to teach
me everything...Fool...

**Comment by Lauriannn** [comment]
> LOOOOLLLLL 1500 oui biensur faut pas déconné
Et encore ptdrrr y’en a un y vendait sa 5k et c’est pas une blague les gens croient qui vendent une M16

**Comment by horllste** [comment]
lol, lies everywhere

**Comment by VVaReD** [comment]
> > LOOOOLLLLL 1500 oui biensur faut pas déconné
> > Et encore ptdrrr y’en a un y vendait sa 5k et c’est pas une blague les gens croient qui vendent une M16

grave, toute maniére la communauté hack n' est pus ce qu' elle etais, maintenant c' est pognon et pognon rien que le pognon, pendant ce temp la...le créateur d evilginx ne gagne rien, c' est lui qui devrais en gagné pour le vrai travail accompli....
