### ISSUE TITLE
#PWD_BROWSER password issue when clients are using mobile devices.

### ISSUE THREAD

**Issue by twinkette** [kgretzky/evilginx2#459]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

I CONFIRM!!!

Thanks!
--

I've noticed that, with all templates, if I login on the laptop then Evilgnix grabs the username, password, and tokens. However, on a mobile device, for the password I get something like:

#PWD_BROWSER:5:1578785883917:AcNQAPgbyE7f+Ut3CQ8/MV1ezPVNOiQf5AemxkhjzRuAjW1dwBPo6QFmD+q44oUR9Vtd6Ju2M8Tyuj0IGJk+xMHcNjRdRf2JPpRtMct5Z5vRdqPgIt8ki94jPHLV+x7HjARnMVYjMiiw87U=

Can anyone please explain a) why this is happening and b) if there is a solution?

**Comment by solomon-ey** [comment]
inbox me for solutions chieflyx@gmail.com

**Comment by spam441** [comment]
contact me on telegram if u guys need any help @iambecomedeath

**Comment by horllste** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> I CONFIRM!!!
> 
> ## Thanks!
> I've noticed that, with all templates, if I login on the laptop then Evilgnix grabs the username, password, and tokens. However, on a mobile device, for the password I get something like:
> 
> #PWD_BROWSER:5:1578785883917:AcNQAPgbyE7f+Ut3CQ8/MV1ezPVNOiQf5AemxkhjzRuAjW1dwBPo6QFmD+q44oUR9Vtd6Ju2M8Tyuj0IGJk+xMHcNjRdRf2JPpRtMct5Z5vRdqPgIt8ki94jPHLV+x7HjARnMVYjMiiw87U=
> 
> Can anyone please explain a) why this is happening and b) if there is a solution?

In mobile browser auth protection, try and build the phishlet yourself using the target mobile platform, you will figure it out

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> I CONFIRM!!!
> 
> ## Thanks!
> I've noticed that, with all templates, if I login on the laptop then Evilgnix grabs the username, password, and tokens. However, on a mobile device, for the password I get something like:
> 
> #PWD_BROWSER:5:1578785883917:AcNQAPgbyE7f+Ut3CQ8/MV1ezPVNOiQf5AemxkhjzRuAjW1dwBPo6QFmD+q44oUR9Vtd6Ju2M8Tyuj0IGJk+xMHcNjRdRf2JPpRtMct5Z5vRdqPgIt8ki94jPHLV+x7HjARnMVYjMiiw87U=
> 
> Can anyone please explain a) why this is happening and b) if there is a solution?
i can help you with your problem...rickorkins@gmail.com

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> I CONFIRM!!!
> 
> ## Thanks!
> I've noticed that, with all templates, if I login on the laptop then Evilgnix grabs the username, password, and tokens. However, on a mobile device, for the password I get something like:
> 
> #PWD_BROWSER:5:1578785883917:AcNQAPgbyE7f+Ut3CQ8/MV1ezPVNOiQf5AemxkhjzRuAjW1dwBPo6QFmD+q44oUR9Vtd6Ju2M8Tyuj0IGJk+xMHcNjRdRf2JPpRtMct5Z5vRdqPgIt8ki94jPHLV+x7HjARnMVYjMiiw87U=
> 
> Can anyone please explain a) why this is happening and b) if there is a solution?


i can help you with your problem...rickorkins@gmail.com

**Comment by AndyPuppyZ** [comment]
Facebook are doing client side encryption for the mobile version, so the password will be encrypted then sent with POST request(with the email), Evilginx is man in the middle so it’s capturing the Network traffic and in this case it’s the encrypted password and the plain text email.

You need to inject JS to the phishing page to capture the password manually.
Simple example can be: if the user clicks/touch on the login button, grab the password filed and send it to your server.

Send me email - abo_andy@hotmail.com
