### ISSUE TITLE
I NEED IDEA !

### ISSUE THREAD

**Issue by muratsnkl** [kgretzky/evilginx2#460]
Hello Everyone.  i need some help. I have no problem with the work of Evilginx. I just want an idea. I am running Evilginx in popup. After entering the necessary information, which file should I intervene so that the popup closes?

**Comment by horllste** [comment]
Not clear enough, some pictures will help

**Comment by arinze12345** [comment]
> Hello Everyone. i need some help. I have no problem with the work of Evilginx. I just want an idea. I am running Evilginx in popup. After entering the necessary information, which file should I intervene so that the popup closes?

i can help you with your problem...rickorkins@gmail.com
