### ISSUE TITLE
i have problems with a phishlet 

### ISSUE THREAD

**Issue by gelabertdionisio432** [kgretzky/evilginx2#461]
i have a phishlet that is not working on this evilginx version 
go get -u github.com/kgretzky/evilginx2

i have find another version that is working this is the version 

go get -u github.com/hash3liZer/evilginx2

but now when i install it i get this error :
acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

CAN PLEASE ANYONE HELP ME WITH THIS 

THIS IS MY EMAIL: gelabert.dionisio432@gmail.com

**Comment by arinze12345** [comment]
> i have a phishlet that is not working on this evilginx version
> go get -u github.com/kgretzky/evilginx2
> 
> i have find another version that is working this is the version
> 
> go get -u github.com/hash3liZer/evilginx2
> 
> but now when i install it i get this error :
> acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
> 
> CAN PLEASE ANYONE HELP ME WITH THIS
> 
> THIS IS MY EMAIL: [gelabert.dionisio432@gmail.com](mailto:gelabert.dionisio432@gmail.com)

i can help you out with it ...rickorkins@gmail.com
