### ISSUE TITLE
anyway to do this?

### ISSUE THREAD

**Issue by horllste** [kgretzky/evilginx2#463]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*i confirm*

Thanks!
--

Am confused regarding replacing the JavaScript or striping it

Am working on a phishlet, it has several js files, the js function I want to remove is in a file with other js functions.

I wish you would please point out to me

1, replacing the whole js file. 
I tried the evilginx replace function, I set it to replace the js file with empty link but it doesn't work.

2, replacing some JS functions in a js file.

Another thing baffling me is if a sub domain is like this... 

us.en.free.domain.com

How do I configure a subdomain like that in a phishlet. 

Thanks, I wish and hope you'd answer my questions. 
Thanks

**Comment by arinze12345** [comment]
> #### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID
> * I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
> * I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
> * I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
> * I am not trying to set up a domain on FreeNOM (also read the sentence above again).
> * I am not a robot.
>   _(Sorry, if you are an adult and a professional and you had to read this.)_
> 
> Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:
> 
> _i confirm_
> 
> ## Thanks!
> Am confused regarding replacing the JavaScript or striping it
> 
> Am working on a phishlet, it has several js files, the js function I want to remove is in a file with other js functions.
> 
> I wish you would please point out to me
> 
> 1, replacing the whole js file.
> I tried the evilginx replace function, I set it to replace the js file with empty link but it doesn't work.
> 
> 2, replacing some JS functions in a js file.
> 
> Another thing baffling me is if a sub domain is like this...
> 
> us.en.free.domain.com
> 
> How do I configure a subdomain like that in a phishlet.
> 
> Thanks, I wish and hope you'd answer my questions.
> Thanks

i can help you out ...rickorkins@gmail.com
