### ISSUE TITLE
js_inject: String interpolation bug

### ISSUE THREAD

**Issue by nicoandmee** [kgretzky/evilginx2#464]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!
--

It seems there is an issue with parsing the JS inject parameter in the yaml file. Specifically, if one uses string backtick syntax which is standard ES6 and common practice for any JavaScript programmer, the code will not be executed as expected- I spent a few hours banging my head against the wall trying to understand what was going on until I realized internally evilginx2 is performing some kind of sanitization on the JavaScript code that gets injected. TLDR Don't use string interpolation for ES6- use stone age techniques.

**Comment by kgretzky** [comment]
Thanks!

I think you may need to check with YAML documentation on how to properly escape backticks. It should be doable.
