### ISSUE TITLE
How can I add a http header?

### ISSUE THREAD

**Issue by miroschnichenkoMax** [kgretzky/evilginx2#49]
While I'm opening my phishlet I'm getting such errors. 

> Failed to load https:/external.domain: The 'Access-Control-Allow-Origin' header has a value 'https:/external.domain' that is not equal to the supplied origin. Origin 'https://my.domain' is therefore not allowed access.

So how can I add header "Access-Control-Allow-Origin" to a response in order to let browser fetch data from different origins?

**Comment by kgretzky** [comment]
You need to add this hostname to `proxy_hosts` and it will automatically strip the CSP headers.

**Comment by CyberTheReape** [comment]
I wrote some things about evilginx 1 but did not answer @kgretzky 
I try on my own account with evilginx 1...everything works fine but when I want to change the password there is 2 step verification on the login page that opens..when I want to change the password with another google account, I just write the password of my google account on the login page and go to the password change page...but I'm trying to change the password of my google account that I entered with EvilGinx, but google want 2-step phone verification on the login page..

How can I change the password of my google account that I open with evilginx ? please hepl me @kgretzky

**Comment by kgretzky** [comment]
Sorry, based on this info I have no way of figuring out the cause of the issue.
