### ISSUE TITLE
Can't update to 2.4.0

### ISSUE THREAD

**Issue by xyloganiste** [kgretzky/evilginx2#497]
I'm trying to update to 2.4.0
Go is up to date (go version go1.15.2 linux/amd64)
When I'm executing this request: `git clone github.com/kgretzky/evilginx2`, I get this message: 
fatal: repository 'github.com/kgretzky/evilginx2' does not exist

What I am missing?

Thank you

**Comment by kgretzky** [comment]
Thanks I've fixed the command in the README.

It should've been:
```
git clone https://github.com/kgretzky/evilginx2.git
```

**Comment by lacylau157** [comment]
Hi, can you pleas help me with the updated way you fix this issue i am stock here my self, when i run the code it says command not found
