### ISSUE TITLE
Developer mode: duplicate issuer/serial

### ISSUE THREAD

**Issue by efenex** [kgretzky/evilginx2#50]
Been playing with the new developer mode, and kept getting certificate errors SEC_ERROR_REUSED_ISSUER_AND_SERIAL

Looked at the code a bit, and if I understood correctly you re-use the serial number from the upstream cert?

Did a minor patch, re-using your CA cert serial generation code to have random serials to work around this issue, which works a lot smoother for me:

```
diff --git a/core/certdb.go b/core/certdb.go
index 01d7e53..997f195 100644
--- a/core/certdb.go
+++ b/core/certdb.go
@@ -314,8 +316,14 @@ func (d *CertDb) SignCertificateForHost(host string, phish_host string, port int
        if srvCert == nil {
                return nil, fmt.Errorf("failed to get TLS certificate for: %s", host)
        } else {
+               serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
+               serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
+               if err != nil {
+                       return nil, err
+               }
+
                template = x509.Certificate{
-                       SerialNumber:          srvCert.SerialNumber,
+                       SerialNumber:          serialNumber,
                        Issuer:                x509ca.Subject,
                        Subject:               srvCert.Subject,
                        NotBefore:             srvCert.NotBefore,
```

Not sure what the consequences of this approach are, or what the reasoning was of re-using the original serial - first time playing with this tool so I may just be doing things the wrong way.

Let me know if you'd like me to fork and create a PR.

P.S.: any IRC/Slack channel for evilginx?

**Comment by kgretzky** [comment]
Thank you very much for pointing out this issue!

I will take a look into that serial number thing. Indeed the serial number is retrieved from the legitimate website and probably it is a bad idea if the hostname doesn't match.

I will test your patch and let you know!
Thanks again - this is a very good bug report.

**Comment by kgretzky** [comment]
Thanks for the PR!

Do you know the steps to reproduce this issue? I've tried hard to see this error pop up and I couldn't.
Tested on the latest version of Firefox and tested with Twitter phishlet. Opened both phishing URL and `twitter.com`, double-checked the certificates and could indeed tell both certificate serial numbers match for the phishing hostname and the legitimate one, but still no error popped up.

Do you have some additional security settings enabled, which may be triggering that? Also tested in Chrome and no error popped up.

I will for sure merge your PR as it makes sense to generate a random serial number. Just wanted to see that error first to confirm the fix.

**Comment by kgretzky** [comment]
Fixed with @efenex patch https://github.com/kgretzky/evilginx2/commit/f03780baf51d27ca8ce50587f750b161ec27fd5f
