### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by physics-sp** [kgretzky/evilginx2#500]
Hello!
I have been working on a phishlet and notice some CORS issues.

I'm going to talk about google in this particular example, but the issue of course applies to other domains as well.

This is how it normally works:  
The `accounts.google.com` domain sends an authenticated POST request to the `play.google.com` domain.

Request:
```
POST /log?format=json&hasfast=true HTTP/1.1
Host: play.google.com
Origin: https://accounts.google.com
Content-Length: 494
Cookie: ...

...
```

Response:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://accounts.google.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Playlog-Web
Content-Length: 131

...
```

Notice that the `play.google.com` is allowing `accounts.google.com` to read the response of the authenticated request.

This is what is being returned by evilginx (version 2.4.0 btw).

```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Playlog-Web
Access-Control-Allow-Origin: *
Content-Length: 131

...
```

The issue is that the combination of the star (*) as the origin with the allow credential as true is not valid. (More info about that [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Credentialed_requests_and_wildcards))  
This means that `accounts.google.com` is unable to read the response of `play.google.com`.   

This is the error that you get on Firefox:

```
Access to XMLHttpRequest at 'https://play.evil.com/log?format=json&hasfast=true' from origin 'https://accounts.evil.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

The fix is to instead of specifying the star (*) as the origin, just include actual origin.  

[This](https://github.com/hash3liZer/evilginx2/commit/d1ce887e3412aab73ca331dd1bd8bf2f15ae7752) might be helpful.

Hope I was clear, let me know if you have any issues.  
Thank you in advance!

**Comment by physics-sp** [comment]
Update: I have submitted a PR: https://github.com/kgretzky/evilginx2/pull/501

**Comment by An0nUD4Y** [comment]
@physics-sp , Thanks For the PR , I will test it soon to see if it works or not !

**Comment by An0nUD4Y** [comment]
@physics-sp , Is it fixing the Google phishlet issues as well ???

**Comment by physics-sp** [comment]
Well.. it fixes that particular issue, but google implemented quite a few protections against this kind of techniques, so is really far away from "fixing" the phishlet.
It just fixes CORS issues in general 😃

**Comment by An0nUD4Y** [comment]
@physics-sp , Still it's great help for those who stucked at this issue.
Btw , I have a testing  link for working google phishlet, I tried to read the changes been made in js functions to make that phishlet work and to understand the implementation against those protections added by Google. But I failed to do so. Let me know if you wanna try.

**Comment by physics-sp** [comment]
Sure thing! I was actually working on that, and that's how I found this CORS thing haha

**Comment by kgretzky** [comment]
Thank you for reporting!
I've pushed a possible fix. Can you pull from `master` and let me know if the issue was resolved?

Fix: https://github.com/kgretzky/evilginx2/commit/2cef350d26090b1ac76ef9d0f658e7c83c2d285e

**Comment by physics-sp** [comment]
I added a comment in the commit (hope you will consider it), besides that, is great and the fix works correctly 😄

**Comment by kgretzky** [comment]
Thanks! You have a valid point here.
I made a tweak to the fix here according to your suggestions: https://github.com/kgretzky/evilginx2/commit/c8e17beeb9c88f81619f0f391f092a8e4282276b

**Comment by physics-sp** [comment]
Nice!  

If `replaceHostWithPhished` fails (meaning that the domain wasn't in the proxy_hosts, right?) we should probably also print a warning to the user, because _maybe_ it should be added to the phishlet.  

Also, I would delete [this](https://github.com/kgretzky/evilginx2/blob/c8e17beeb9c88f81619f0f391f092a8e4282276b/core/http_proxy.go#L617) line due to what I mention before [here](https://github.com/kgretzky/evilginx2/commit/2cef350d26090b1ac76ef9d0f658e7c83c2d285e#r42529341), there is no real need to force the domain to accept credentials with CORS requests and by doing that we break some implementations.

**Comment by kgretzky** [comment]
I can't remember why I had this line there in the first place, but I think it was to make sure that all AJAX requests send attached cookies, which will be intercepted by Evilginx. I haven't found any proof yet that this header may be causing issues.

For the warning about `proxy_hosts` I think it is not needed. The user can decided what to do with it after the warning is displayed.

**Comment by physics-sp** [comment]
I'm not sure I am reading the code correctly, but if the `Access-Control-Allow-Origin` header has a "valid" domain (`Parse` is successful) but the domain is not present in `proxy_hosts` (`replaceHostWithPhished` fails), I think no warning will be displayed to the user

**Comment by kgretzky** [comment]
Yes, correct. There will be no warning. I don't want to send out warnings for messages, which may not be relevant. Makes sense probably to print such messages as debug output, since it should be used only for phishlet devs.

**Comment by physics-sp** [comment]
True
Okay then, that's' it 😄

**Comment by kgretzky** [comment]
Thanks for your help! It is the first time I've had such meaningful conversation about suggested fixes here 😛 Really appreciate the feedback you provided.

**Comment by physics-sp** [comment]
I'm glad I could help 😄
