### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by bojanrodic** [kgretzky/evilginx2#506]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I need to understand why websockets are not forwarded, when i turn on evilginx, packets that are websockets are not forwarded good.
What i am doing wrong, basically, it is login problem, it will not show login option on website because it upgraded to websockets.
What i am doing wrong?
Sorry if question is stupid, but i researched about it and did not found proper answer.
If someone can give me some hints i will appreciate that.

**Comment by kgretzky** [comment]
Proxying of websockets is not implemented in evilginx. That's why they are not forwarded.

**Comment by nrmv** [comment]
When will it be implemented?
