### ISSUE TITLE
web page not safe !

### ISSUE THREAD

**Issue by CyberTheReape** [kgretzky/evilginx2#51]
hei...  @kgretzky 

I have read the evilginx 2.1 installation instructions from breakdev.org ..I am sure that everything has been done properly....I'm running evilginx 2 .1 in developer mode .but when I enter my site it says it's not safe.
I think there is a certificate error..now I'm sending you a screenshot of the actions I have made to you..

![2018-09-11 18-36-49 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373270-a84d7c00-b5f7-11e8-853b-0217c0286fd7.png)

![2018-09-11 18-37-47 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373307-c3b88700-b5f7-11e8-9b48-7a9a50420ea2.png)

![2018-09-11 18-42-01 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373315-ca46fe80-b5f7-11e8-8be7-d55681c1e5c2.png)

![2018-09-11 18-43-07 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373342-e054bf00-b5f7-11e8-9fc7-1960a7b88f76.png)

![2018-09-11 18-44-11 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373360-eea2db00-b5f7-11e8-9708-6b18f235ce48.png)

![2018-09-11 18-45-33 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373388-01b5ab00-b5f8-11e8-8a19-9980bd3c0944.png)

![2018-09-11 18-45-46 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45373411-15f9a800-b5f8-11e8-9603-fcf9e6c4c770.png)

![2018-09-11 19-38-35 ekran goruntusu](https://user-images.githubusercontent.com/42475284/45374326-6a9e2280-b5fa-11e8-9c26-030bd4e89026.png)

I have made no adjustments other than these images...do I have a settings file where I can type the location of the folder where the certificates are stored ?? it probably does not recognize the location of the certificate folder ?? What do you think @kgretzky  ??

**Comment by kgretzky** [comment]
>Evilginx will generate a new root CA certificate when it runs for the first time. You can find the CA certificate at $HOME/.evilginx/ca.crt or %USERPROFILE%\.evilginx\ca.crt. Import this certificate into your certificate storage as a trusted root CA and your browsers will trust every certificate, generated by Evilginx.

That part of the blog post was crucial.

**Comment by CyberTheReape** [comment]
@kgretzky i know it... look at the sixth picture ... ca certifica in /root/.evilginx/crt/ca.crt 
but it is not working.. Do I need to move the ca.crt certificate file to another folder?? @kgretzky
