### ISSUE TITLE
Capturing all submitted data on lure pages.

### ISSUE THREAD

**Issue by infosecconsultant** [kgretzky/evilginx2#513]
Hi there, 

I'm looking for a way to log all user input entered/submitted to a page regardless of if it's correct or not. If I am able to get the raw credentials entered, instead of the cookies, it gives the possibility of password reuse on other environment applications that are not using MFA. Occasionally users will write _helpful_ things when they realize a site is a phish like 'nice try red team'. If they enter that, we know it's burnt rather than 'we did not get any hits'.

I daresay I can do that by tcpdumping all traffic and going through the output later, but that's not an elegant solution either, especially when running on budget VPS's. 

Any thoughts on how to do this would be much appreciated. 

Thanks,

**Comment by An0nUD4Y** [comment]
@infosecconsultant , That can be easily done by injecting a javascript codes. We can get the value of all input fields and then can send a xhr request containing those fields values.
And in phishlet we can add custom parameter to capture in evilginx session.

FOR REFERENCE CHECK FACEBOOK PHISHLET.

**Comment by infosecconsultant** [comment]
Oooh hey that's a fantastic idea! 
It'd still be neat if there was a switch you could just toggle to 'capture all typed data' but this will work as a fix for now. 
Cheers @An0nUD4Y

**Comment by An0nUD4Y** [comment]
@infosecconsultant , You can see all the intercepted requests by using debug mode in evilginx. And there also you can find all the parameters of Http Requests.
`evilginx --debug`

**Comment by kgretzky** [comment]
@infosecconsultant You can try to specify `custom` fields for intercepting other POST arguments.

Check it out here on the Wiki: https://github.com/kgretzky/evilginx2/wiki/Phishlet-File-Format-(2.3.0)#credentials
