### ISSUE TITLE
Certificate generation issue

### ISSUE THREAD

**Issue by physics-sec** [kgretzky/evilginx2#514]
Hi!

I believe there might be an issue with the certificate generation,
I was working on a phishlet which had several subdomains and evilginx generated the certificates perfectly.

Now, after some testing, I discovered some other subdomains that I added to the _proxy_host_ in the phishlet.
The thing is that evilginx is does not update the certificates to include these new subdomains.
Now even if I disable and re-enable de phishlet.

I went to the .evilginx folder and deleted the .crt and .key files for that domain and that worked.
Evilginx regenerated the certificated including now all the subdomains that are in the phishlet.

May be it should be a check every time a phishlet is enabled: if it has new subdomains, the certificate should be regenerated.

(I have no idea how to use Let's Encrypt, sorry I don't just submit a PR)

Thank you!

**Comment by An0nUD4Y** [comment]
@physics-sp , Yupp i can confirm this issue.

**Comment by physics-sp** [comment]
Great,
The fix shouldn't be too hard

The [loadPhishletCertificate](https://github.com/kgretzky/evilginx2/blob/master/core/certdb.go#L249) function should also receive the domain list as a parameter and verify that the Subject Alt Names match.
I'm now sure how to get all the supported DNS Names from the certificate, There is no build in function.. 😞
may be a new dependency?

**Comment by physics-sp** [comment]
Submitted PR!
seems to detect the new domains correctly 😄 
no new dependencies needed after all

**Comment by kgretzky** [comment]
Thank you for the PR! Yes, this was a known bug for a long time. I will verify the PR a bit later and merge it in when I don't see any issues with it. 👍

**Comment by physics-sp** [comment]
Awesome!

**Comment by physics-sp** [comment]
Added a check
If the certificate expires in less than a week (they last 3 months), is regenerated

**Comment by Hackndo** [comment]
Damn, I just read this. I added this functionnality today on my local version. Will check the PR :)

**Comment by physics-sp** [comment]
I'm glad you liked it!
