### ISSUE TITLE
Provide an uninstall option

### ISSUE THREAD

**Issue by phish** [kgretzky/evilginx2#521]
I tried to start from scratch by removing the .evilginx directory, the binary in /usr/local/bin and the directories in /usr/local/share/evilginx
I reinstalled evilginx and it remembered which phishlets I had activated and which domain I was using.

I wonder where this information is stored 

[EDIT] I found the info in the .evilginx directory of root. 

A uninstall script that would delete all configuration information would be welcome.

**Comment by kgretzky** [comment]
Thanks for suggestion. This is not likely to be added in near future.
For now you can uninstall manually, it is not that hard.
