### ISSUE TITLE
Phishlet enabling error

### ISSUE THREAD

**Issue by remydesaintphalle** [kgretzky/evilginx2#526]
Whenever I try to enable my phishlet, it gives me this error:
: phishlets enable instagram 
[04:13:19] [inf] enabled phishlet 'instagram'
[04:13:19] [inf] setting up certificates for phishlet 'instagram'...
[04:13:19] [war] failed to load certificate files for phishlet 'instagram', domain 'instagram.login.remy.wtf': open /root/.evilginx/crt/instagram.login.remy.wtf/instagram.crt: no such file or directory
[04:13:19] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[04:13:27] [!!!] acme: Error -> One or more domains had a problem:
[m.instagram.login.remy.wtf] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for m.instagram.login.remy.wtf - check that a DNS record exists for this domain, url: 
[www.instagram.login.remy.wtf] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.instagram.login.remy.wtf - check that a DNS record exists for this domain, url: 

My DNS records are:
NS | remy.wtf   ns3.digitalocean.com.   3600
NS | remy.wtf   ns2.digitalocean.com.   3600
NS | remy.wtf   ns1.digitalocean.com.   3600
A | www.remy.wtf   157.230.208.85   3600
A | remy.wtf   157.230.208.85   3600
A | m.remy.wtf   157.230.208.85   3600

Any help is appreciated

**Comment by CraftedCat** [comment]
enable phishlet, and run "phishlets get-hosts instagram", then create DNS recrods

**Comment by remydesaintphalle** [comment]
Thats the problem. I'm not able to enable the phishlet because it says there is a DNS error when I have the proper DNS set up.  Whenever I try to enable it, it gives me those errors after saying "failed to load certificate files for phishlet 'instagram', domain 'remy.wtf': open /root/.evilginx/crt/remy.wtf/instagram.crt: no such file or directory" I'm not sure what instagram.crt is and why it isn't there

**Comment by remydesaintphalle** [comment]
Also, on startup, evilginx has started to say "Failed to start nameserver on port 53" That might contribute to the problem

**Comment by remydesaintphalle** [comment]
I am using Uniregistry, and my DNS settings are ns1.digitalocean.com, ns2.digitalocean.com, and ns3.digitalocean.com

**Comment by remydesaintphalle** [comment]
I was able to fix the port 53 error by running with sudo, but now I get this message when I try to enable a phishlet:
"get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.api.letsencrypt.org: Temporary failure in name resolution"

**Comment by CraftedCat** [comment]
systemctl stop systemd-resolved


#### systemctl start systemd-resolved
edit /etc/resolv.conf
nameserver 8.8.8.8

**Comment by remydesaintphalle** [comment]
THANKS!!! It worked!

**Comment by jvrbn** [comment]
@remydesaintphalle Est-ce que tu as réussi à faire fonctionner ça?
