### ISSUE TITLE
does not capture passwords on mobile devices 

### ISSUE THREAD

**Issue by trukito2020** [kgretzky/evilginx2#536]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.
How can I configure the .yaml to change the password variable? I have problems because from a mobile browser it only captures me the username but not the password.

However, from my pc browser if I capture username and password.

I already tried with Facebook and Instagram but from the mobile it only captures me user

Can someone help me to configure or where do I have to modify? Thank you

**Comment by mihai9621** [comment]
javascript does not run on the submit button because the mobile version has an expensive type of button
