### ISSUE TITLE
Can i use Evilginx2 with a raspberry pi 4 ?

### ISSUE THREAD

**Issue by HugoLGF** [kgretzky/evilginx2#539]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

___________________________

Hello i was wondering i could use evilginx domain & ip with my raspberry instead of a server ?

**Comment by davisfreimanis** [comment]
Yes. Evilginx2 will work on your raspberry pi 4. Follow the installation instructions for installation with Docker or from source.

**Comment by HugoLGF** [comment]
When i mean use my raspberry is use it for the NS1 ip and domain i can ? (sorry i'm french so i'm cousi cousa in english)
