### ISSUE TITLE
Password encrypted

### ISSUE THREAD

**Issue by loutchoo** [kgretzky/evilginx2#542]
Hello, i created the phishlet of steam but when i login the password is encrypted like this :
![image](https://user-images.githubusercontent.com/63863060/100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b.png)
Do someone have any idea to fix this ? Thanks

**Comment by mihai9621** [comment]
send phishlet let's see what you wrote

**Comment by azamet90** [comment]
> Hello, i created the phishlet of steam but when i login the password is encrypted like this :
> ![image](https://user-images.githubusercontent.com/63863060/100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b.png)
> Do someone have any idea to fix this ? Thanks

i think this happens on some new model phone's

**Comment by roymillar** [comment]
@mihai9621 am facing the same issue. can i send my own phishlet so that you can help me explain what to do.
Thanks.

**Comment by roymillar** [comment]
@kgretzky how can i fix this sir? [https://user-images.githubusercontent.com/63863060/100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b.png](url)

> > Hello, i created the phishlet of steam but when i login the password is encrypted like this :
> > ![image](https://user-images.githubusercontent.com/63863060/100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b.png)
> > Do someone have any idea to fix this ? Thanks
> 
> i think this happens on some new model phone's

@kgretzky
