### ISSUE TITLE
Certificates do not renew

### ISSUE THREAD

**Issue by jkennedyvz** [kgretzky/evilginx2#547]
Hi, 

On a long-lived instance the letsencrypt certificates do not renew when they expire.

**Comment by Hackndo** [comment]
Hey,
PR https://github.com/kgretzky/evilginx2/pull/515 has already been submitted (more info https://github.com/kgretzky/evilginx2/issues/514#issuecomment-704665850)

**Comment by jkennedyvz** [comment]
Thanks @Hackndo , I apologize for not seeing that PR.
