### ISSUE TITLE
How DO I FIX THIS ?

### ISSUE THREAD

**Issue by testinglab66** [kgretzky/evilginx2#551]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.
I'm getting this error messages each time run evilginx2

> [12:54:09] [!!!] Failed to start nameserver on port 53
[12:54:09] [!!!] listen tcp :443: bind: address already in use

please how do i fix this??? 
![Screenshot 2020-12-16 08:01:08](https://user-images.githubusercontent.com/75833727/102351738-f12dd100-3f74-11eb-8645-5a77ab4d3211.png)

**Comment by testinglab66** [comment]
Your response time is too low sir... its almost 24hrs

**Comment by kgretzky** [comment]
I'm very sorry to have kept you waiting, sir.

Our free support department is currently short of staff due to the pandemic.
Next time when you feel you're waiting too long for a response to your ticket, click the button below.

![image](https://user-images.githubusercontent.com/19260967/102477132-40026600-405c-11eb-852e-910c085801f8.png)

 The more times you click on it, the sooner our staff shall respond to your inquiry.

**Comment by nickvangilder** [comment]
LOL

**Comment by azamet90** [comment]
> #### DO NOT ASK FOR PHISHLETS.
> #### DO NOT ASK FOR HELP CREATING PHISHLETS.
> #### DO NOT ASK TO FIX PHISHLETS.
> #### DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
> #### EXPECT A BAN OTHERWISE. THANK YOU!
> #### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.
> I'm getting this error messages each time run evilginx2
> 
> > [12:54:09] [!!!] Failed to start nameserver on port 53
> > [12:54:09] [!!!] listen tcp :443: bind: address already in use
> 
> please how do i fix this???
> ![Screenshot 2020-12-16 08:01:08](https://user-images.githubusercontent.com/75833727/102351738-f12dd100-3f74-11eb-8645-5a77ab4d3211.png)

fastest way to fix this for me was using it on debian... ubuntu also gives same error... use it on debian...

**Comment by pcouy** [comment]
If you ( @testinglab66 & @azamet90 ) cannot understand such a simple and clear error message, that means two things :

- You are not a computer security specialist and there is a 99% chance that your use of this tool is unlawful
- You are going to leave evidence of your hacking attempts all over the place, and will end up in prison the moment law enforcement gets involved

**Comment by ABHIJEET80040** [comment]
lmao

**Comment by Ret2lib** [comment]
Had the same issue. Fixed it by downloading more ram.
