### ISSUE TITLE
instagram phishlet  issue

### ISSUE THREAD

**Issue by rayan312** [kgretzky/evilginx2#556]
hello
instagram phishlet got this issue every time 
how to fix it ?

![ggg](https://user-images.githubusercontent.com/76600219/103142430-ce30b900-46fa-11eb-899d-0cd09ad35160.PNG)

**Comment by furkan6116** [comment]
+up , im also getting this error, can anyone please help ?

**Comment by rayan312** [comment]
bro idon't know but i think instagram blocking server ip

**Comment by rayan312** [comment]
> +up , im also getting this error, can anyone please help ?

bro idon't know but i think instagram blocking server ip

**Comment by furkan6116** [comment]
are u sure ? , because we both are getting this error.
can you send me a contact mail or discord ID.
ı think we will help ourself and can find a solution :)

**Comment by prem1835** [comment]
hey @furkan6116 were you able to resolve the issue?
I'm having the same error

**Comment by rzmpzgeviii** [comment]
@prem1835  same here. DId you find the solution?
