### ISSUE TITLE
page not working

### ISSUE THREAD

**Issue by azamet90** [kgretzky/evilginx2#557]
i did installed evilginx to my debian server and my debian server is protected with cloudflare... certificates working without errors also it is creating it and enabling the facebook phishlet without errors... the problem is that my domain is not working after i enable the phishlet? its saying page not working? is there an extra proccess for using evilginx2 on cloudflare?

**Comment by dangote007** [comment]
hello pls let me know if you found the solution to this issue as i am facing the same problem. I did all the dns config on domain side and also did A config on droplet side but my domain is not working after i launch phishlets
