### ISSUE TITLE
o365 test running url link

### ISSUE THREAD

**Issue by Coronavirus27009** [kgretzky/evilginx2#568]
I tried the lure link i got and tried to test run with a credential and got the error message.

![58D8A290-47B4-47F0-9A7A-6DA97B87EAF1_1_105_c](https://user-images.githubusercontent.com/73862294/106520828-a55fc880-64dd-11eb-8e28-c51c92b75d77.jpeg)

![914101F2-2B0F-47EA-8F51-943724D55E9D_1_105_c](https://user-images.githubusercontent.com/73862294/106520839-a7c22280-64dd-11eb-8c76-54fc478a0bd7.jpeg)

**Comment by Coronavirus27009** [comment]
I have already typed my username and hit enter and this is the error message i got.

**Comment by tatramaco** [comment]
This occurs when you use an account without a valid o365 subscription....
