### ISSUE TITLE
About js_inject

### ISSUE THREAD

**Issue by ni3ck** [kgretzky/evilginx2#569]
When I try to make some templates, the Passwd value obtained after injecting JS code is encrypted. May I ask, can this value be unable to obtain the original text by injecting JS?

**Comment by Coronavirus27009** [comment]
Hello Please do you have any idea on why after the user types in the username to proceed to the next page for password the phishing link i created will project the error below this message as shown in the picture. i have been on this issue for more than 3 days now. 


![58D8A290-47B4-47F0-9A7A-6DA97B87EAF1_1_105_c](https://user-images.githubusercontent.com/73862294/106643436-05ac4400-658a-11eb-968b-d160148dad29.jpeg)

![7CD7EF45-5603-4F73-8F86-30611583203D_1_105_c](https://user-images.githubusercontent.com/73862294/106643524-25dc0300-658a-11eb-8337-2151d136f687.jpeg)

**Comment by ni3ck** [comment]
You can use "--debug" to try to capture packet data to analyze the problem
