### ISSUE TITLE
[bug] duplicate hosts entries with certain yaml config options

### ISSUE THREAD

**Issue by audibleblink** [kgretzky/evilginx2#57]
The following phishlet configuration will generate duplicate dns records when using the `get-hosts` option in developer mode.

```yaml
proxy_hosts:
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'abc.com', session: false, is_landing: true}
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'xyz.com', session: false, is_landing: false}
```

__phishlet get-hosts abc__:

```sh
127.0.0.1 ssl.abc.com.phishdomain.com
127.0.0.1 ssl.abc.com.phishdomain.com
```

__expected__:
```sh
127.0.0.1 ssl.abc.com.phishdomain.com
127.0.0.1 ssl.xyz.com.phishdomain.com
```

I've not yet verified if this also affects whether or not 2 proxies (abc and xyp) get created correctly or whether this is just a cosmetic bug where the incorrect host entries are printed.

**Comment by kgretzky** [comment]
Thanks for reporting. This is intended behavior.

The hostname part `abc.com.phishdomain.com` that you set up for the phishlet must remain the same for all phishing subdomains. You need to make the `phish_sub` unique for each entry in order for the phishlet to work properly.

This example should fix it:
```
proxy_hosts:
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'abc.com', session: false, is_landing: true}
  - {phish_sub: 'ssl2', orig_sub: 'ssl', domain: 'xyz.com', session: false, is_landing: false}
```
Then you will get hosts:
```
127.0.0.1 ssl.abc.com.phishdomain.com
127.0.0.1 ssl2.abc.com.phishdomain.com
```
