### ISSUE TITLE
Why does it give bad certificates

### ISSUE THREAD

**Issue by emprrr** [kgretzky/evilginx2#575]
Hello, evilgnix is ​​working fine, everything goes as it should until the moment when I enter the phishing domain in the console with evil running, it gives this:
2021/02/12 18:43:56 [051] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:43:58 [054] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:43:58 [056] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:43:58 [055] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:43:58 [057] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:43:59 [058] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:44:00 [059] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:44:00 [060] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate
2021/02/12 18:44:00 [061] WARN: Cannot handshake client abs.twimg.com remote error: tls: bad certificate

**Comment by athena2001** [comment]
im having this exact problem too. I think this happened after the new update

**Comment by emprrr** [comment]
А как установить прошлую версию подскажи?

**Comment by emprrr** [comment]
How to install the previous version, tell me?

**Comment by emprrr** [comment]
> im having this exact problem too. I think this happened after the new update

How to install the previous version, tell me?

**Comment by athena2001** [comment]
> > im having this exact problem too. I think this happened after the new update
> 
> How to install the previous version, tell me?

wouldnt matter because im still having the same problem with the old version too lol

**Comment by athena2001** [comment]
> > im having this exact problem too. I think this happened after the new update
> 
> How to install the previous version, tell me?

try connecting to a vpn and see if your page works

**Comment by athena2001** [comment]
@kgretzky please help

**Comment by emprrr** [comment]
> @kgretzky please help

+++ I support

**Comment by kgretzky** [comment]
This is not a help desk or support portal.

**Comment by athena2001** [comment]
> This is not a help desk or support portal.

everything was working fine until the new update tho :(
