### ISSUE TITLE
Bash file for Evilginx2

### ISSUE THREAD

**Issue by well728** [kgretzky/evilginx2#576]
I have installed the evilginx2 by using git clone method but dont know how to run it.

**Comment by emprrr** [comment]
you need to install golang at least 1.13, and then compile evilginx2 with the make command

**Comment by Coronavirus27009** [comment]
What are your error messages?

**Comment by kameni14** [comment]
Hi,I have dns propagate .Can I set my phishlets without proper problem?

**Comment by No-Cellist-7780** [comment]
Download it from the releases ig? Thats way more easier
