### ISSUE TITLE
about SSL/TLS certificates from LetsEncrypt

### ISSUE THREAD

**Issue by abarava** [kgretzky/evilginx2#577]
when type `enabled phishlet`
i got 
get directory at 'https://acme-v02.api.letsencrypt.org/director y': Get https://acme-v02.api.letsencrypt.org/directory: dial tcp: lookup acme-v0 2.api.letsencrypt.org: Temporary failure in name resolution
this problem
how can i fix this one?
thank you

**Comment by kameni14** [comment]
I have the same issue

**Comment by abarava** [comment]
I could solve this.
