### ISSUE TITLE
[request] a `reload` command to refresh configs after changes are made

### ISSUE THREAD

**Issue by audibleblink** [kgretzky/evilginx2#58]
Development of phishlets could be made smoother by providing users a `reload` command that re-reads main configs and  phishlet yaml.

**Comment by kgretzky** [comment]
Agreed! I have this in the back of my head to eventually implement. Thanks!
Will make it official now.

**Comment by norisharma** [comment]
[war] failed to load certificate files for phishlet 'linkedin', domain 'myowndomain2.com': open /root/.evilginx/crt/myowndomain2.com/linkedin.crt: no such file or directory
[01:51:22] [inf] requesting SSL/TLS certificates from LetsEncrypt..

**Comment by zero-timeszer0** [comment]
I understand this command is not yet availble but is there any other work around, because i made som changes in yaml file and i cant see any changes whatsoever (no positive or negativ effect). so im wondering ho do i test that it is working or not?

thx in advance
