### ISSUE TITLE
Buy google

### ISSUE THREAD

**Issue by cybernoob13123** [kgretzky/evilginx2#583]
Did any one can bypass google 2fa successfully
Any method if you can
I can buy

**Comment by kmac48** [comment]
email me npace201@gmail.com i can assist you but do not wish to be banned

**Comment by K4zBeK** [comment]
> Did any one can bypass google 2fa successfully
> Any method if you can
> I can buy

add me in telegram @GoUnix i will help you

**Comment by psyinzx** [comment]
Email me cypher688@gmail.com

**Comment by Aleksandr3313** [comment]
Кто ни будь phishlets сделал чтоб попробовать gmail, vk, mail, telegram, на evelginx

**Comment by rickyrik001** [comment]
email me rickyrik@protonmail.com i can help you out

**Comment by TomAbel** [comment]
https://github.com/TomAbel/evilginx.botguard

**Comment by aitsu01** [comment]
> Кто ни будь phishlets, сделал чтоб попробовать gmail, vk, mail, telegram, на evilginx?

уже сделал сам ;)
