### ISSUE TITLE
How do I receive the URL of the pre-phish template?

### ISSUE THREAD

**Issue by pootystar** [kgretzky/evilginx2#596]
I am attempting to get the pre-phishlets to work.

I run `evilginx -t ~/evilginx2/templates` to start the program.

Then I run `lures edit 5 template download_example.html`

The result is `[21:26:41] [inf] template = 'download_example.html'

However, at this point, nothing else happens. How can I receive the URL of the pre-phish template? Thank you.

**Comment by therealelyayo** [comment]
lures get-url 0 from_name="Ronald Rump" filename="Annual Salary Report.xlsx"

**Comment by YOUNE-S** [comment]
same problem,  can't find  the url of the pre-phishlets like domain.com/download_example.html
