### ISSUE TITLE
Change the Rick ashley URL

### ISSUE THREAD

**Issue by elementsy** [kgretzky/evilginx2#597]

**Comment by elementsy** [comment]
Hello Gretzky I have being testing evilginx2 and its amazyng, I have a couple of questions, I hope you can help me please:
1.- ¿How can I change the Rick Ashley URL to be something else?
2.- ¿Is it possible for evilginx2 to change any word in the target HTML the same way it changes "original-domain.com" to be "my-domain.com"? For example, is it possible to look for a specific word or command in the target HTML  like : "hello" and change it to "sayonara"? 
Thankyou very much abd have a nice day.

**Comment by dedpehto** [comment]
> 2.- ¿Is it possible for evilginx2 to replace any word in the target HTML the same way it replaces "original-domain.com" to be "my-domain.com"? For example, is it possible to look for a specific word or in the target HTML like : "hello" and replace it to "sayonara"?
> Thankyou very much and have a nice day.

Yes. Read about sub_filters
