### ISSUE TITLE
Invalid url 

### ISSUE THREAD

**Issue by harrypotter360** [kgretzky/evilginx2#599]
Hello !
My question must be stupid!
I installed evilginx2, and configured it like this:

"config domain google.com
config ip xx.xx.xxx.xx

phishlets hostname reddit reddit.google.com
lures create reddit
lures edit 7 redirect_url https://www.reddit.com/r/Whatcouldgowrong/comments/mjug1i/removing_the_prime_minister_from_the_podium/

lures get-url 7 "

I get a link, but the link is invalid ...

Thank you !

**Comment by charlesbel** [comment]
I think you just not own google.com

**Comment by HSmile007** [comment]
I think it's from your phishlet.. try using another phishlet
