### ISSUE TITLE
TLS read error with facebook phishlet

### ISSUE THREAD

**Issue by loriezn** [kgretzky/evilginx2#6]
: 2018/07/29 01:54:06 [091] WARN: Cannot read TLS request from mitm'd client www.facebook.com EOF
[01:54:06] [imp] [5] redirecting to URL: https://www.facebook.com/

in test this out I am about to grab my credentials however the server fails to forward me onto my facebook feed.

service is running in an aws ec2 instance & domain ns via route53.

I updated the nameservers in namecheap to point to the supplied amazon addresses, then created my host records in route53 as follows:

A record for DOMAIN.com point to my SERVER IP

NS records point to DOMAIN.COM
ns1.DOMAIN.COM 
ns2.DOMAIN.COm

CNAMES
facebook.DOMAIN.COM 
www.facebook.DOMAIN.COm
m.facebook.DOMAIN.COM 
static.facebook.DOMAIN.COM

EVILGINX
config domain DOMAIN.COM
config ip SERVER IP
redirect_key : xi
verification_key : ew
verification_token : 24f4
redirect_url : https://www.google.com

phishlet hostname: facebook.DOMAIN.COM
phishlet get-url: https://www.facebook.com/ (i also tried https://www.facebook.com/settings) 
landing url : https://www.facebook.DOMAIN.com/login.php

Could you please explain to me where i've gone wrong with my config.

**Comment by kgretzky** [comment]
Do you own domain `domain.com`?

**Comment by loriezn** [comment]
yes i own the domain. I was just using domain.com as an example placeholder

**Comment by kgretzky** [comment]
Facebook phishlet may be buggy as I didn't test it properly yet. That's why it may not be redirecting at the moment after the session is capture.

Does it properly capture the cookies after login?

**Comment by loriezn** [comment]
Yes it properly captures the cookies and I can load them into another browser and it works great.
It's just the final redirect which 95% of the time fails to load. I did experience some sessions that it would follow through but am unable to recreate the same scenario again to make that happen

**Comment by kgretzky** [comment]
In the log you pasted, I see:
```
[01:54:06] [imp] [5] redirecting to URL: https://www.facebook.com/
```
Did you choose the redirection URL to be `https://www.facebook.com/`? Can you try other URL to see clearer if it redirects? It may be automatically redirecting to main facebook page.

**Comment by JoyceX2times** [comment]
Hello loriezn, did you manage to find out why the redirection was not working? I have the exact same issue.
