### ISSUE TITLE
Sessions seem to be overwriting

### ISSUE THREAD

**Issue by sandwichi** [kgretzky/evilginx2#604]
I can get 1 evilginx session with correct auth tokens that work. If I then log in with a second user using the same lure URL the username and password will overwrite the first session, and auth tokens will not be saved for the second user. I've noticed that if I login with the second user from a different public IP the second evilginx session will be created properly with the second user's auth tokens.

**Comment by redlocks** [comment]
Just now I wanted to report this problem, you got ahead of me :)
This is really inconvenient - since many are behind NAT, sessions are lost(

**Comment by sandwichi** [comment]
This would be the perfect tool for red team phishing engagements if this issue wasn't occurring. Unfortunately I don't know go and my programming skills aren't good enough to dig into the code and figure out what functionality is causing this.
