### ISSUE TITLE
I can help you with evilginx2 installation, making phishlets and other

### ISSUE THREAD

**Issue by K4zBeK** [kgretzky/evilginx2#621]
Paid consultations, evilginx2/vps/vds configuration, phishlets creation, soft coding, website creation and other.
Add me in telegram @GoUnix

**Comment by ronaldPHishing** [comment]
Hi
Why the facebook phishlet page primary language isn't English?

**Comment by Babyshark71** [comment]
hi I am needing help to configure evilginx2 on debian9 I have followed many tutorials but I am getting an error message when t comes to 'make'. please can you help me resolve this.

**Comment by Trevorsig** [comment]
Hey whats your telegram @K4zBeK 

GoUnix doesn't exist

**Comment by K4zBeK** [comment]
> > Hey whats your telegram @K4zBeK
> > GoUnix doesn't exist
> 
> Yes, give us new contact

sorry guys, add me again

**Comment by K4zBeK** [comment]
> Hey whats your telegram @K4zBeK
> 
> GoUnix doesn't exist

sorry guys, add me again @gounix
