### ISSUE TITLE
Facebook refreshing and password not captured

### ISSUE THREAD

**Issue by grimmpotter** [kgretzky/evilginx2#625]
Hey everyone,

Hope you are all doing good, I was trying to use the evilginx tool, but I faced some issues that I don't really understand why when I was carrying out tests.

Basically, I used the Facebook phishlets everything seems fine for a start but when I open the fake link, I enter my email and password, instead of login in and go to the next steps, it keeps refreshing on the fake website every time.

![image](https://user-images.githubusercontent.com/26930115/123691209-52d3cf80-d823-11eb-880f-61a73fc85dce.png)

![image](https://user-images.githubusercontent.com/26930115/123687124-8bbd7580-d81e-11eb-91f1-3009046b137d.png)

And sometimes when it doesn't keep refreshing it gives these informations in the console of evilginx, no password, just the token and the email.
![image](https://user-images.githubusercontent.com/26930115/123691997-4734d880-d824-11eb-9015-f70b508d8449.png)

That's what i get basically.

I'd appreciate if someone can explain why it's happening that way.

Thanks in advance.

**Comment by charlesbel** [comment]
Use the latest version, look in the PRs to find it

**Comment by shan1141** [comment]
@grimmpotter Have you found the solution.  mine behaving the same. when enter the email and password it keep stays there.
and I realised when we using chrome desktop browser I can get the email and password. when link open using mobile we can only get the email. any reason for this. how to ratify. Any help ?

**Comment by charlesbel** [comment]
> @grimmpotter Have you found the solution.  mine behaving the same. when enter the email and password it keep stays there.
> and I realised when we using chrome desktop browser I can get the email and password. when link open using mobile we can only get the email. any reason for this. how to ratify. Any help ? 

Use the latest version, look in the PRs to find it
