### ISSUE TITLE
Instagram doesn't accept cookies!

### ISSUE THREAD

**Issue by Rovinskyi64** [kgretzky/evilginx2#627]
Hi guys, who faced this problem: the agreement window does not close. this problem is only on the instagram phishlet. How to fix this and is it possible at all?
As I understand it, this is the new Instagram protection from evilginx2
![Безымянный](https://user-images.githubusercontent.com/67419384/123939198-90119c00-d9a0-11eb-85a9-b0def9aef1e2.jpg)

**Comment by grimmpotter** [comment]
Hey !

I don't think so, you browser may be overloaded with cookies ! try refresh your browser data and let me know !

I had this issue too !

**Comment by Rovinskyi64** [comment]
> Hey !
> 
> I don't think so, you browser may be overloaded with cookies ! try refresh your browser data and let me know !
> 
> I had this issue too !

Thanks for the answer, bro. Tried restarting the browser, nothing helped. Tried to login from the mobile phone - the same problem. Also tried it from another computer, nothing worked, the window simply does not close and does not allow me to enter username and password. How did you solve this problem?

**Comment by grimmpotter** [comment]
Hey man !


I just did clear cache cookies ! also are you using a VPN ???? or a proxy ?

**Comment by Rovinskyi64** [comment]
> Hey man !
> 
> I just did clear cache cookies ! also are you using a VPN ???? or a proxy ?

No, I don't use vpn and proxy. I think the problem is with the instagram phishlet. Because all other phishlets like Facebook and Twitter work great. Can you share your Instagram fishlet with me?

**Comment by NiicOw974** [comment]
Hello , I have the same problem ! Anyone have the solution ?

**Comment by BuckPete** [comment]
I have got this same issue with the @charlesbel Instagram phishlet

On visiting my lure link I get the "Accept cookies from Instagram in this browser?" message.   Clicking on "accept" does nothing and the message just wont go and enable us to try and login.

I have tried on all browsers and different machines.  Same result.

Charl. Any ideas mate?  s’il vous plaît?

 Merci Beaucoup

**Comment by charlesbel** [comment]
> I have got this same issue with the @charlesbel Instagram phishlet
> 
> On visiting my lure link I get the "Accept cookies from Instagram in this browser?" message.   Clicking on "accept" does nothing and the message just wont go and enable us to try and login.
> 
> I have tried on all browsers and different machines.  Same result.
> 
> Charl. Any ideas mate?  s’il vous plaît?
> 
>  Merci Beaucoup

I already fixed it with this new phishlet : https://github.com/kgretzky/evilginx2/pull/611

**Comment by BuckPete** [comment]
Wonderful @charlesbel 

All good. Thanks so much.
