### ISSUE TITLE
Can Help??

### ISSUE THREAD

**Issue by apollo89** [kgretzky/evilginx2#630]
> -

**Comment by Babyshark71** [comment]
Need help when it comes to “cd evilginx2” part when installing from code I have a no such file or directory message coming up

**Comment by Rovinskyi64** [comment]
Did you install GO language?

**Comment by apollo89** [comment]
Yes i habeh

**Comment by Babyshark71** [comment]
> Did you install GO language?

Yes I do

**Comment by apollo89** [comment]
Can you send me a German anleitung für modlishka my English is very very
bad I need modlishka for 2fa by Gmail I need the sms code

Babyshark71 ***@***.***> schrieb am Mo., 5. Juli 2021, 15:56:
