### ISSUE TITLE
Urgent help needed

### ISSUE THREAD

**Issue by Babyshark71** [kgretzky/evilginx2#633]
I’m trying to open Evilginx2 on Debian9 from source code using Putty but I always come across “no such file or directory” whenever I enter “Cd evilginx2” I’m a noob I would appreciate any help and would Defoes pay you back!

**Comment by Rovinskyi64** [comment]
Did you install GO language?

**Comment by Babyshark71** [comment]
Yes I have

**Comment by Rovinskyi64** [comment]
Write me on telegram @Perdunfull
