### ISSUE TITLE
Instagram please wait error

### ISSUE THREAD

**Issue by Muhasheikh** [kgretzky/evilginx2#634]
![Screenshot_20210709-224135](https://user-images.githubusercontent.com/63383715/125113984-fddb6780-e106-11eb-9d39-a8c19fa664d5.jpg)

**Comment by Rovinskyi64** [comment]
Have the same problem but only with facebook, did you find solution?

**Comment by Muhasheikh** [comment]
Whats the name of your hosting provider?

**Comment by Rovinskyi64** [comment]
digitalocean

**Comment by charlesbel** [comment]
Facebook/Instagram seems to have a fraud detection system like all big websites targeting by IP address, so I would recommend to not use IP of VPS of famous hosters. Instead, I would recommend residencial proxies.
