### ISSUE TITLE
PARSE CAPTURED SESSIONs  

### ISSUE THREAD

**Issue by gronget** [kgretzky/evilginx2#635]
Iam trying to parse captured sessions to a frontend.
Tried the /root/.evilginx/data.db file but all i see is not the correct captured session.
Any ideas how i can interface with the captured sessions outside of evilginx.

**Comment by nicolas-brahim** [comment]
Hi @gronget were you able do do it? I'm running evilgnix2 in docker and I want to export the sessions to JSON but I'm not able to do it.

**Comment by gronget** [comment]
I was not able to get a solution. Hoped The developer would help with a solution but he seems very dormant here.
