### ISSUE TITLE
Page won't open

### ISSUE THREAD

**Issue by ghost** [kgretzky/evilginx2#644]
I bought a domain off of go daddy and connected it to Cloudflare. It successfully sets up SSl/TLS certificates for the domain and generates a phishing link, but when I try to go to the link, I get a "Failed to open page error"

**Comment by Esp26** [comment]
I am facing same error

**Comment by TomAbel** [comment]
Try to set them up manually with certbot. Use this [guide](https://cilynx.com/how-to/evilginx2-vs-2fa-phishing/424/).
CTRL + F: Further configurations
