### ISSUE TITLE
Phishing in a local home network

### ISSUE THREAD

**Issue by TW-D** [kgretzky/evilginx2#649]
Hello, to understand my problem i expose you my operating mode on Raspberry Pi.

I) Configuration

```bash
nano /etc/hosts
#------------------------------------------------
#    (replace "127.0.1.1		raspberrypi" by "127.0.1.1		www.reddit.raspberrypi.home")
#------------------------------------------------
```

```bash
nano /etc/hostname
#------------------------------------------------
#   (replace raspberrypi by www.reddit.raspberrypi.home)
#------------------------------------------------
```

```bash
reboot
```

("hacker" computer)
```bash
nmap -Pn -sn www.reddit.raspberrypi.home
#------------------------------------------------
#    Nmap scan report for www.reddit.raspberrypi.home (192.168.1.X)
#    rDNS record for 192.168.1.X: <NAME>.home
#------------------------------------------------
```

II) Usage

```bash
cd /opt/evilginx2/
./bin/evilginx -developer -p ./phishlets/ -t ./templates/
: config domain raspberrypi.home
: config ip 127.0.0.1
: phishlets hostname reddit reddit.raspberrypi.home
: phishlets enable reddit
: lures create reddit
: lures get-url 0
```

(Internet browser of the "victim" on the lure page)
[lure-page](https://i.ibb.co/XSS89wJ/lure-page.png)
[lure-network-media](https://i.ibb.co/P1X6gxH/lure-network-media.png)

[evilginx2-tls](https://i.ibb.co/KyJ8gbB/evilginx2-tls.png)
The problem is here because the host "win.reddit.raspberrypi.home" or "events.reddit.raspberrypi.home" does not exist on the local home network
and "/etc/hostname" can have only one entry.

Do you think there is a solution without editing the modem/router configuration ?

Thank you for your help, cordially.

**Comment by TomAbel** [comment]
have you tried appending output of `phishlets get-hosts reddit` into /etc/hosts?

**Comment by TW-D** [comment]
@TomAbel, of course but the modem/router uses the hostname of the device for rDNS and a device can only have one hostname.
I have tried 
```
cat /etc/hosts
127.0.1.1		www.reddit.raspberrypi.home
127.0.1.1		win.reddit.raspberrypi.home
127.0.1.1		events.reddit.raspberrypi.home
```
Make the modem/router think the device has three different names (DHCP attack) ?

**Comment by TW-D** [comment]
Solved with multiple interfaces and dhclient. Thanks.
