### ISSUE TITLE
Capture all cookies and 2fa token

### ISSUE THREAD

**Issue by p3nt4** [kgretzky/evilginx2#65]
Is there a way to capture all issued cookies using evilgnx?
Similarly, is it possible to capture multiple password fields for 2fa?

Thanks

**Comment by p3nt4** [comment]
I see the cookie regex part has been implemented already: #44

**Comment by kgretzky** [comment]
What do you mean by multiple password fields?
Can you provide an example of such login page?

**Comment by p3nt4** [comment]
Well, 2FA pages often have a password field and a token field.
I managed to capture both by using regex for the password field and patching the code like this:
```
s.Password += " --- " + password
```
So that I get both the password and token in the password field.

It's a bit hacky but does the trick.

**Comment by kgretzky** [comment]
Added with 2.2.0 update.
