### ISSUE TITLE
o365 Tokens No Longer Captured

### ISSUE THREAD

**Issue by stillhunt14** [kgretzky/evilginx2#654]
I have been successfully the o365 phishlet for a few weeks, an issue started this morning where it will not longer capture tokens for MFA.  I can still get the username/password just fine but the tokens no longer work.

**Comment by stillhunt14** [comment]
I was able to resolve the issue the SignInStateCookie is now coming from .login.microsoftonlein.com

**Comment by sunshine69645** [comment]
hello, having the same issue can you please share your solution?

**Comment by Web3villian666** [comment]
I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your

**Comment by Daniel-McCoy-Sec** [comment]
I am having the same issue can anyone help?

mrock21 is the spelling mistake in your resolution on purpose?
