### ISSUE TITLE
regexp failed to compile

### ISSUE THREAD

**Issue by CraftedCat** [kgretzky/evilginx2#663]
Why evil can't compile this:
search: '(?<!bbb\\u003dhttps%3A%2F%2F)ccc.domain.com'
?

**Comment by TomAbel** [comment]
The repo uses the regular RegExp package, which does not support lookahead due to O(n) reasons.
Use  dlclark's [regexp2](https://github.com/dlclark/regexp2)

**Comment by TomAbel** [comment]
Use regex101 for testing expressions. Select golang on the left-hand side. https://regex101.com/r/qUdOr8/1

**Comment by CraftedCat** [comment]
Ok, thanks

**Comment by Web3villian666** [comment]
I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your

**Comment by 456478** [comment]
no, you can't even program site-wide recaptcha support for evilginx2, I doubt you can implement a regexp2 package into it...
