### ISSUE TITLE
Get https://acme-v02.api.letsencrypt.org/directory: dial tcp: lookup acme-v02.api.letsencrypt.org: Temporary failure in name resolution

### ISSUE THREAD

**Issue by im-simon** [kgretzky/evilginx2#665]
hi!
I have scanned all the topics related to this problem but the problem has not been solved on my side.
I bought a domain name on domains.google.com, I configured it by inserting the server names of my host, digital ocean (droplets) ns1.ns2 and ns3digitalocean.com

When I opened evilginx, everything was fine, I wanted to start by trying to phish from outlook.
When i enter phishlet 'outlook' hostname set to: testeoutlook.mydomain.fr everything is good .
It's when I write enabled phishlet 'outlook' that the problem starts and I get this error message.
![Capture d’écran 2021-09-23 102630](https://user-images.githubusercontent.com/91256914/134491075-14dfa5f2-617e-420c-9813-1b3d399cca6d.png)

**Comment by M3ph15** [comment]
> hi! I have scanned all the topics related to this problem but the problem has not been solved on my side. I bought a domain name on domains.google.com, I configured it by inserting the server names of my host, digital ocean (droplets) ns1.ns2 and ns3digitalocean.com
> 
> When I opened evilginx, everything was fine, I wanted to start by trying to phish from outlook. When i enter phishlet 'outlook' hostname set to: testeoutlook.mydomain.fr everything is good . It's when I write enabled phishlet 'outlook' that the problem starts and I get this error message. ![Capture d’écran 2021-09-23 102630](https://user-images.githubusercontent.com/91256914/134491075-14dfa5f2-617e-420c-9813-1b3d399cca6d.png)

I suspect you disabled systemd-resolved to release port 53?
If this is so - enable it back .. and do the following:

- Edit /etc/systemd/resolved.conf as root:
```
[Resolve]
DNS=8.8.8.8	#(or any other public DNS server)
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#DNSOverTLS=no
#Cache=no
DNSStubListener=no
#ReadEtcHosts=yes
```

- Create a symbolic link for /run/systemd/resolve/resolv.conf with /etc/resolv.conf as the destination:
`sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`

- Reboot your system. Enjoy)
