### ISSUE TITLE
Twitter links don't work properly

### ISSUE THREAD

**Issue by redirect-twitter** [kgretzky/evilginx2#666]
![2021-09-24](https://user-images.githubusercontent.com/77673744/134696530-8acb68c6-29d8-455e-89be-676c15a9f047.png)
The link does not work properly as shown in the image.
In debug mode `WARN: Cannot handshake client abs.twimg.com remote error: tls: unknown certificate` was displayed.

**Comment by takizawatakashi** [comment]
![2021-09-25](https://user-images.githubusercontent.com/77673744/134697218-dd350e4d-f278-4054-bc9c-7be879ccf591.png)

**Comment by TomAbel** [comment]
import the CA cert into your browser and you won't experience this issue

**Comment by takizawatakashi** [comment]
> import the CA cert into your browser and you won't experience this issue

twitter.com/login
When you hit
twitter.com/i/flow/login
Is it the cause of being skipped by?

**Comment by TomAbel** [comment]
![Screenshot_2021-09-24_21-59-41](https://user-images.githubusercontent.com/33309474/134726964-2c4ae8c7-d360-4281-8469-d97fd479a249.png)

**Comment by takizawatakashi** [comment]
![2021-09-25 (1)](https://user-images.githubusercontent.com/77673744/134734289-0f5cd91c-7fc5-4b3c-aa6f-46cb3edc4dd9.png)
I imported the certificate into Chrome but it didn't change.

**Comment by takizawatakashi** [comment]
It seems that the specifications of the Twitter login screen have changed.
