### ISSUE TITLE
Why Debian and no Centos?

### ISSUE THREAD

**Issue by osterhagenchemnitz** [kgretzky/evilginx2#67]

**Comment by keep-learning-go** [comment]
@osterhagenchemnitz  How is this related to Evilginx2 ?
Use any OS you prefer, as far as I know, Evilginx2 has no external dependencies (precompiled bins) and runs smoothly on any distro,
I tried running it on Kubuntu/Kali/Ubuntu 16/18/Fedora 28/Debian 9/Centos 7, all works with no issue or whatsover.

**Comment by osterhagenchemnitz** [comment]
Thank you for the answer.
