### ISSUE TITLE
o365 adfs 

### ISSUE THREAD

**Issue by oakryan** [kgretzky/evilginx2#675]
how can i solve this issue of o365 adfs, the issue is i have couple of domain that use the adfs the issue is it not picking the right subdomain example.

org_sub 'adfs' domain1.com
org_sub 'adfs' domain2.com
org_sub 'adfs'. domain3.com
org_sub 'adfs' domain1.com:443
org_sub 'adfs' domain2.com:443
org_sub 'adfs' domain3.com:443

when a user that use domain2 input there info eg email instead of it to go to adfs.domain2.com it goes to adfs.domain1.com is there something am missing on the phishlet or the issue is from evilginx plz i need help on how to make it trigger it specific domain.

**Comment by kosiwere1** [comment]
@[oakryan]

Were you able to fix it
