### ISSUE TITLE
Blocking URL access

### ISSUE THREAD

**Issue by keep-learning-go** [kgretzky/evilginx2#68]
Hey @kgretzky I hope you are doing fine.
I have a question, this is not issue report.
I've been experimenting with Evilginx lately, its awesome, and you've done great job with it.
Can you please tell (or drop some tips) is it possible to block access or replace url to certain paths?
For example.
Bob visited my tokenized page, all fine, but target website has widget on index page, in form of div object that shows visitor IP, and in our case it would be my AWS server IP and not his real IP.
Source of div script is in www.same-website.com/my-ip dir
So to beat this is there any way to block /my-ip path?
Thank you

**Comment by keep-learning-go** [comment]
Here's another question:
Is there any way to block all actions on website?
e.g Check button link looks like www.same-domain.com/#
and I dont want it to popup any modal window, so I dont it to work at all.
Is there any way to achieve this using Evilginx?
Sorry for bothering you with lots of questions.

**Comment by kgretzky** [comment]
Hey!

This all can be done through dynamic replacement of proxied site content with `sub_filters`. Check how string replacing is done for URLs and you can look for the content that you want to remove and replace it with something else.
