### ISSUE TITLE
LinkedIn deactivates account after all authorizations tokens captured!

### ISSUE THREAD

**Issue by Manneckaz101** [kgretzky/evilginx2#680]
LinkedIn deactivates account after all authorizations tokens captured!

**Comment by rnnhood** [comment]
same here, anyone can tell why is this happening?

**Comment by MelroyB** [comment]
LinkedIn detects the evil proxy. I modified the phishlet to proxy all subdomains for tracking pixels:

  - {phish_sub: 'platform-ecst', orig_sub: 'platform-ecst', domain: 'linkedin.com', session: false, is_landing: false}
  - {phish_sub: 'realtime', orig_sub: 'realtime', domain: 'linkedin.com', session: false, is_landing: false}
  - {phish_sub: 'platform', orig_sub: 'platform', domain: 'linkedin.com', session: false, is_landing: false}

but that didn't work.

**Comment by rnnhood** [comment]
is this on the main repo? or in a pull request yet?
