### ISSUE TITLE
Possibility to capture updated cookie

### ISSUE THREAD

**Issue by ndex11** [kgretzky/evilginx2#684]
Hi,
Is there any way to capture updated cookie?

Situation:
After landing on the login page cookie is created and captured by the Evilginx.
After successfull login cookie is then updated but update is not captured by the Evilginx.

**Comment by rnnhood** [comment]
maybe you should not capture the cookie on the landing page? but on the auth page?

**Comment by ndex11** [comment]
I have tried to experiment with session: true/false parameter and also tried to enter multiple rows with the domain and different configuration of phishlet....Nothing worked.... Problem is that the cookie is updated on the same domain as where is created...
Landing page (cookie created) -> authentication domain (2FA) -> Landing page (cookie updated)... Cookie is captured in the first step when accessing landing page.
