### ISSUE TITLE
Failed to load certficates for phishlet

### ISSUE THREAD

**Issue by azertyu2257** [kgretzky/evilginx2#686]
hi, I have a problem when i try to enable a phishlet. I think it's because of my DNS but I don't know why.
![Capture d’écran du 2021-11-16 18-03-16](https://user-images.githubusercontent.com/89607689/142031566-796d0ade-1559-4300-a5b9-942b26a3cad6.png)
![Capture d’écran du 2021-11-16 18-11-23](https://user-images.githubusercontent.com/89607689/142032758-07ecde63-d0db-4ee3-97a1-20e801a1e8e0.png)
![Capture d’écran du 2021-11-16 18-12-33](https://user-images.githubusercontent.com/89607689/142032771-0d54175a-9107-4340-afc2-67cf7e230cc2.png)

**Comment by MelroyB** [comment]
Port 80 open?

**Comment by azertyu2257** [comment]
how do i know this?

**Comment by azertyu2257** [comment]
i checked on yougetsignal and my port 80 is closed

**Comment by azertyu2257** [comment]
you think it's the problem?

**Comment by MelroyB** [comment]
Letsencrypt uses port 80. Look at the log. It’s says http and not https

**Comment by azertyu2257** [comment]
ok thanks, do you know a quick command to open it?

**Comment by MelroyB** [comment]
Don’t know which firewall you got, but try
sudo ufw allow 80/tcp

**Comment by azertyu2257** [comment]
![Capture d’écran du 2021-11-16 19-50-41](https://user-images.githubusercontent.com/89607689/142047248-fc2464cb-6bfd-42ad-ade4-ea95e3527b26.png)
i did this, restart evilginx and same problem

**Comment by azertyu2257** [comment]
up :)

**Comment by rnnhood** [comment]
did you have the latest version of certbot? i had that problem at the beginning, it is a little messy but in debian you should install snaptd or snap and then use it to install loke ''snap install certbot'' or so... and then having the lastest vercion giveme an update
