### ISSUE TITLE
Outlook 2fa cookies not working.

### ISSUE THREAD

**Issue by ssl-user-en** [kgretzky/evilginx2#692]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I recently tried testing outlook phishlet. It captures the cookies but they doesn't seem to work. I get the errors which are mentioned below -

Cookie “WLSSC” will be soon treated as cross-site cookie against “https://login.live.com/login.srf?contextid=EF7F32D83866DFC1&bk=1638781892&uiflavor=web&mkt=EN-US&lc=1033&uaid=97a84f2c6d1f4f00b1dd42e92c75a565&sessionid=M.17805154273269046954” because the scheme does not match.

I am getting these errors for every cookie I have injected. If anyone knows how to solve this problem, please let me know.

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the target end..... You can reach how to the developer on icq @mrgretzky
