### ISSUE TITLE
Allow user to change port

### ISSUE THREAD

**Issue by JR2Media** [kgretzky/evilginx2#693]
I've had to hack at the code to change the default ports from 443, to 8443 as I'm running through a reverse proxy. It's working.

But is there any reason why this option hasn't been added?

**Comment by riramar** [comment]
Could you please provide the source code of your implementation?
I'm facing the same issue for a specific subdomain.

**Comment by support-evilg526** [comment]
> Could you please provide the source code of your implementation? I'm facing the same issue for a specific subdomain.

Hello. Yes, we can help you. Contact us at support@evilginx2.com
