### ISSUE TITLE
[10:10:27] [war] [o365] unauthorized request:

### ISSUE THREAD

**Issue by maggy-1** [kgretzky/evilginx2#695]
It says new visitor has arrived but the username and password and the token is empty what could be the cause of this. Attached below is the kind of display prompt i usually get.
<img width="510" alt="git" src="https://user-images.githubusercontent.com/95232242/148245251-c53d7e37-4e0d-48ab-9c0f-135d4b4a5b8a.png">

**Comment by sunshine69645** [comment]
these are robots scanning your server for phishing pages, use blacklist unauth to add them to blacklist and prevent detecting your page.
