### ISSUE TITLE
Godaddy AWS config 

### ISSUE THREAD

**Issue by jayhill365** [kgretzky/evilginx2#696]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I keep getting errors, I believe I have correctly pointed my purchased godaddy domain toward my AWS server. 

However when I run command, phishlets enable facebook, 
I get getting 403 errors. Am I not configuring A records correctly in Godaddy , or is this an issue I need to fix within AWS?
<img width="1039" alt="Screen Shot 2022-01-05 at 9 40 29 AM" src="https://user-images.githubusercontent.com/19259608/148264350-8be1b94e-a3b1-44a6-a803-a735c5ad0d6c.png">
<img width="676" alt="Screen Shot 2022-01-05 at 9 40 51 AM" src="https://user-images.githubusercontent.com/19259608/148264366-a2f50256-5c96-4f6a-b719-0833c9a729c2.png">

For reference I have followed this tut

![evilginx2 walkthrough](https://user-images.githubusercontent.com/19259608/148264419-d6ada400-65aa-4694-95a9-ebfa6f7bcb92.png)

When i visit, my domain currently an apache web page is showing, when i visit the link created by Evilginx2 , it doesn't work. 

Are there any walkthroughs showing steps setting up DNS and subdomains as I think this is where I'm doing something wrong?

**Comment by jayhill365** [comment]
https://github.com/kgretzky/evilginx2/issues/614 looks like a similar issue here

**Comment by jayhill365** [comment]
Feature suggestions: Make setup more clearer i'm not the only one here with this problem, I see similar issues are closed but no one really explains a fix.

**Comment by waitwhatwhen** [comment]
It's fine if you leave your namesevers on your host.
I always keep mine as ns1.digitalocean.com, ns2.digitalocean.com, ns3digitalocean.com, and never have any problems with the ACME error.
Also, you don't need to edit your /etc/hosts file to add in instagram? wtf. 
Then your tool would only be able to use one phishlet at a time. How absurd.

**Comment by jayhill365** [comment]
Thanks going to ignore adding anything to  /etc/hosts file . 
<img width="976" alt="Screen Shot 2022-01-05 at 7 27 57 PM" src="https://user-images.githubusercontent.com/19259608/148327462-cd59f174-18f3-4bed-b609-2ccebf2d093d.png">
<img width="735" alt="Screen Shot 2022-01-05 at 8 18 57 PM" src="https://user-images.githubusercontent.com/19259608/148327498-694bd44b-ac41-4157-95b3-3ac2b2b34a97.png">

Does this look correct to you? Still not sure why im getting 403's from what i can tell ive already correctly added subdomains to godaddy's domain manager @waitwhatwhen thanks for the reply here as well

**Comment by jayhill365** [comment]
Something else to note, when I added the new subdomains to the godaddy  domain manager it automatically assigned new IP's to each of the new subdomains not sure if this is why im still getting this same error

<img width="1214" alt="Screen Shot 2022-01-05 at 8 28 28 PM" src="https://user-images.githubusercontent.com/19259608/148328829-9ace931f-2e78-45e9-9002-38eeec5571f3.png">
.

**Comment by waitwhatwhen** [comment]
Might be a tad confusing because my domain starts with 'com-', but these are the basic settings I use every time without fail.
If my domain didn't start with 'com-', I would be adding 'facebook.com', 'm.facebook.com', 'static.facebook.com', 'www.facebook.com', etc.
Also, I just use A records. Fuck CNAME's. Also fuck adding in subdomains. DNS records are all you need.

<img width="1202" alt="Screen Shot 2022-01-06 at 3 26 07 pm" src="https://user-images.githubusercontent.com/96520621/148328570-1b7e038a-9a0f-4f2f-9e17-5361519dd7ab.png">

**Comment by jayhill365** [comment]
Well shit thanks for looking out i've been on this for 2 days straight im going to rip out Cnames, and delete the subdomains  I added and see if it works your way instead thanks @waitwhatwhen

**Comment by jayhill365** [comment]
Still not working on my end, does it look like im missing anything from what you can tell?
<img width="781" alt="Screen Shot 2022-01-05 at 9 01 06 PM" src="https://user-images.githubusercontent.com/19259608/148331254-ba40aa71-8445-41fd-a50c-96a2b319f03e.png">
<img width="1216" alt="Screen Shot 2022-01-05 at 9 05 48 PM" src="https://user-images.githubusercontent.com/19259608/148331473-4cf1379d-6773-469c-9f95-ada2681b3802.png">

looks like im still getting errors something to do with thre subdomain m.instagram.com and www.instagram.com

**Comment by jayhill365** [comment]
I figured out what was causing this issue, after getting the DNS records corrected, I needed to shut down the AWS DNS and webserver in order for evilginx to use 443 & set up TLS certs and proxy the request. The AWS server im using host its own dns server on local 53 which stops evilginx2. In order to fix the 403 error  what I did was first turn off the apache2 service, then I started evilginx2 using sudo, then enabled phishlets and I was finally able to setup the TLS.

**Comment by jayhill365** [comment]
https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help someone else out.

**Comment by starbwoy32** [comment]
> https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help someone else out.

how did you get you domain to say instgram.com [
![Screenshot 2022-01-16 192923](https://user-images.githubusercontent.com/56569794/149684364-44cdb474-f1c2-407f-8ff5-e99e052c5bfd.png)
](url)

**Comment by jayhill365** [comment]
> > https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help someone else out.
> 
> how did you get you domain to say instgram.com [ ![Screenshot 2022-01-16 192923](https://user-images.githubusercontent.com/56569794/149684364-44cdb474-f1c2-407f-8ff5-e99e052c5bfd.png) ](url)

yo @starbwoy32 thats a feature that comes with Evilginx2 and the premade phishlet they give you

**Comment by starbwoy32** [comment]
> > > https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help someone else out.
> > 
> > 
> > how did you get you domain to say instgram.com [ ![Screenshot 2022-01-16 192923](https://user-images.githubusercontent.com/56569794/149684364-44cdb474-f1c2-407f-8ff5-e99e052c5bfd.png) ](url)
> 
> yo @starbwoy32 thats a feature that comes with Evilginx2 and the premade phishlet for ig they give you.

Last question I read you blog. What is the purpose of putting evilginx2 link in gophish?

**Comment by jayhill365** [comment]
@starbwoy32 gophish is a super powerful tool, basically you'd use it to spam the link you created using evilginx2. There's a ton of information out about gophish check out there docs https://getgophish.com/documentation/

**Comment by WilKGoodangel** [comment]
> > > https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help someone else out.
> > 
> > 
> > how did you get you domain to say instgram.com [ ![Screenshot 2022-01-16 192923](https://user-images.githubusercontent.com/56569794/149684364-44cdb474-f1c2-407f-8ff5-e99e052c5bfd.png) ](url)
> 
> yo @starbwoy32 thats a feature that comes with Evilginx2 and the premade phishlet for ig they give you.

I am a bit lost it has been 4 days. are you saying that the domain name added to the server needs to be the one of the phishlet (e,g coinbase.com ) instead of the one I bought coinbase.com.es?
