### ISSUE TITLE
LinkedIn deactivates account after all authorizations

### ISSUE THREAD

**Issue by williamsjoe724** [kgretzky/evilginx2#697]

**Comment by newworldorder45** [comment]
I have opened this issue before (https://github.com/kgretzky/evilginx2/issues/680)  and there is no solution yet. 

@charlesbel (https://github.com/charlesbel) might be able to provide solution to this LinkedIn issue as he did for Google.

**Comment by charlesbel** [comment]
> I have opened this issue before (https://github.com/kgretzky/evilginx2/issues/680)  and there is no solution yet. 
> 
> @charlesbel (https://github.com/charlesbel) might be able to provide solution to this LinkedIn issue as he did for Google.

I'll take a look on it 😉

**Comment by newworldorder45** [comment]
@charlesbel great one. Looking forward to hearing back from you soonest.

**Comment by williamsjoe724** [comment]
@charlesbel  how can I reach you?

**Comment by williamsjoe724** [comment]
@newworldorder45 do you have telegram?

**Comment by newworldorder45** [comment]
@williamsjoe724 

My ICQ: @loggerjacky

**Comment by newworldorder45** [comment]
@charlesbel what's the progress?

**Comment by charlesbel** [comment]
> @charlesbel what's the progress?

Actually, linkedin detect the suspicious activity serversidely, and we can't do anything to it. But, we can make all the possible to fake linkedin data reportings... I am analyzing how linkedin send data and what are them. I will let you know (l'm a bit buzy)

**Comment by williamsjoe724** [comment]
@charlesbel how can I reach you?

**Comment by charlesbel** [comment]
> @charlesbel how can I reach you?

Telegram, find it on my github readme

**Comment by charlesbel** [comment]
> @charlesbel can I contact you via Telegram? 

For sure

**Comment by newworldorder45** [comment]
ok @charlesbel

**Comment by newworldorder45** [comment]
@charlesbel I have message you on Telegram.

**Comment by charlesbel** [comment]
After further inspections, it is very hard... Infact, I don't really know how they do it. I tried many things but it did not work...
