### ISSUE TITLE
From where can I get Google phishlet for evilginx2 plz

### ISSUE THREAD

**Issue by williamsjoe724** [kgretzky/evilginx2#698]

**Comment by asapx6** [comment]
You can reach how to the developer on icq @mrgretzky

**Comment by Kevin3-00** [comment]
> You can reach how to the developer on icq @mrgretzky

You are a scammer using kgretzky i.d to scamm people for phishlets guys beware of him

**Comment by rickyrik001** [comment]
yes ,you can contact me  rickyrik at protonmail.com
