### ISSUE TITLE
Blacklist is empty

### ISSUE THREAD

**Issue by BakkerJan** [kgretzky/evilginx2#699]
Hi @kgretzky ,

I have enabled "blacklist unauth", and it added a couple of IP addresses to the blacklist so far. I can see there are being blocked.
Now, I would expect them to show up in ~./evilignx/blacklist.txt, but the file seems empty.
When I set "blacklist off", it keeps blocking those sessions.

Any guidance around that, on how to clear that list?

**Comment by MelroyB** [comment]
Take a look in /root/.evilginx/

;)

**Comment by BakkerJan** [comment]
> Take a look in /root/.evilginx/
> 
> 
> 
> ;)

Thanks, that worked 👍
