### ISSUE TITLE
Can't create SSL certificate

### ISSUE THREAD

**Issue by Evilginx2User** [kgretzky/evilginx2#702]
I keep getting red and SSL creation certificate failed on Facebook and on my Coinbase phishlets how do I get it to work ??

**Comment by sunshine69645** [comment]
you have to wait for dns propagation, don't keep trying your requests will be blocked after many failed attempts.

**Comment by Evilginx2User** [comment]
How long do I have to wait for it to propergate ?  I've added everything on my digital ocean server and still it still shows red

**Comment by MelroyB** [comment]
What is the error message?
Is port 80 open?
Check DNS propagation here https://dnschecker.org/

and see  #686

**Comment by Evilginx2User** [comment]
![IMG_20220111_111506.jpg](https://user-images.githubusercontent.com/97452507/148924027-dc6d58f9-2f47-4e08-91f3-1be9fd300874.jpg)

I just got this now still same error again..

**Comment by MelroyB** [comment]
Do you have a other webserver running on port 80?

**Comment by Evilginx2User** [comment]
![IMG_20220111_112728.jpg](https://user-images.githubusercontent.com/97452507/148926051-841418ba-4545-4730-849b-d5c4cebcb472.jpg)

Is this correct ??

**Comment by Evilginx2User** [comment]
![IMG_20220111_112919.jpg](https://user-images.githubusercontent.com/97452507/148926239-bf86f9ee-07a9-4a98-aca3-0bdc2297dbbb.jpg)


That's what I got

**Comment by MelroyB** [comment]
can you login again with ssh?
the apache server is now stopped.

**Comment by Evilginx2User** [comment]
Ok I'm logged in now I'm enabling the Coinbase phishlet let me see if it's going to work..

**Comment by Evilginx2User** [comment]
![IMG_20220111_113953.jpg](https://user-images.githubusercontent.com/97452507/148927786-b82c0c5a-4cf6-42e4-92fa-2904004ba292.jpg)

I think it worked bro ...Ur blessed thanks I really appreciate..

**Comment by Evilginx2User** [comment]
![IMG_20220111_114128.jpg](https://user-images.githubusercontent.com/97452507/148928048-1d5c5a8c-11a0-474a-8903-f904a2a5ffe8.jpg)

But I'm I supposed to get those code's after SSL had been created ??

**Comment by Evilginx2User** [comment]
![IMG_20220111_114551.jpg](https://user-images.githubusercontent.com/97452507/148928682-7762831d-8c9f-436f-8427-9f7d88671713.jpg)

After generating the link this is what I got from the browser..

**Comment by Evilginx2User** [comment]
![IMG_20220111_123122.jpg](https://user-images.githubusercontent.com/97452507/148935215-397dec81-24b5-4f94-91e9-65b45fd3666d.jpg)

I'm getting this in most phishlets and the URL ends up not loading but the SSL certificate was successfully created..

**Comment by MelroyB** [comment]
If the certificates are requested on Letsencrypt. The first hour there are a bunch of web scanners visiting.
So set blacklist on ALL or UNAUTH
and the phishlet on hide.

Never set the lure path to / The scanners will detect the phishing site and reporting it as unsafe.

So if you set the blacklist on, and request a couple of certificates the blacklist will fill with most scanners
(run evilginx in --debug mode to see this)

If you mail the link set the phishlet on hide to prevent mail scanners to detect the phshing site for a couple of minutes

**Comment by Evilginx2User** [comment]
You know I'm new to this how do I set the blacklist on ?? And after doing that I shouldn't set the lures path ..

So I won't be receiving this errors after I on the blacklist ??

**Comment by Evilginx2User** [comment]
Also how do I set phishlet on hide ??

**Comment by MelroyB** [comment]
It is described in the readme.md:

Running phishlets will only respond to phishing links generating for specific lures, so any scanners who scan your main domain will be redirected to URL specified as redirect_url under config. If you want to hide your phishlet and make it not respond even to valid lure phishing URLs, use phishlet hide/unhide <phishlet> command

**Comment by MelroyB** [comment]
Blacklist: https://breakdev.org/evilginx-2-4-gone-phishing/

By default automatic blacklist creation is disabled, but you can easily enable it using one of the following options:

blacklist unauth
This will automatically blacklist IPs of unauthorized requests. This includes all requests, which did not point to a valid URL specified by any of the created lures.

blacklist on
This will blacklist IP of EVERY incoming request, despite it being authorized or not, so use caution. This will effectively block access to any of your phishing links. You can use this option if you want to send out your phishing link and want to see if any online scanners pick it up.

**Comment by Evilginx2User** [comment]
So I'll be using 
blacklist unauth for the issue to be settled right ??

**Comment by Evilginx2User** [comment]
![IMG_20220111_140235.jpg](https://user-images.githubusercontent.com/97452507/148947351-fc00e012-2e9b-459f-ad4f-22e5c676baa4.jpg)
So with this mode enabled I won't be having that issue anymore let me try setting up a phishlet

**Comment by Evilginx2User** [comment]
![IMG_20220111_140823.jpg](https://user-images.githubusercontent.com/97452507/148948235-f3a1e497-3d93-4b49-a401-2c4764913e7e.jpg)

I didn't get that error again when I tried setting up my PayPal phishlet

**Comment by Evilginx2User** [comment]
Some of my phishlets link ain't loading the phishing page it just shows a blank page .

**Comment by Evilginx2User** [comment]
![IMG_20220113_121402~2.jpg](https://user-images.githubusercontent.com/97452507/149321227-67b32951-5745-4767-b4de-29b3acce3e85.jpg)

Can anyone help out ??
How do I set my phishing URL to something like accounts.binance.mydomain.com
???

**Comment by Evilginx2User** [comment]
My own ip keeps getting blocked by evilginx2 after using blocklist unauth it keeps think I'm an unauthorized user...how do I fix this ?

**Comment by SuperbSonik** [comment]
> Do you have a other webserver running on port 80? Yes
> 
> Apache2 Debian Default Page
> 
> Stop apache and restart evilginx sudo service apache2 stop
Hi..

if stop apache service, the port 80 will be closed automatically isn't it?
