### ISSUE TITLE
Error message after target puts in email on office 365 

### ISSUE THREAD

**Issue by richardrance** [kgretzky/evilginx2#704]
Question. When I test the lure for MSoffice365, as soon as the email is put in I get an error message: 

"invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

I have redirect_url set to https://www.google.com

I will keep working on this, but I was wondering if this was a known problem. Thanks for this amazing tool. I will keep practicing until I master it.

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the target end..... You can reach how to the developer on icq @mrgretzky
