### ISSUE TITLE
Phishlets URL

### ISSUE THREAD

**Issue by Evilginx2User** [kgretzky/evilginx2#705]
![IMG_20220113_121402~2.jpg](https://user-images.githubusercontent.com/97452507/149320339-61576524-f0e1-4b12-b804-e5282d52e2dd.jpg)

How can I set my phishlets URL generated to look like this 
Accounts.binance.mydomain_name.com ??
Just like in the picture above..

**Comment by williamsjoe724** [comment]
rename your phish sub

**Comment by Evilginx2User** [comment]
Ok thanks ... My phishing pages doesn't load ..do you have an idea why ??and the SSL certificate was successfully created.

**Comment by Web3villian666** [comment]
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.
