### ISSUE TITLE
My phishing page isn't loading.

### ISSUE THREAD

**Issue by Evilginx2User** [kgretzky/evilginx2#706]
![IMG_20220111_114551.jpg](https://user-images.githubusercontent.com/97452507/149507633-04341c5d-1e19-4832-8bc9-56e370c1c252.jpg)

That's what I keep getting.

**Comment by Evilginx2User** [comment]
I keep getting this page isn't accessible by this address is the issue from my domain ??

**Comment by Horosh-epta** [comment]
Yes

**Comment by Evilginx2User** [comment]
Once I use a different domain your sure it's going to work out ??
