### ISSUE TITLE
My Coinbase and Gmail phishlets keeps giving me error 

### ISSUE THREAD

**Issue by Evilginx2User** [kgretzky/evilginx2#707]
After victim put his or her email it shows this for the Gmail phishlet ![IMG_20220115_125300.jpg](https://user-images.githubusercontent.com/97452507/149623897-dab1bdac-a880-4470-a689-2bf10e297631.jpg)

Then for the Coinbase it's just blank and tells me web page can't be accessed by the address..

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the target end..... You can reach how to the developer on icq @mrgretzky

**Comment by WilKGoodangel** [comment]
did you solve you issue? 

I am having an issue with my domain configurgation. 

> acme: Error -> One or more domains had a problem:
[assets.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for assets.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for assets.mydomain.com - check that a DNS record exists for this domain, url:
[cdn.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for cdn.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for cdn.mydomain.com - check that a DNS record exists for this domain, url:
[dynamic.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for dynamic.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for dynamic.mydomain.com - check that a DNS record exists for this domain, url:
[events.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for events.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for events.mydomain.com - check that a DNS record exists for this domain, url:
[exceptions.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for exceptions.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for exceptions.mydomain.com - check that a DNS record exists for this domain, url:
[google.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for google.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for google.mydomain.com - check that a DNS record exists for this domain, url:
[googletag.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for googletag.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for googletag.mydomain.com - check that a DNS record exists for this domain, url:
[images.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for images.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for images.mydomain.com - check that a DNS record exists for this domain, url:
[sessions.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for sessions.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for sessions.mydomain.com - check that a DNS record exists for this domain, url:
[ws.mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for ws.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for ws.mydomain.com - check that a DNS record exists for this domain, url:
