### ISSUE TITLE
Domain unauthorized issue 

### ISSUE THREAD

**Issue by SuperbSonik** [kgretzky/evilginx2#709]
Dear kgretzky,

I know this might be a little unrelated to evilginx2 but I am posting hoping maybe other users who has overcame this can give me a solution to my problem. *I built the mitm website is for my assignment, not for phishing public purpose.

I have been setting everything correctly according to the tutorial however I am hard stucked at one place which is as shown below..
![image](https://user-images.githubusercontent.com/61529488/149685901-8d0db900-9460-4a95-9147-d17a7529d523.png)

and I checked my webpage it shows this:
![image](https://user-images.githubusercontent.com/61529488/149686120-473f1127-3348-4920-bd10-019e90590687.png)
and while I inspect the page:
![image](https://user-images.githubusercontent.com/61529488/149686154-d8341c57-e3ac-48f6-8a0a-ddbeb7b23619.png)

I am really not sure how to solve this and the root cause of this..

My Freenom DNS A record:
![image](https://user-images.githubusercontent.com/61529488/149685967-5ada1e68-4359-491a-bf15-216c8713151a.png)

My Freenom Glue Record:
![image](https://user-images.githubusercontent.com/61529488/149686002-248f1cca-4e26-471e-a688-85ace1444629.png)

I am quite sure it was my problem, I might be setting DNS wrongly..

Sorry for the inconvenience caused, I thank the community in advance for provide any comments on my issues. Have a great day ahead, amazing people.

**Comment by MelroyB** [comment]
Check #702 , an other webserver is running

**Comment by SuperbSonik** [comment]
> Check #702 , an other webserver is running

Thanks a lot, mate! Will definitely look into this issue!

**Comment by SuperbSonik** [comment]
> Check #702 , an other webserver is running

I have already stop the apache2 service as shown in issue #702 . however, it still same:
![image](https://user-images.githubusercontent.com/61529488/150495211-6a96dd11-cea5-4f24-b46a-97e8212965f5.png)

after shutdown apache2 server, i perform nmap scan on local machine:
![image](https://user-images.githubusercontent.com/61529488/150495296-628f5922-5ae1-4ee2-a5b1-f1ca874229fe.png)

as shown, the port is closed. however, if i manually open it via ufw with allow http or 80, it shows the same issue on EvilGinx too . My host file in /etc as shown below:

![image](https://user-images.githubusercontent.com/61529488/150495449-f55241d3-ab29-4c88-931e-d61de5c1587d.png)

Truly appreciate if any guidance is provided.

**Comment by WilKGoodangel** [comment]
did you find a solution?

**Comment by jayhill365** [comment]
https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b follow my tut it might help

**Comment by SuperbSonik** [comment]
> did you find a solution?

yea, you may just follow jayhill article from the comment below, thanks.

**Comment by SuperbSonik** [comment]
> https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b follow my tut it might help

Thank you buddy for your generosity!
