### ISSUE TITLE
Okta phishlet not working 

### ISSUE THREAD

**Issue by jayhill365** [kgretzky/evilginx2#712]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

Are there any fixes for the okta phishlet as of now its automatically redirecting me toward another page .  going to double check if the key is correct in config 
<img width="932" alt="Screen Shot 2022-01-20 at 1 56 07 PM" src="https://user-images.githubusercontent.com/19259608/150428530-3a465d7f-1505-40d6-9036-ba459d6540c8.png">

**Comment by jayhill365** [comment]
got it working, just needed to add verification key and token at the end or the url, found out both by going to config and pulling they key and token at the end of the url created. ex: ?verification_key=verificationtoken

**Comment by Web3villian666** [comment]
I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your

**Comment by hydroponictrash** [comment]
1. Type `config` to get the verification token.
2. Run ` lures edit path <id> ?verification_key=verificationtoken` 
3. If that doesn't work try ` lures edit path <id> verification_key=verificationtoken` 
Or just the verification token. The goal is to make a lure attach to the correct verification token. Then your site should redirect to xxxxx.com/login/login.htm if everything else was done right.
