### ISSUE TITLE
Instagram phishlet can't accept cookie

### ISSUE THREAD

**Issue by borosmate** [kgretzky/evilginx2#713]
Can't accept cookie on instagram phishlet how can I solve this?

I got this in console "Uncaught w {name: 'AjaxError', message: '', stack: 'Error\n    at new w (https://www.XXXXXXX.xy/static/b…es6/ConsumerLibCommons.js/9df39bad3bb0.js:64:2129', framesToPop: 1, networkError: '', …}"

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky

**Comment by asapx6** [comment]
> 

What!!?  he just helped me out with my phishlets thought I let you guys know.... What ever you say dude Idgaf

**Comment by TheSilentNoob** [comment]
I have this problem tho and cant fix it !

**Comment by rdtm443** [comment]
...any solution for that yet? Same problem here, can't accept cookies. Would love to correct it by myself, but don't know where to start.

**Comment by rzmpzgeviii** [comment]
@rdtm443 same god damn, tell me you found the solution :,(
