### ISSUE TITLE
All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky

### ISSUE THREAD

**Issue by asapx6** [kgretzky/evilginx2#718]
All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky

_Originally posted by @asapx6 in https://github.com/kgretzky/evilginx2/issues/713#issuecomment-1030854522_

**Comment by Kevin3-00** [comment]
> All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky
> 
> _Originally posted by @asapx6 in [#713 (comment)](https://github.com/kgretzky/evilginx2/issues/713#issuecomment-1030854522)_

You are a scammer using kgretzky i.d to scamm people for phishlets guys beware of him

**Comment by asapx6** [comment]
What!!? He just helped me out with my phishlets issue.. thought I'd let you guys struggling with same issues know... Buh wat ever you say man IDGAF

**Comment by Jillsarkozi50** [comment]
> What!!? He just helped me out with my phishlets issue.. thought I'd let you guys struggling with same issues know... Buh wat ever you say man IDGAF

I contacted, you are the one managing the account.I asked him  to write through his official site or here and started giving excuses.I guess you think everyone is foolish here.
