### ISSUE TITLE
Your request couldn't be processed in Facebook phishlets

### ISSUE THREAD

**Issue by onceonce1** [kgretzky/evilginx2#724]
When open my fishiing site (Facebook) and I input login and pass  show message:Your request couldn't be processed in Facebook phishlets. In console I put only login without pass. It like on situation with my fishing site based instagram phishlets, but here other message: couldn't access to Internet.

**Comment by squodgeface** [comment]
I also have the same problem. See https://github.com/kgretzky/evilginx2/issues/729

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky

**Comment by syrex1013** [comment]
So, any updates on the tempalte?
