### ISSUE TITLE
Correction, reCaptcha can be proxied correctly via one phishing tool that supports base64 string transformations.

### ISSUE THREAD

**Issue by Jillsarkozi50** [kgretzky/evilginx2#726]
How to bypass Recaptcha while making custom phishlets?

**Comment by Kevin3-00** [comment]
Please can you give hints on how to do this I

**Comment by Kevin3-00** [comment]
I want to know how to do it myself this is what I'm talking about
    On Wednesday, February 16, 2022, 02:02:39 PM GMT-5, Evilginx2User ***@***.***> wrote:  
 
 


Rcaptcha Hcaptcha Cloudfare can be bypassed and I've bypassed it....

Send the phishlet I'll by pass it on my server I'll send you the link to confirm...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Evilginx2User** [comment]
You don't expect to learn something that's difficult to figure out publicly

@Lawson2_a1

That's my telegram....

**Comment by Evilginx2User** [comment]
It's not free!! Have something to return back either finds or knowledge...

**Comment by Kevin3-00** [comment]
Check your telegram I messaged already
    On Wednesday, February 16, 2022, 02:26:59 PM GMT-5, Evilginx2User ***@***.***> wrote:  
 
 


It's not free!! Have something to return back either finds or knowledge...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 456478** [comment]
lol i remember saying this. recaptcha is free...

**Comment by 456478** [comment]
[Hydra.pdf](https://github.com/kgretzky/evilginx2/files/8230316/Hydra.pdf)

**Comment by 456478** [comment]
> lol i remember saying this. recaptcha is free...

https://raw.githubusercontent.com/456478/reCAPTCHA-Phishing-Tool/main/HydraFINpdf.pdf

**Comment by Kevin3-00** [comment]
Why don't you quit wasting your time thinking you can scam me?
    On Sunday, March 13, 2022, 01:17:16 AM GMT-8, Rensowhitehat ***@***.***> wrote:  
 
 


I had similar issues the developer helped me with it... You can reach out to him on icq https://icq.im/mrgretzky

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
