### ISSUE TITLE
hostname unsupported

### ISSUE THREAD

**Issue by CraftedCat** [kgretzky/evilginx2#728]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

orig domain: domain.com.nz (example)
phis domain: evil.biz

I  cant proxy metric.cloud.domain.com.nz

cert for metric.cloud.domain.com.nz - wildcard, *.cloud.domain.com.nz
i have wildcard too *.evil.biz
but got error: hostname unsupported: metric.cloud.evil.biz

- {phish_sub: 'metric', orig_sub: 'metric', domain: 'cloud.domain.com.nz', session: true, is_landing: false} - not work
- {phish_sub: 'metric', orig_sub: '', domain: 'metric.cloud.domain.com.nz', session: true, is_landing: false} - not work
- {phish_sub: 'metric.cloud', orig_sub: 'metric.cloud', domain: 'domain.com.nz', session: true, is_landing: false} - not work

**Comment by asapx6** [comment]
All issues can be fixed.... It's cuased due to update on the targeted end..... You can reach how to the developer on icq @mrgretzky
