### ISSUE TITLE
the last step!!!!! 

### ISSUE THREAD

**Issue by netroyano** [kgretzky/evilginx2#73]
i have this problem!!!!

[www.facebook.com.netroyano.tk] acme: Error 400 - urn:acme:error:dns - DNS problem: NXDOMAIN looking up A for www.facebook.com.xxxx.tk
Error Detail:
	Validation for www.facebook.com.xxxx.tk:80
	Resolved to:
		
	Used:

**Comment by netroyano** [comment]
And the final messenge say:

Timeout during connect (likely firewall problem)

**Comment by keep-learning-go** [comment]
@netroyano  Likely Firewall Problem, means literally that Let'sEncrypt can't access port 80 on your host. If you are running Evilginx2 on a server behind NAT, you'll need to port forward port 80. But I recommend you to get some cheap VPS on DigitalOcean or Amazon AWS.
-
If you are facing this issue on VPS, check your firewall rules and allow 80 IN connections.
