### ISSUE TITLE
How to handle site redirection for Target Page?

### ISSUE THREAD

**Issue by ajayfuloria** [kgretzky/evilginx2#734]
Hi,

I have a target which redirects on to a different port when the URI is opened. 
How can I configure the phishlet to cater for this redirection on the target page.

Scenario
1. My target is abc.com/login
2. On opening the page the it redirects to abc.com:2200/login
3. My phishlet opens the page xyz.com/login but then goes to the actual page abc.com:2200/login

How can this be handled? 

Thanks.

**Comment by WilKGoodangel** [comment]
is your issue on the url side?
