### ISSUE TITLE
o365 not capturing cookies pls help

### ISSUE THREAD

**Issue by williamsjoe724** [kgretzky/evilginx2#737]

**Comment by Maxim0n** [comment]
The o365 phislet captures the cookies but does not store it to sessions. If you create an additional phishlet for example wordpress and use that, the sessiondata includes both the o365 token as the wordpress token in the json array.

**Comment by JM-Lemmi** [comment]
Did you try the fix from #676?

**Comment by Web3villian666** [comment]
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.
