### ISSUE TITLE
manual ssl cert creation for phishlets

### ISSUE THREAD

**Issue by kwisatzhadierach** [kgretzky/evilginx2#739]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

Is it possible to manually implement lets encrypt and store it in the folder before enabing the phishlets? I keep getting acme errors even after following the fixes shown in the issue
<img width="1680" alt="Screen Shot 2022-03-03 at 6 29 58 PM" src="https://user-images.githubusercontent.com/100869641/156628939-8f35c579-e912-4afa-89da-87edb4841c90.png">
s

**Comment by WilKGoodangel** [comment]
are you using it locally or on a VPS?

**Comment by kwisatzhadierach** [comment]
i am using it on a vps

**Comment by Web3villian666** [comment]
I had similar issues it got sorted with help of the developer..... Y'all can reach support on icq @mrgretzky
