### ISSUE TITLE
I can help you with evilginx2 installation, making phishlets and google issue

### ISSUE THREAD

**Issue by rickyrik001** [kgretzky/evilginx2#740]
If the issue is small i will love to help you freely and also i am open for discussion but if it will take time i will charge some bucks, Thanks 
Note : Don't ask for blockchain or any credit card phishlets which involve steeling money 
my contact :  rickyrik at protonmail.com
Telegram : Ricky_rik1

**Comment by Whytfaz** [comment]
Thanks!!! Been battling with for days bro

**Comment by ringxzero** [comment]
i have a problem i have been working all day on yesterday. i keep getting this error. 

acme: Error -> One or more domains had a problem:
[b.stats.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for b.stats.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for b.stats.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[c.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for c.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for c.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://www.htmlconnecting.com/.well-known/acme-challenge/3OPJ9ODpeWwqNkTzRH-jiVAOFs8jrr7h6ez6C6ytiZo [137.184.150.196]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</ce", url:


i set my nameservers on go daddy to my digitalocean droplet and set my A's in the digitalocean DNS like im supposed to but still im having DNS issues. 

heres my digitalocean DNS setup 

	
(A) mydomain.com	directs to   <MydropletIP>
(A) www.mydomain.com directs to <mydropletIP>
(NS) mydomain.com directs to ns1.digitalocean.com
(NS)mydomain.com directs to ns2.digitalocean.com
(NS)mydomain.com directs to ns3.digitalocean.com

and on my go daddy account where my domain is registered pretty much all i  have is my nameservers pointed to digital ocean

ns1.digitalocean.com and
sn2.digitalocean.com

ive tried ALOT of things and its still a problem.

**Comment by Web3villian666** [comment]
I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your

**Comment by klumren1** [comment]
This guys a ripper be aware

**Comment by rickyrik001** [comment]
If you don't know how to use evilginx then it is not my problem .. :)

**Comment by mrviularry** [comment]
> This guys a ripper be aware

Nah, this is a shitty comment, Rikky has been working on evilginx before you knew what the internet is.. Learn how to use evilginx

**Comment by klumren1** [comment]
> > This guys a ripper be aware
> 
> Nah, this is a shitty comment, Rikky has been working on evilginx before you knew what the internet is.. Learn how to use evilginx

lol when problem arise he run, he makes false promises, he lies, if any potential customer of his is seeing this if you want full transparency with a service I recommend https://t.me/nakedpages before using rikky

**Comment by rickyrik001** [comment]
@klumren1 Bro I told you again ,first learn how to use evilginx you don't know even a single command how you ran the tool ? and people I worked with know who I am ,so I don't need your certificate to proof anything :)

**Comment by klumren1** [comment]
I told you before purchase I won’t know how to use, you said you will help me set everything up, you have been nothing but useless, you even promised to send my money back then proceeded to block me

**Comment by klumren1** [comment]
I recommend users use nakedpages instead

**Comment by klumren1** [comment]
![81FFCDA9-6288-4E95-B7A9-D6C1BEBC286A](https://user-images.githubusercontent.com/112618432/191245604-aff4e378-363d-491f-9265-598e66e6ae39.jpeg)

**Comment by rickyrik001** [comment]
@klumren1 i was trying to help you from last 3 weeks but you are so dump that you didn't know even basic commands of linux and you don't know how to even use evilginx.
![screenshot](https://user-images.githubusercontent.com/89962590/191366648-07657624-fbb7-42c9-8756-6e3d20781700.png)

**Comment by klumren1** [comment]
Your lying, before I sent you the money you agreed to help me set up everything even after I told you I can’t use evilginx, 2 weeeks your google page was not working, when I  first brought the issue to you that your page was not working you agreed in 24 hours that if page is still not working you will send me the money. The 24 hours came what did you do ? You blocked me. I then msged you from another telegram where you said that you needed the btc for your sick mother in hospital that I should give you a chance to make things right for 2 weeks back and forth I was going with you to release my money your excuse for not releasing was that your working on a fix. Now the 2 weeks has come and you claim your service is up and running to help me set up as you first agreed, you are refusing. The matter of fact is and the conclusion is that you are not a trustworthy guy or neither are you a man of your word. You are more like a bitch, whose ego is so high but for no reason at all

**Comment by klumren1** [comment]
If you use @nakedpages it is better than evilginx you won’t go through the headaches of setting up etc it’s all done for you automatically

**Comment by rickyrik001** [comment]
@klumren1 I agree I took 4days time because at that time it was patch so I need time to fix it ,once I fixed i gave you all things ,except this all other is lie ,peace bro :)  don't waste your time here do something productive ,learn few commands of Linux,learn how to use the tool :)

**Comment by klumren1** [comment]
4 days ?😂😂😂😂😂😂😂😂😂😂

**Comment by klumren1** [comment]
anyways guys use @nakedpages on telegram don’t waste your money with this guy

**Comment by klumren1** [comment]
This is what you say after you blocked my main acc when it was time to send my money back your reason for not sending back cause I am spammer and your not so money should be easy for me to accumulate 😂😂😂😂
![Uploading A1AED4EA-0FE6-431D-92C1-559B432685EC.png…]()

**Comment by klumren1** [comment]
![Uploading A00C9CE0-2131-4721-90DE-8FA0A9896A0D.png…]()

**Comment by klumren1** [comment]
![Uploading 6A9B8CFC-D14F-4C3B-8484-8792ACFB8F00.png…]()

**Comment by klumren1** [comment]
https://ibb.co/7j94bxF

**Comment by klumren1** [comment]
https://ibb.co/WHNPKzm
when google riky 😂😂 blocked me his excuse was that I was messaging him constantly when instead it was the deadline for him to refund my money

**Comment by rickyrik001** [comment]
It's not about money ,if I deliver you thing that is working correctly and yes you are asking for refund I will refund you and if I am not able to solve the issue ,but I did ! And you can ask anyone  to whom I provide services they all satisfied from me ,but you don't know any thing about evilginx not even a single command you know ! You want me to teach you from begining and also teach you how to run Linux sever how to login it ,my friend no one has time to do this !!

**Comment by klumren1** [comment]
Ok so why would you clear conversation and delete all the information that I need after collecting my money ?

**Comment by klumren1** [comment]
🤡

**Comment by klumren1** [comment]
Misunderstanding Ricky fixed my issues
