### ISSUE TITLE
DNS problems, i think. i have tried everything i can think of.  put a lot of time into trying to fix this. 

### ISSUE THREAD

**Issue by ringxzero** [kgretzky/evilginx2#741]
MY ERROR as is below

acme: Error -> One or more domains had a problem:
[b.stats.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for b.stats.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for b.stats.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[c.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for c.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for c.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[c6.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for c6.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for c6.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[hnd.stats.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for hnd.stats.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for hnd.stats.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[t.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for t.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for t.www.htmlconnecting.com - check that a DNS record exists for this domain, url:
[www.htmlconnecting.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://www.htmlconnecting.com/.well-known/acme-challenge/3OPJ9ODpeWwqNkTzRH-jiVAOFs8jrr7h6ez6C6ytiZo [137.184.150.196]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</ce", url:
[www.www.htmlconnecting.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.www.htmlconnecting.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.www.htmlconnecting.com - check that a DNS record exists for this domain, url:

My DNS settings as is below 

DIGITALOCEAN

	
(A) mydomain.com	directs to   <MydropletIP>
(A) www.mydomain.com directs to <mydropletIP>
(NS) mydomain.com directs to ns1.digitalocean.com
(NS)mydomain.com directs to ns2.digitalocean.com
(NS)mydomain.com directs to ns3.digitalocean.com

no DNS settings aviable on godaddy because i set the godaddy nameservers to ns1.digitalocean.com and sn2.digitalocean.com

going to my domain and its ip both pull up my ocean droplet and show welcome to nginx! 

i work all day yesterday trying to fix this and put a entire day into this. so its easy to say ive tried everything i know. its just hard finding the right info online to fix this issue.

**Comment by ringxzero** [comment]
both (A) records direct to my droplet IP whats hosting everything

**Comment by ringxzero** [comment]
![nameservers](https://user-images.githubusercontent.com/101017533/156897726-437dfe79-4003-4fbf-ae09-8d5b4b09fdd7.png)
![myDNSsettings](https://user-images.githubusercontent.com/101017533/156897730-636bfe77-0877-47de-a2b0-6305089d3e8f.png)

**Comment by ringxzero** [comment]
the first pic is of my config on godaddy. just the namesevers changed 2 digitalocean.

**Comment by WilKGoodangel** [comment]
you need to create an AAA record too

**Comment by jepunband** [comment]
this might help : https://github.com/kgretzky/evilginx2/issues/296#issuecomment-505259964

**Comment by Iro4you** [comment]
You have to buy a domain, example cloudfare and add dns records on cloudfare. and then run evilginx
