### ISSUE TITLE
o365 automaticallly redirects to youtube video help please?

### ISSUE THREAD

**Issue by officialdedsec** [kgretzky/evilginx2#742]
hey i sucessfully setup evilginx all are working fine but when i try to click login or sign in of phishlet o365 then browser automatically redirects me on a youtube video i also set redirect url but nothing works anybody please help me about this issue?

**Comment by HornyLemur** [comment]
you need to edit the redirect URL of the lure in evilginx like this

**lures create [phishlet name]**
**lures edit [id #] redirect_URL [url of site you want them to go to]**

**Comment by Web3villian666** [comment]
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.
