### ISSUE TITLE
get directory at 'https://acme-v02.api.letsencrypt.org/directory'

### ISSUE THREAD

**Issue by spektr001** [kgretzky/evilginx2#744]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

Greetings.

Tried to enable instagram phishlet.

But I'm getting this.

`[13:12:25] [inf] setting up certificates for phishlet 'instagram'...`
`[13:12:25] [war] failed to load certificate files for phishlet 'instagram', domain 'instagram.pentest.ga': open /root/.evilginx``/crt/instagram.pentest.ga/instagram.crt: no such file or directory`
`[13:12:25] [inf] requesting SSL/TLS certificates from LetsEncrypt...`
`[13:12:34] [!!!] get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": EOF`
`[13:12:34] [inf] disabled phishlet 'instagram'`

I solved a lot of problems and I think that if I solve this problem, everything will success.

Thanks in advance.

**Comment by Cyphercoda** [comment]
any update on this ticket?

**Comment by talk2noob** [comment]
facing same issue, any resolution?
and sometimes getting this, Get https://acme-v02.api.letsencrypt.org/directory: net/http: TLS handshake timeout

**Comment by faccboy** [comment]
I'm having the same issue, how to solve this TLS Cert issue?
