### ISSUE TITLE
is it possibe SEND SESSIONN REPORTS to Telegram or ICQ or EMAIL

### ISSUE THREAD

**Issue by authverify** [kgretzky/evilginx2#753]

**Comment by gsmthconsult** [comment]
lovely, kindly give an update on progress of the notifier project

**Comment by JM-Lemmi** [comment]
I am waiting for clearance from work to publish the PR.

**Comment by rickyrik001** [comment]
@gsmthconsult  if you need any help you can contact me on telegram @Ricky_rik1

**Comment by gsmthconsult** [comment]
> I am working on E-Mail notifiers. See my fork: [cirosec-studis/evilginx2](https://github.com/cirosec-studis/evilginx2)
> 
> It is based on the Webhook Notifiers from PR #606.
> 
> Feel free to also add a Telegram notifier method, the framework for different delivery methods is there!

great work. you have telegram or icq ?

**Comment by Web3villian666** [comment]
I got latest o365 phishlets off kgretzky..... Y'all can reach support on icq @mrgretzky

**Comment by darkxlord0147** [comment]
> I am working on E-Mail notifiers.
> 
> It is based on the Webhook Notifiers from PR #606.
> 
> Feel free to also add a Telegram notifier method, the framework for different delivery methods is there!

I am working with the telegram method. I get visitors and unauthorized notifications but I Don't get authenticated notifications.  how did you get your to work.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
