### ISSUE TITLE
NEW 0365 PHISHLETS WORKS GOOD

### ISSUE THREAD

**Issue by Web3villian666** [kgretzky/evilginx2#758]
I got latest o365 phishlets off kgretzky..... Y'all can reach support on icq @mrgretzky

**Comment by gsmthconsult** [comment]
what's your icq ?

**Comment by rickyrik001** [comment]
Cool lots of people have .

**Comment by Jillsarkozi50** [comment]
> 
You can't seem to stop opening new profiles everytime since you already know you are here to scam people.If  kgretzky got any he would update it here officially,why would he need you to deliver his update backdoors?

**Comment by Jillsarkozi50** [comment]
> I got latest o365 phishlets off kgretzky..... Y'all can reach support on icq @mrgretzky

So you just opened this git profile and the first message would be from  kgretzky really?how dumb could you be bro?

**Comment by ZzzHarry** [comment]
working o365 phishlets captures token, telegram me @ghoxt007, for evilginx setup

**Comment by serikioluwagbenga** [comment]
Please I need someone who can help me with the installation.. 
Please you can email me on serikioluwagbenga@gmail.com
