### ISSUE TITLE
Change the condition of content type definition

### ISSUE THREAD

**Issue by redlocks** [kgretzky/evilginx2#761]
https://github.com/kgretzky/evilginx2/blob/511860ca993b73e0d412c372c8aaa4b70ba5a7e1/core/http_proxy.go#L436

At the moment the condition is not satisfied with "application/json;charset=UTF-8", you need to replace string matching with substring search.

`if strings.Contains(contentType, "application/json"){}`

**Comment by Web3villian666** [comment]
I got latest o365 phishlets off kgretzky..... Y'all can reach support on icq @mrgretzky
