### ISSUE TITLE
Cert on local domain

### ISSUE THREAD

**Issue by kileyturney** [kgretzky/evilginx2#765]
Hello
Anyone can tell me how to setup evilginx2 on local machine (kali linux) with necessary certs?
I am installed and run evilginx, but don't know how to setup certificate

**Comment by kileyturney** [comment]
I am found information
on running need to use key -developer
and
change /etc/hosts file

**Comment by Web3villian666** [comment]
I had similar issues I got in touch with the developer on icq @mrgretzky
