### ISSUE TITLE
o365 issue with domain name

### ISSUE THREAD

**Issue by cmsth** [kgretzky/evilginx2#766]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

Hi, i have an issue with my evilginx, can some1 dm me on telegram ? based on o365 

telegram : https://t.me/KOS_betting

**Comment by ghoxt007** [comment]
message me on telegram @ghoxt007 i will set up evilginx for u, and theres a working O365 phishlet

**Comment by 456478** [comment]
o365 phishlet:t #778
