### ISSUE TITLE
Guide to create Phishlet

### ISSUE THREAD

**Issue by BraQwesi** [kgretzky/evilginx2#77]
Can you please write a guide to create phishlets of other social media and mail services

**Comment by decidedlygray** [comment]
This would be nice. In the meantime, for anyone who needs it, this podcast covers phishlets in enough detail to get started - https://www.youtube.com/watch?v=GDVxwX4eNpU

**Comment by kgretzky** [comment]
Yes, I eventually want to do that, but no ETA at this point.
