### ISSUE TITLE
How to fix office365 phishlets domain unable to grab cookies?

### ISSUE THREAD

**Issue by Manmade404** [kgretzky/evilginx2#772]

**Comment by Web3villian666** [comment]
I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your issue mate.

**Comment by Kevin3-00** [comment]
> I worked my o365 phishlets with the author on icq https://icq.im/mrgretzky now forwarding results to mail..... So I believe could fix your issue mate.

Why not go stop wasting your time here bro?

**Comment by 456478** [comment]
To capture cookies apply this patch https://github.com/kgretzky/evilginx2/pull/178#issuecomment-459979893

Add /kmsi* to auth_urls

**Comment by ghoxt007** [comment]
i fix it for you telegram me @ghoxt007

**Comment by 456478** [comment]
try my o365 phishlet #778

**Comment by Manmade404** [comment]
Thanks man @mrgretzky

**Comment by Kevin3-00** [comment]
> Thanks man @Mrgretzky

If you don't stop using gretzky to scamm people here then expect worst,go and do that in the wild here is to share ideas not to practice scamm fool
