### ISSUE TITLE
Unauthorised request warning.

### ISSUE THREAD

**Issue by GAMhackER** [kgretzky/evilginx2#773]
How to work around this? Also, every URL redirects to a youtube video.
![Screenshot 2022-05-07 211821](https://user-images.githubusercontent.com/37270471/167261782-94cd8596-5988-48f0-a177-843ef0035969.png)

**Comment by Manmade404** [comment]
You can reach out to the developer on icq @mrgretzky he helped me once on similar issues

**Comment by AlphaByte-RedTeam** [comment]
I have a similar issue.
![warning](https://i.imgur.com/luyWhOw.png)

**Comment by AlphaByte-RedTeam** [comment]
> I have a similar issue. ![warning](https://camo.githubusercontent.com/4dcef70799ed854c219b576928eff9aa2a6ea482314cf2202d65a4442d8401dc/68747470733a2f2f692e696d6775722e636f6d2f6c757957684f772e706e67)

Oh I have fixed this issue now. But technically I don't fix anything. It's just a warning related to DNS issue. If you setup your DNS correctly, you just have to wait for about 1-2 hours for the DNS to cache.
