### ISSUE TITLE
How To Add Phishlets on Evilginx2 

### ISSUE THREAD

**Issue by YoungMoney01** [kgretzky/evilginx2#779]

**Comment by cashtro28** [comment]
open evinx folder
then open phishlets in terminal
pick a yaml file to duplicate
'cp <original_yaml_file> <your_new_yaml_file'>
then 
'nano <your_new_yaml_file>

**Comment by YoungMoney01** [comment]
My bro thanks but I can’t not find evilginx2 folder of my vps in Linux why? Please drop me your telegram ID boss 🙏🙏

**Comment by YoungMoney01** [comment]
My phishing page, send me your telegram ID please
