### ISSUE TITLE
Bots crawling prevention

### ISSUE THREAD

**Issue by pentest01** [kgretzky/evilginx2#785]
How does evilginx prevent bot crawling your lure id, or is there a way to configure evilginx to work with redirect rules.

**Comment by Jamesmich12** [comment]
Yes there's a way to hide it from bots

**Comment by Manmade404** [comment]
> Yes there's a way to hide it from bots

How can I do that?

**Comment by nakedpages** [comment]
Checkout nakedpages https://github.com/nakedpages/nakedpages

**Comment by oldkingcone** [comment]
id suggest looking into something with 

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

and maybe some PHP for the uncaught ones.

**Comment by Kevin3-00** [comment]
> id suggest looking into something with
> 
> https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker
> 
> and maybe some PHP for the uncaught ones.

Looks promising but have you personally tested it with evilgin link?

**Comment by oldkingcone** [comment]
i have not, but i only use nginx.

**Comment by Kevin3-00** [comment]
> i have not, but i only use nginx.

I went through it long steps just want to be sure it works before following such steps

**Comment by Kevin3-00** [comment]
> i have not, but i only use nginx.

I followed you is there a way I can pm you?
