### ISSUE TITLE
microsoft page is detecting credentials immediately when the credentials has been input

### ISSUE THREAD

**Issue by kris8080** [kgretzky/evilginx2#786]

**Comment by Manmade404** [comment]
Not true..... I got a working o365 phishlets off @kgretzky on icq and works gud

**Comment by captaindd1** [comment]
@Manmade404 here my icq719964852

**Comment by newworldorder45** [comment]
@Manmade404

> @Manmade404 here my icq719964852

THIS GUY IS A RIPPER

![Capture](https://user-images.githubusercontent.com/97228608/177001836-783e1794-d1a6-4e6b-9034-d6b8415e1a94.JPG)
![Capture2](https://user-images.githubusercontent.com/97228608/177001839-96644dba-cad9-4a66-8d84-233f290c4507.JPG)
