### ISSUE TITLE
'redirect_uri' is not valid

### ISSUE THREAD

**Issue by DanMinihanNACS** [kgretzky/evilginx2#789]
Full error: 
We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

I'm getting this error after entering an office 365 email using the o365.yaml phishlet. It seems to be an issue with not registering my web page with Azure app registrations. Is there any way around this without registering my app on Azure?

**Comment by Trippleson** [comment]
bro....the tool has been programmed already.....you would have to edit it....for it to work on O365,gmail and some other financial institution websites

**Comment by jeffaf** [comment]
As far as I can tell the o365 phishlet doesn't work anymore. I assume something has changed on Microsoft's side.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
