### ISSUE TITLE
### DNS Problem ["UNIT APACHE2.SERVICE NOT LOADED."]

### ISSUE THREAD

**Issue by ljackson140** [kgretzky/evilginx2#791]
### DNS Problem ["UNIT APACHE2.SERVICE NOT LOADED."]

I have followed this tutorial and a bunch other more as seen down below. 

1. https://mrturvey.co.uk/how-to-phish-for-passwords-and-bypass-2fa/
2. https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b 

Second link is to fix DNS. 

This is the message after trying to stop all of the ports 
![image](https://user-images.githubusercontent.com/62328065/175320436-5af5d59e-cd01-43e5-a7a1-8f366bbbfe0f.png)

I think this is the main problem everyone is facing, whilst i was searching through the issues log. And **YES** i have changed the nameserver within the **“/etc/resolv.conf”** text file to point towards _google._

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
