### ISSUE TITLE
My recaptcha issues fixed by @mrgretzky on icq

### ISSUE THREAD

**Issue by Manmade404** [kgretzky/evilginx2#794]

**Comment by newworldorder45** [comment]
@mrgretzky on icq is  RIPPER

![5679-d38f-cf5b-984b](https://user-images.githubusercontent.com/97228608/176997834-8c5ff893-bf41-4656-8a03-17281c31db10.png)

**Comment by newworldorder45** [comment]
@mrgretzky on icq RIPPED me of $400

**Comment by newworldorder45** [comment]
![Capture](https://user-images.githubusercontent.com/97228608/176997876-4c8267fb-a622-47dc-888a-56989a299c64.JPG)
