### ISSUE TITLE
error with SSL

### ISSUE THREAD

**Issue by pentest01** [kgretzky/evilginx2#799]
I get this error when evilginx2 is requesting for certificate

![Screenshot_2022-07-09_23_27_05](https://user-images.githubusercontent.com/103268912/178130878-a44e6f7a-7910-4ac2-b3d2-7a4c665f803e.png)

**Comment by JM-Lemmi** [comment]
The error in the Screenshot shows you the issue: `temporary failure in name resolution`. Your DNS resolution is not working correctly.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Comment by pentest01** [comment]
Sorry, that was a while ago. I left it open for other users as reference. I’ll close now.

**Comment by pentest01** [comment]
@Support-1535 i haven’t been able to get it to work yet, is there any way you can help?

**Comment by Support-1535** [comment]
If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
