### ISSUE TITLE
hostname unsupported error

### ISSUE THREAD

**Issue by gsparks77** [kgretzky/evilginx2#80]
Hello,

I'm hoping you can help me out with what is likely a simple setup issue. I'm on Kali, and I've set up evilginx2 (installed from source).

## What I'm Working With
I've pointed my nameservers for my domain, let's just call it `phishdomain.com`, to my evilginx2 server. I have debug mode enabled, and I see debug messages like `DNS A: subdomainhere.phishdomain.com = 123.123.123.123` logged when my browser tries to pull up the phishing page, which indicate the DNS server is properly serving up IPs for my domain.

Here is a basic summary of how I started up evilginx:
```
# sudo evilginx -debug
: config domain phishdomain.com
: config ip 123.123.123.123
: config redirect_url https://www.google.com
: phishlets hostname citrix phishdomain.com
: phishlets enable citrix
: phishlets unhide citrix
```

## The Issue I'm Seeing
On my client machine I try to pull up the site, either directly or by using a url provided by `phishlets get-url citrix https://www.google.com`, and I either get a connection timeout or an error message saying the SSL message returned was too long.

Server-side in the debug logs I see messages like this:
```
[22:36:57] [dbg] DNS A: subdomainhere.phishdomain.com = 123.123.123.123
[22:36:57] [dbg] hostname unsupported: subdomainhere.phishdomain.com
```

## What I've Tried to Fix It

I've of course read your blog post, read the README, and watched that BHIS podcast. Nothing there seemed to help.

I've played with variations on starting up and configuring evilginx. For example, setting `subdomainhere.phishdomain.com` as my `phishlets citrix hostname` as well as my `config domain`. I've tried it without using `unhide`. I've tried it with and without the `config redirect_url`.

I've also started digging into the code [here](https://github.com/kgretzky/evilginx2/blob/6ee43961b86b332c23e973ac46bb71035acfb223/core/http_proxy.go#L575) where the error message is printed from, which then lead me to [here](https://github.com/kgretzky/evilginx2/blob/6b40db172b757910ec9d0c6459565f4669ba8632/core/config.go#L294) which is the check performed to trigger that debug message. It looks like it checks `activeHostnames` for the string provided and if it doesn't see it (makes it through the loop) it returned false. It looks like `activeHostnames` is supposed to be a list of sites enabled, but I thought I've already enabled the site?

Any help would be greatly appreciated

**Comment by kgretzky** [comment]
Can you send me the output of `phishlets` command so that I can see the hostname and status of the phishlet?

**Comment by DarknightCanada** [comment]
Hello! I am having the same issue! what is the fix for it?
