### ISSUE TITLE
I keep getting my this message when ever I try

### ISSUE THREAD

**Issue by cashboy08** [kgretzky/evilginx2#800]
root@debian-s-1vcpu-1gb-intel-sfo3-01:~# sudo ./bin/evilginx -p ./phishlets/
sudo: ./bin/evilginx: command not found

When I input this command it this message 
<command not found

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
