### ISSUE TITLE
threat actor selling phishlets https://github.com/trewisscotch/PHISHLET-EVILGINX2- thought you should know

### ISSUE THREAD

**Issue by joewaller99** [kgretzky/evilginx2#801]

**Comment by joewaller99** [comment]
this threat actor is selling phishlets 


https://github.com/trewisscotch/PHISHLET-EVILGINX2-

**Comment by Kevin3-00** [comment]
> this threat actor is selling phishlets
> 
> https://github.com/trewisscotch/PHISHLET-EVILGINX2-

He is a complete scammer don't try to buy from him after payment he will block you.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
