### ISSUE TITLE
Cloudflare bypass

### ISSUE THREAD

**Issue by kileyturney** [kgretzky/evilginx2#802]
Can anybody explain how bypass cloudflare check.
When I am try to access to site throw phish I am got error "This web property is not accessible via this address."

How to bypass is?

**Comment by Manmade404** [comment]
That's not cloudflare... Reach out to the developer on icq @mrgretzky

**Comment by Kevin3-00** [comment]
> 

Don't follow or reach out to  @Mrgretzky he's a scammer pretending to be the coder of evilginx2

**Comment by newworldorder45** [comment]
This is @Mrgretzky username on Github here: "Manmade404"

He is a thief

**Comment by mghtyspm** [comment]
@kileyturney were you able to solve your issue?
I am currently faced with the same issue with the coinbase phishlet.
Thank you.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
