### ISSUE TITLE
Failed to obtain certificates

### ISSUE THREAD

**Issue by puppyland** [kgretzky/evilginx2#81]
Can anyone help with this issue, while trying to enable (phishlets enable twitter) i get error stating that "Timeout during connect (likely firewall problem)
failed to obtain certificates.

i already disabled my firewall in kali linux running as a guest machine.
this is taking forever to fix any help with this please.
do i need to install letsencrypt before SSL certificate can be obtained because i noticed while trying to enable the phishlets, the link does not have a secure layer, only HTTP and no S.

**Comment by kgretzky** [comment]
Is the host you are running evilginx on, reachable from the outside?

**Comment by Eliot4** [comment]
I've got same problem and yes mine is reachable from the outside

**Comment by kgretzky** [comment]
It's likely the same issue with improper nameserver configuration #89
