### ISSUE TITLE
Site goes on about:blank

### ISSUE THREAD

**Issue by lor901** [kgretzky/evilginx2#815]
My PayPal phishlet works fine, when it asks for an image captcha it works and redirects me to log in. But about a second into the page, it instantly redirects me to about:blank. I literally need to continuously open the page and try to type but it just instantly puts me back to about:blank. Everything is configured fine. This is a bug, any help?

**Comment by oldkingcone** [comment]
have you tried screaming at it?

**Comment by lor901** [comment]
> have you tried screaming at it?

Yep, didn't work.

**Comment by hopcross1994** [comment]
im having same problem when trying to use paypal

**Comment by lor901** [comment]
> im having same problem when trying to use paypal

Same, no solution yet.

**Comment by p1nngu** [comment]
Same problem .. im not sure why it is happening but it does only on paypal

**Comment by lor901** [comment]
> Same problem .. im not sure why it is happening but it does only on paypal

Due to their security, I'm pretty sure.
