### ISSUE TITLE
phishlets start working but is not capturing anything 

### ISSUE THREAD

**Issue by WoxFi** [kgretzky/evilginx2#818]
I tried to install this on Ubuntu 20 , 
the process works good , instead of pointing my name server to my server ip 
i created individual DNS records in my another server 
ssl certificates obtaining is successful 

when i land the lure page , and i login it does not captures anything  just the username for amazon , nothing for protonmail , and i cant even pass the allow cookies option for instagram 

AM i missing something

**Comment by Jackramsdel** [comment]
I got a working boa phishlets  off @mrgretzky on icq... can help out

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
