### ISSUE TITLE
Acme

### ISSUE THREAD

**Issue by Zeze03** [kgretzky/evilginx2#821]
Code:
Port 80 is presumably open

[17:02:26] [inf] enabled phishlet 'coinbase'
[17:02:26] [inf] setting up certificates for phishlet 'coinbase'...
[17:02:26] [war] failed to load certificate files for phishlet 'coinbase', domain 'coinbase.evil-testbed-kali.com': open /root/.evilginx/crt/coinbase.evil-testbed-kali.com/coinbase.crt: no such file or directory
[17:02:26] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[17:02:48] [!!!] acme: Error -> One or more domains had a problem:
[assets.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for assets.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for assets.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                 
[cdn.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for cdn.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for cdn.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                          
[coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                                      
[dynamic.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for dynamic.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for dynamic.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:              
[events.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for events.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for events.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                 
[exceptions.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for exceptions.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for exceptions.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:     
[google.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for google.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for google.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                 
[googletag.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for googletag.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for googletag.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:        
[images.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for images.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for images.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                 
[sessions.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for sessions.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for sessions.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:           
[ws.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for ws.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for ws.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                             
[www.coinbase.evil-testbed-kali.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.coinbase.evil-testbed-kali.com - check that a DNS record exists for this domain, url:                      

I've never gotten past this error. I bought the domain from namecheap.com, digital ocean vps with an A record for every variation of coinbase.com for this site. Any help would be appreciated.

**Comment by Support-1535** [comment]
Hello,

Make sure you have correctly created the dns records for that domain.

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
