### ISSUE TITLE
Syntax error for a lure

### ISSUE THREAD

**Issue by Zeze03** [kgretzky/evilginx2#822]
input "lures edit redirect_url 0 https://www.coinbase.com"
lures: edit: strconv.Atoi: parsing "redirect_url": invalid syntax was the result
wondering what is wrong as I just copied from the readme

**Comment by mghtyspm** [comment]
@Zeze03 Hello "redirect_url" is wrong please use a hyphen instead. i.e. "redirect-url"
Please reach out with any more questions.

**Comment by mghtyspm** [comment]
@Zeze03 were you able to fet the coinbase lure to run, I am having an error while running on browser

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
