### ISSUE TITLE
O365 working phishlets 

### ISSUE THREAD

**Issue by Manjunou** [kgretzky/evilginx2#824]
tnx man 👐

**Comment by Sunnymoon2022** [comment]
Ripper

**Comment by TeddyBlue** [comment]
Can I get it?

**Comment by Sunnymoon2022** [comment]
His a scammer on telegram and icq the real person only have twitter

**Comment by TeddyBlue** [comment]
thanks for the heads up ... trying to ADFS working ...

**Comment by Sunnymoon2022** [comment]
You got telegram?

**Comment by longwalkshortdock999** [comment]
Indeed @diam0ndfox



Sent from my Galaxy



-------- Original message --------
From: Sunnymoon2022 ***@***.***>
Date: 2022-09-12 3:08 p.m. (GMT-08:00)
To: kgretzky/evilginx2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [kgretzky/evilginx2] O365 working phishlets (Issue #824)


You got telegram?

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Comment by atanu2679** [comment]
> 

[14:19:56] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[14:20:16] [!!!] acme: Error -> One or more domains had a problem:
[m.adbuniversity.cf] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for m.adbuniversity.cf - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for m.adbuniversity.cf - check that a DNS record exists for this domain, url: 
[static.adbuniversity.cf] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 20.219.38.54: Invalid response from http://static.faceb00k.cf/.well-known/acme-challenge/n5KEOTvOlu63DWeiWlzqxas7buc_7qVYiH7j-pZRnho: 404, url: 
[www.faceb00k.cf] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 20.219.38.54: Invalid response from http://www.faceb00k.cf/.well-known/acme-challenge/Ly_-anTgEuTcA4XRgeVBAGU7U0tJeoHtdy2kA5q6rqQ: 404, url:

**Comment by Support-1535** [comment]
Hello @atanu2679,

Make sure you have correctly created the dns records for that domain.

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by atanu2679** [comment]
Ok, thnks for your reply 🤗
