### ISSUE TITLE
git clone https://github.com/kgretzky/evilginx2.git code not working, command not found

### ISSUE THREAD

**Issue by lacylau157** [kgretzky/evilginx2#838]
support?

**Comment by henzo5050** [comment]
try this  git clone https://github.com/kgretzky/evilginx2.git  
and make sure you don't copy extra space when highlight that might be the issue

**Comment by Support-1452** [comment]
Hello,

To run the command 
```
git clone https://github.com/kgretzky/evilginx2.git
```
You need to have Git installed.
```
root@localhost:~# sudo apt install git
```
To confirm that you installed Git correctly, run the following command and check that you receive a relevant result.
```
root@localhost:~# git --version
git version 2.25.1
```

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
