### ISSUE TITLE
how to change port ?

### ISSUE THREAD

**Issue by globally0x** [kgretzky/evilginx2#839]
Hi, I want to proxy a website like www.example.com:8080, in my yaml file:
I add these lines, but it is not correct. Can anyone help?
login:
  domain: 'example.com'
  port: 8080
  path: ''

**Comment by bratyboby** [comment]
Telegram. cryptopro99

**Comment by lhost25** [comment]
> Telegram. cryptopro99

are you guys not tired? trying to rip people off. get a job dude.

**Comment by globally0x** [comment]
@ProfessorRS Do you know how to change port?
