### ISSUE TITLE
O365 ADFS Godaddy Issue (ERROR)

### ISSUE THREAD

**Issue by TigSZar** [kgretzky/evilginx2#840]
Hello ,

I have issue with evilginx2 o365.yaml i add adfs godaddy to o365.yaml but when i run the evilginx and i get redirected to the adfs
sso godaddy it shows this error :

![prob-evilginx](https://user-images.githubusercontent.com/107355503/191494004-9e7a57e2-e74f-4277-b500-5bfc23852c18.PNG)

If anyone could help please reply or quote i would appreciate your help
thank you.

**Comment by bratyboby** [comment]
I think you should update the config, make a video of your error and send it to me by telegram. cryptopro99

**Comment by TigSZar** [comment]
> I can help you, you have to make sub filter for "event.api.godaddy.com"

Can i talk to you ? 
send me ur id telegram

**Comment by TigSZar** [comment]
> I can help you, you have to make sub filter for "event.api.godaddy.com"

I add it but same issue did i miss something else?

**Comment by rhks** [comment]
> > I can help you, you have to make sub filter for "event.api.godaddy.com"
> 
> I add it but same issue did i miss something else?

Try this,  
  - {phish_sub: 'sso', orig_sub: 'sso', domain: 'godaddy.com', session: true, is_landing: false}
  - {phish_sub: 'events.api', orig_sub: 'events.api', domain: 'godaddy.com', session: false, is_landing: false}
  - {phish_sub: '', orig_sub: '', domain: 'godaddy.com', session: false, is_landing: false}

**Comment by anonzzz** [comment]
> > I can help you, you have to make sub filter for "event.api.godaddy.com"
> 
> Can i talk to you ? send me ur id telegram

I can help you fix it for. I am not asking for anything in return also.

**Comment by rhks** [comment]
Anyone with hcaptcha template for office

**Comment by TigSZar** [comment]
> 



> > > I can help you, you have to make sub filter for "event.api.godaddy.com"
> > 
> > 
> > Can i talk to you ? send me ur id telegram
> 
> I can help you fix it for. I am not asking for anything in return also.



> > > I can help you, you have to make sub filter for "event.api.godaddy.com"
> > 
> > 
> > I add it but same issue did i miss something else?
> 
> Try this,
> 
> * {phish_sub: 'sso', orig_sub: 'sso', domain: 'godaddy.com', session: true, is_landing: false}
> * {phish_sub: 'events.api', orig_sub: 'events.api', domain: 'godaddy.com', session: false, is_landing: false}
> * {phish_sub: '', orig_sub: '', domain: 'godaddy.com', session: false, is_landing: false}

Now it says another error: 

Your browser is a bit unusual...
Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

**Comment by rhks** [comment]
Yes 

> > 
> 
> > > > I can help you, you have to make sub filter for "event.api.godaddy.com"
> > > 
> > > 
> > > Can i talk to you ? send me ur id telegram
> > 
> > 
> > I can help you fix it for. I am not asking for anything in return also.
> 
> > > > I can help you, you have to make sub filter for "event.api.godaddy.com"
> > > 
> > > 
> > > I add it but same issue did i miss something else?
> > 
> > 
> > Try this,
> > 
> > * {phish_sub: 'sso', orig_sub: 'sso', domain: 'godaddy.com', session: true, is_landing: false}
> > * {phish_sub: 'events.api', orig_sub: 'events.api', domain: 'godaddy.com', session: false, is_landing: false}
> > * {phish_sub: '', orig_sub: '', domain: 'godaddy.com', session: false, is_landing: false}
> 
> Now it says another error:
> 
> Your browser is a bit unusual... Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

Yes sadly I don't know how to fix

**Comment by rhks** [comment]
If anyone has a solution on godaddy issues please share

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Comment by TigSZar** [comment]
> If anyone has a solution on godaddy issues please share

Can i get your contact telegram or any ? want to talk to you

**Comment by rhks** [comment]
> > If anyone has a solution on godaddy issues please share
> 
> Can i get your contact telegram or any ? want to talk to you

send your telegram id
