### ISSUE TITLE
o365 autograb email anyone?

### ISSUE THREAD

**Issue by lhost25** [kgretzky/evilginx2#841]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

office autograb email in link, is it possible?

**Comment by lhost25** [comment]
> #### DO NOT ASK FOR PHISHLETS.
> #### DO NOT ASK FOR HELP CREATING PHISHLETS.
> #### DO NOT ASK TO FIX PHISHLETS.
> #### DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
> #### EXPECT A BAN OTHERWISE. THANK YOU!
> #### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.
> office autograb email in link, is it possible?

You guys should be careful of this guy demanding for money. He's a scammer and a ripper. Will claim he has phislet and start demanding for money claiming nothing is free.


stop-robot <notifications@github.com> Unsubscribe | stop-robot <notifications@github.com> Unsubscribe | 4:07 AM (1 hour ago) 
stop-robot <notifications@github.com> Unsubscribe
to kgretzky/evilginx2, me, Author | to kgretzky/evilginx2, me, Author
to kgretzky/evilginx2, me, Author

href="mailto:maxibrainz10@outlook.com" target="_blank" style="color: rgb(17, 85, 204);">maxibrainz10@outlook.com
stop-robot <notifications@github.com> Unsubscribe
4:07 AM (1 hour ago)
to kgretzky/evilginx2, me, Author

Add me on ICQ @MAX1N3WT0N
or skype [maxibrainz10@outlook.com]

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Comment by xfoxhack** [comment]
If you have edited working o365 that grab email and remove bots please dm @xfoxhack icq
