### ISSUE TITLE
Password encrypted 2

### ISSUE THREAD

**Issue by roymillar** [kgretzky/evilginx2#845]
Hello, i created the phishlet of steam but when i login the password is encrypted like this 

<a href="https://ibb.co/0Yjn69n"><img src="https://i.ibb.co/8PDmfxm/100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b.png" alt="100247245-6db32e00-2f3a-11eb-87e2-66a5bd5a201b" border="0"></a>

Do someone have any idea to fix this ? Thanks   @cheapgutti   telegram

**Comment by support-evilg526** [comment]
Hello. Yes, we can help you. Contact us at support@evilginx2.com

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
