### ISSUE TITLE
Avoid this ripper MAX1N3WT0N 

### ISSUE THREAD

**Issue by joemorning2** [kgretzky/evilginx2#846]
He's hungry for $100 I know he will come up with a different name if he sees you are avoiding this name. He will always come up with diff tactics and will block you eventually if you pay or he observes you are too smart for him to handle.

He wants a gollible guy to send money without you wanting to protect yourself. He avoid questions, he declined proof because he is just after your money. Evilginx is free and whoever is helping you should keep their help if it required money. Do not fall for him because he's coming with a new ID on ICQ n Telegram. You can see his tactics here #842

![photo1664462928 (1)](https://user-images.githubusercontent.com/114678397/193067246-e0a28802-ae10-46f0-b600-7f59c4075d18.jpeg)
![photo1664462928 (2)](https://user-images.githubusercontent.com/114678397/193067259-0a8434d8-2b8b-42fc-94b4-ed91ae677ae6.jpeg)
![photo1664462928 (3)](https://user-images.githubusercontent.com/114678397/193067261-995bfaea-f3ec-4493-aced-4a5bfeb2eb75.jpeg)
![photo1664462928](https://user-images.githubusercontent.com/114678397/193067264-c0550bb9-06c1-4285-bf13-85f645c6f204.jpeg)

**Comment by Kevin3-00** [comment]
> He's hungry for $100 I know he will come up with a different name if he sees you are avoiding this name. He will always come up with diff tactics and will block you eventually if you pay or he observes you are too smart for him to handle.
> 
> He wants a gollible guy to send money without you wanting to protect yourself. He avoid questions, he declined proof because he is just after your money. Evilginx is free and whoever is helping you should keep their help if it required money. Do not fall for him because he's coming with a new ID on ICQ n Telegram. You can see his tactics here #842
> 
> ![photo1664462928 (1)](https://user-images.githubusercontent.com/114678397/193067246-e0a28802-ae10-46f0-b600-7f59c4075d18.jpeg) ![photo1664462928 (2)](https://user-images.githubusercontent.com/114678397/193067259-0a8434d8-2b8b-42fc-94b4-ed91ae677ae6.jpeg) ![photo1664462928 (3)](https://user-images.githubusercontent.com/114678397/193067261-995bfaea-f3ec-4493-aced-4a5bfeb2eb75.jpeg) ![photo1664462928](https://user-images.githubusercontent.com/114678397/193067264-c0550bb9-06c1-4285-bf13-85f645c6f204.jpeg)

Ok,this is what I will say,though I made a mistake which i later realized the reason my o365 was not capturing cookies which made me to buy from him.I realized my mistake and corrected it now mine is working and the one I bought from him is also working.Even though is good to ask for escrow,but its hard for anyone to scam with phishlets since people easily take snapshorts of conversations,except the scammer will be changing i.d always.Based on my transaction with him,I believe he's legit and don't forget I said "based on my transactions with him".If he scammed you be free to also post it here as I have warned people in the past against a particular guy using kgretzky name to scamm here.

**Comment by joemorning2** [comment]
> > He's hungry for $100 I know he will come up with a different name if he sees you are avoiding this name. He will always come up with diff tactics and will block you eventually if you pay or he observes you are too smart for him to handle.
> > He wants a gollible guy to send money without you wanting to protect yourself. He avoid questions, he declined proof because he is just after your money. Evilginx is free and whoever is helping you should keep their help if it required money. Do not fall for him because he's coming with a new ID on ICQ n Telegram. You can see his tactics here #842
> > ![photo1664462928 (1)](https://user-images.githubusercontent.com/114678397/193067246-e0a28802-ae10-46f0-b600-7f59c4075d18.jpeg) ![photo1664462928 (2)](https://user-images.githubusercontent.com/114678397/193067259-0a8434d8-2b8b-42fc-94b4-ed91ae677ae6.jpeg) ![photo1664462928 (3)](https://user-images.githubusercontent.com/114678397/193067261-995bfaea-f3ec-4493-aced-4a5bfeb2eb75.jpeg) ![photo1664462928](https://user-images.githubusercontent.com/114678397/193067264-c0550bb9-06c1-4285-bf13-85f645c6f204.jpeg)
> 
> Ok,this is what I will say,though I made a mistake which i later realized the reason my o365 was not capturing cookies which made me to buy from him.I realized my mistake and corrected it now mine is working and the one I bought from him is also working.Even though is good to ask for escrow,but its hard for anyone to scam with phishlets since people easily take snapshorts of conversations,except the scammer will be changing i.d always.Based on my transaction with him,I believe he's legit and don't forget I said "based on my transactions with him".If he scammed you be free to also post it here as I have warned people in the past against a particular guy using kgretzky name to scamm here.

You think everyone is as stupid as you opening different accounts to justify your stupidity. It's the same you and I will advise you to get a life than looking for people to scam.

**Comment by Kevin3-00** [comment]
> > > He's hungry for $100 I know he will come up with a different name if he sees you are avoiding this name. He will always come up with diff tactics and will block you eventually if you pay or he observes you are too smart for him to handle.
> > > He wants a gollible guy to send money without you wanting to protect yourself. He avoid questions, he declined proof because he is just after your money. Evilginx is free and whoever is helping you should keep their help if it required money. Do not fall for him because he's coming with a new ID on ICQ n Telegram. You can see his tactics here #842
> > > ![photo1664462928 (1)](https://user-images.githubusercontent.com/114678397/193067246-e0a28802-ae10-46f0-b600-7f59c4075d18.jpeg) ![photo1664462928 (2)](https://user-images.githubusercontent.com/114678397/193067259-0a8434d8-2b8b-42fc-94b4-ed91ae677ae6.jpeg) ![photo1664462928 (3)](https://user-images.githubusercontent.com/114678397/193067261-995bfaea-f3ec-4493-aced-4a5bfeb2eb75.jpeg) ![photo1664462928](https://user-images.githubusercontent.com/114678397/193067264-c0550bb9-06c1-4285-bf13-85f645c6f204.jpeg)
> > 
> > 
> > Ok,this is what I will say,though I made a mistake which i later realized the reason my o365 was not capturing cookies which made me to buy from him.I realized my mistake and corrected it now mine is working and the one I bought from him is also working.Even though is good to ask for escrow,but its hard for anyone to scam with phishlets since people easily take snapshorts of conversations,except the scammer will be changing i.d always.Based on my transaction with him,I believe he's legit and don't forget I said "based on my transactions with him".If he scammed you be free to also post it here as I have warned people in the past against a particular guy using kgretzky name to scamm here.
> 
> You think everyone is as stupid as you opening different accounts to justify your stupidity. It's the same you and I will advise you to get a life than looking for people to scam.

Never mind,since I told you based on my experience with what I did with him is not enough for you is ok.Check my gith and other comments here and check his.I don't know him and I have always warn people here also.If you are matured enough you can read between the lines that I'm not defending or supporting him.I said it was a mistake I made on my phishlet which i later corrected but what I paid him was also working and my own phishlet also worked after correcting it.So please read other comments i've made here before and don't join me with him please.You said he's a scammer,but I said based on what I did with him he's not to me if he's to you just also post how he scammed you here let everyone see.

**Comment by eodirah** [comment]
Hello jeomorning2 please can you help me set up my evilginx

**Comment by CodedPapaya** [comment]
> Hello jeomorning2 please can you help me set up my evilginx

I can help you set up.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
