### ISSUE TITLE
o365 ADFS phishlet TLS error

### ISSUE THREAD

**Issue by aleixsb** [kgretzky/evilginx2#847]
Hey!

I'm trying to create a lure using o365 phishlet with uncommented lines for ADFS, but when the initial o365 tries to redirect to adfs site I get the following error:

WARN: Cannot read TLS response from mitm'd server local error: tls: no renegotiation

and a 404 in the browser.. any idea what could be the issue?

**Comment by support-evilg526** [comment]
Hello. Yes, we can help you. Contact us at support@evilginx2.com

**Comment by manjunno** [comment]
O365 ADFS fixed thanks to sir gretzky @Mrgretzky on icq
