### ISSUE TITLE
unable to setup in local enviroment

### ISSUE THREAD

**Issue by Vellimakhlooq** [kgretzky/evilginx2#849]
Hi i am trying to setup evilginx2 in my local environment , I have set the config domain option to localhost and config ip to 127.0.0.1 but upon enabling the phishlets i get certificate error
!!!] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "www.localhost:8000": Domain name contains an invalid character, url:

**Comment by support-evilg526** [comment]
Hello. Yes, we can help you. Contact us at support@evilginx2.com

**Comment by jesus-ale43** [comment]
Hello,

To run EvilGinx2 locally, you need to run it with the `-developer` parameter.

You can get more information at https://github.com/kgretzky/evilginx2/wiki/FAQ

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1452** [comment]
Hello,

To run EvilGinx2 locally, you need to run it with the `-developer` parameter.

You can get more information at https://github.com/kgretzky/evilginx2/wiki/FAQ

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
