### ISSUE TITLE
**ERR_TOO_MANY_REDIRECTS.

### ISSUE THREAD

**Issue by Gta0147** [kgretzky/evilginx2#850]
**ERR_TOO_MANY_REDIRECTS.
everything has work except the landing page is not opening**

**Comment by Ofchitler** [comment]
You can reach out to @mrgretzky on icq maybe he can help

**Comment by support-evilg526** [comment]
Hello. Yes, we can help you. Contact us at support@evilginx2.com

**Comment by arnaud422** [comment]
have the same problem ... Have you found a solution?

**Comment by Andross** [comment]
I literally had to patch the code to solve this. It appears to be a bug though I am not 100% certain why

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
