### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by luhgeeked** [kgretzky/evilginx2#852]
i set my dns records on my domain to the ip of my vps and set everything else up according to the guide and i keep getting ssl error can anyone help

**Comment by luhgeeked** [comment]
acme: Error -> One or more domains had a problem:
[subdomainhere.citrix.citrxhelp.com] acme: error: 400 :: urn:ietf:params:acme:er                        ror:dns :: DNS problem: NXDOMAIN looking up A for subdomainhere.citrix.citrxhelp                        .com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN loo                        king up AAAA for subdomainhere.citrix.citrxhelp.com - check that a DNS record ex                        ists for this domain, url:

this is the error^

**Comment by luhgeeked** [comment]
acme: Error -> One or more domains had a problem:
[subdomainhere.citrix.citrxhelp.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 178.32.215.170: Fetching                  http://subdomainhere.citrix.citrxhelp.com/.well-known/acme-challenge/Z6m4rlm0cBIalblJd7nnzjxRp2STp_LDFb1AVLbnaPM: Timeout during connect (likely firewall problem), url:

i am getting this error now if somone could help that would be great

**Comment by CodedPapaya** [comment]
Try running it from scratch, get a different domain name, if possible a new IP.

**Comment by Ofchitler** [comment]
You can reach out to @mrgretzky on icq maybe he can help

**Comment by support-evilg526** [comment]
Hello. Yes, we can help you. Contact us at support@evilginx2.com

**Comment by Support-1452** [comment]
Hello,

This question is already answered in the FAQ section.

> https://github.com/kgretzky/evilginx2/wiki/FAQ

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!
