### ISSUE TITLE
Instagram Cookie  Banner Bug  5$ BTC Reward for the solution!

### ISSUE THREAD

**Issue by rzmpzgeviii** [kgretzky/evilginx2#855]
I offer 5$ to whoever delivers me the solution since its urgent.

Hi there, when I browse to my instagram lure I get the normal instagram cookie banner but for some weird reason can´t I accept or close it. When I click on accept literally nothing happens.  The console recognizes a connection. I remember I have used this tool a month before with exact same settings and back then it didn´t occur. Its the same on any device not just mine. Any ideas? 
Already tried re-creating lures and reinstalling evilginx.

![sreen](https://user-images.githubusercontent.com/101715188/195958618-a66ece18-1ca6-4d7a-ad8b-60cd6426cff3.PNG)

**Comment by gitmopo** [comment]
Reach out to @mrgretzky he will help

**Comment by rzmpzgeviii** [comment]
@Mrgretzky any idea?

**Comment by rzmpzgeviii** [comment]
any idea?  @kgretzky  I would really appreciate it! 🙏🙏🙏🙏🙏

**Comment by theredbruno** [comment]
Message me on telegram @happyd0b3r
