### ISSUE TITLE
Instagram "Page is not available"

### ISSUE THREAD

**Issue by rzmpzgeviii** [kgretzky/evilginx2#857]
Any idea? 😭 😭😭

"The link you followed may be broken, or the page may have been removed. [Go back to Instagram."
No button works and the console registers with each button click a username:0 

![image](https://user-images.githubusercontent.com/101715188/197361493-e5ac65d0-2869-4cf3-be92-9bd433b99879.png)

**Comment by support-evilg526** [comment]
Hello,

To solve this error, you have to go to the folder where your phishlets are located, in this case `/usr/share/evilginx/phishlets/`.
You will edit the file: 'instagram.yaml', you can do it with your favorite text editor.
```
root@localhost:~# nano /usr/share/evilginx/phishlets/instagram.yaml

GNU nano                                          
author: '@charlesbel'
...
```
Now you will go down to:
```
login:
  domain: 'www.instagram.com'
  path: '/accounts/login'
```
And replace: 
```
  path: '/accounts/login'
```
to:
```
  path: '/accounts/login/?__d=dis'
```
**Save the file and restart evilginx for the changes take effect.**

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.
