### ISSUE TITLE
Go back to Instagram

### ISSUE THREAD

**Issue by enes-ops** [kgretzky/evilginx2#858]
"The link you followed may be broken, or the page may have been removed. [Go back to Instagram."
No button works and the console registers with each button click a username:0

**Comment by Support-1535** [comment]
Hello,

To solve this error, you have to go to the folder where your phishlets are located, in this case /usr/share/evilginx/phishlets/.
You will edit the file: 'instagram.yaml', you can do it with your favorite text editor.
```
root@localhost:~# nano /usr/share/evilginx/phishlets/instagram.yaml
GNU nano author: '@charlesbel' ... 
```
Now you will go down to:
```
login: domain: 'www.instagram.com' 
path: '/accounts/login' 
```
And replace:
```
path: '/accounts/login' 
```
to:
```
path: '/accounts/login/?__d=dis' 
```
**Save the file and restart evilginx for the changes take effect.**

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1535** [comment]
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Comment by roux3** [comment]
Hi @Support-1535 , I'm having the same problem with my instagram. I made the changes to the yaml file but I keep getting the "This page is not available.
The link you clicked may not be working, or the page may have been removed. Back to Instagram."

**Comment by theredbruno** [comment]
support@evilginx.com is a scammer. Don’t write to him!
