### ISSUE TITLE
How to make enabling many phishlets work at the same time

### ISSUE THREAD

**Issue by Kevin3-00** [kgretzky/evilginx2#861]
When I enabled more than one phishlets,any link i generate leads to 404 error,when I disable all and enable a single phishlets then the link load normal.Who experience this same issue and what's the way out of it.I added all subdomains to dns cname already.

**Comment by Support-1535** [comment]
If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Kevin3-00** [comment]
> 

Why not here so that others can benefit instead of asking fee on telegram.If you know how to fix it show it here.
