### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by coderb118** [kgretzky/evilginx2#867]
I'm new here and not sure if there is a community where I can use some help. I just need some help and this is not really an issue with the program. Can anyone please guide me on how to configure the Pre-phish HTML template on Evilginx2. I have the index file and saved in a template folder. So how do I run the template?

**Comment by George152-max** [comment]
@coderb118 
Man can we chat on telegram
Iono if we could share knowledge cuz I also need some guidance

**Comment by theredbruno** [comment]
@George152-max add me on telegram @happyd0b3r

**Comment by Support-1535** [comment]
If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by theredbruno** [comment]
@Support-1535 You Bastard!!! Guys don’t listen to him, he is a scammer!!!
