### ISSUE TITLE
Sites not displaying correctly

### ISSUE THREAD

**Issue by F13** [kgretzky/evilginx2#87]
Hello,

I'm trying to set up Evilginx for the first time. I believe everything is set up according to the instructuons, however, when a user visits the link they are provided a copy that seems to be missing all Javascript and CSS. I am using the built in phishlets for testing and this is how they look:

![example](https://i.imgur.com/WAmUcaT.png)

Is there something obvious I am missing?

**Comment by kgretzky** [comment]
You can open web inspector and then console or network tab to see what is the issue.
