### ISSUE TITLE
How can i edit the pre-phish already created 

### ISSUE THREAD

**Issue by lagrav** [kgretzky/evilginx2#875]
Hello everyone, i am trying to edit the **pre-phish** already created to something of my choice instead of "download" or "*** shared a file with you" i'd prefer something else... i've tried editing the code and saved it, but when i click my link it doesn't seem to change, it still remains as the example. Please your help will be very much appreciated. Thanks in advance

**Comment by Support-1535** [comment]
> By default, evilginx2 will look for HTML templates in ./templates/ directory and later in /usr/share/evilginx/templates/. If you want to specify a custom path to load HTML templates from, use the -t <templates_dir_path> parameter when launching the tool.
**Save the file and restart evilginx for the changes take effect.**

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by Support-1535** [comment]
We have given you the solution to your problem, currently the help here on Github is slow because very few people help, we have a private community that is updated and assisted 24/7 if you are interested in joining find me on Telegram @TheEvilGinx2 or by email at support@evilginx2.com

**Comment by lagrav** [comment]
i cant find the telegram name

**Comment by lagrav** [comment]
alright i'm good now. thanks for the help @Support-1535
