### ISSUE TITLE
Not listening on port 80 & ipv4

### ISSUE THREAD

**Issue by lesleyxyz** [kgretzky/evilginx2#906]
Hi All,

I have two issues with evilginx2.

It works perfectly on windows, but on Ubuntu 22 it's not listening on port 80, only 443.
This port is irresponsive because IIRC port 443 is just a proxy to port 80.
```
c2admin@c2-server:~$ sudo netstat -tulpn | grep evil
tcp6       0      0 :::443
```

The next issue is like others pointed out, it's only listening on ipv6.
Any advice?

**Comment by Mrsagacious** [comment]
Hi,

Listening on ipv6 will also work for ipv4 tcp connections too.

If you are using a VirtualBox setup in windows, perhaps the windows version is using port 80 so you are unable to access from a virtual machine.

**Comment by Mrsagacious** [comment]
It seems like a port issue.

perhaps try multiple apps to check all ports opened on the server, and allow port access via Firewalld.
