### ISSUE TITLE
Feature Request: redirect_url override per phishlet

### ISSUE THREAD

**Issue by aalex954** [kgretzky/evilginx2#915]
When running multiple campaigns or phishlets it may be useful to have the ability to present different redirect pages for unauthorized clients depending on the lure/phishlet they access. 

Presenting different redirect_url pages may help with limiting the association of the redirect_url page for one phishlet with the overall campaign. This will make it more difficult for defenders to model the threat. 

This would be especially useful in conjunction with MSFT IP blacklist to evade EOP.

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
