### ISSUE TITLE
It seems like academy.breakdev.org is not working

### ISSUE THREAD

**Issue by DmitrikSerhiy** [kgretzky/evilginx2#916]
I'd like to buy a course. But https://academy.breakdev.org/ is down.
Is it supported in the first place?

**Comment by BakkerJan** [comment]
FYI

[cid:098366f1-94e3-4197-adef-c519848a50e4]

Met vriendelijke groet,

Jan Bakker
________________________________
Van: Serenkiy ***@***.***>
Verzonden: donderdag 6 juli 2023 16:11
Aan: kgretzky/evilginx2 ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [kgretzky/evilginx2] It seems like academy.breakdev.org is not working (Issue #916)


I'd like to buy a course. But https://academy.breakdev.org/ is down.
Is it supported in the first place?

**Comment by DmitrikSerhiy** [comment]
The site is up.
