### ISSUE TITLE
cookies with path different than root /

### ISSUE THREAD

**Issue by svtlm2018** [kgretzky/evilginx2#92]
First of all great job with this development. Impressive
What I've noticed trying to setup this is that the below declaration is saving just cookies with a path "/":
 **- domain: '.domain.com'** (bogus domain)
    **keys: ['.*,regexp']** ( I know the names, the reason I'm using the catch-all is because this website has country variations and the naming is different based on the locale.)

I do have an instance where .domain.com is setting **root path "/"** as most websites, but the **SSO cookies are set in "/ap/" path** which are responsible for the SSO session.

Is there a way to explicitly grab these cookies?

**Comment by kgretzky** [comment]
Cookie paths are not currently captured from what I remember. In most cases if there are no cookie name duplicates under different paths, it should be fine to have a default path of `/` since then the cookie will be sent with request to any path.

**Comment by svtlm2018** [comment]
Thanks for replying. So in theory if I use the cookie name explicit it should get it, no matter what the original path is?
Would a combination of catch-all regex & explicit cookie work in the same keys declaration like: 
keys: ['.*,regexp','explicit_cookie1','explicit_cookie 2'] ?

I'm trying to build an Amazon Seller Central, one template fits all countries, and I've managed to cover all of it, apart from the SSO cookies which simply refuses to get on..

As a feature I think emailing to a specific address would be good after every capture, or at a specific interval of time. I've built it separately, but I need to run 2 services  separately, ginx on one side and the automatic mailer on another side.

**Comment by kgretzky** [comment]
If you put `'.*,regexp'` in one of the cookie keys to capture it will already capture all cookies, so you don't have to specify other explicit_cookie names apart from that as it would not change anything.
If you use `'.*,regexp'` you need to remember to rely on `auth_url` option that will trigger the session capture when specific URL is hit (also supports regexp).
