### ISSUE TITLE
how to set evilginx to deliver results to telegram

### ISSUE THREAD

**Issue by peterkels** [kgretzky/evilginx2#936]

**Comment by 0xmada** [comment]
Check this tool on Telegram, can be fully customized to do whatever you want for phishing. and can also grab cookies.
https://t.me/dayztar

**Comment by Jill60** [comment]
Becareful with what you download so you don't get phished yourself and also watch those that try to help you here carefully.They fall in to two categories:
(1) First one will leave their tg contact and ask you for money as the first response after saying hi back to you on tg.
(2)The second categories evolved from the first and now they are reffering you to download their backdoored links that will give them access to your pc.Whoever that's not ready to post his/her fix or solution here just be very careful.
