### ISSUE TITLE
blacklisted ip address: 127.0.0.1

### ISSUE THREAD

**Issue by RogueThread** [kgretzky/evilginx2#948]
Hi,

With `blacklist unauth` setting:
I get a visit from external attacker then 127.0.0.1 gets added to blacklist and then phishing page no longer works and every IP is "unauthorized", external visits are considered as "127.0.0.1"

See screenshot:
![image](https://github.com/kgretzky/evilginx2/assets/20130122/6fcb3d4f-69bb-4938-87f3-8f15ce35024b)

**Comment by Jill60** [comment]
Either you use blacklist off which means bots also will crawl your link or you go and remove 127.0.0.1(localhost) from blacklist list.

**Comment by RogueThread** [comment]
Of course i’d prefer to use the blacklist to prevent bots crawling but the issue is still that 127.0.0.1 gets added to Blacklist after visits from external IPs (see timestamps in screenshot)

**Comment by Jill60** [comment]
> Of course i’d prefer to use the blacklist to prevent bots crawling but the issue is still that 127.0.0.1 gets added to Blacklist after visits from external IPs (see timestamps in screenshot)

https://t.me/Dlenny100  pm

**Comment by fsacer** [comment]
This is still an issue afaik, shouldn't the blacklist use the last set X-Forwared-For IP? at least that would make sense in my case, would be nice to have an option to use that
