### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by anicec4t** [kgretzky/evilginx2#97]
Tried to compile the source code (maybe the ssl issue is fixed there) but I get the following error on the make command

imports testing: unrecognized import path "testing"
Makefile:23: recipe for target 'godep' failed
make: *** [godep] Error 1

Any Clues?

**Comment by kgretzky** [comment]
Not really.

**Comment by engrsaheed** [comment]
![error](https://user-images.githubusercontent.com/5889843/51077652-d9bf7c80-16a9-11e9-9304-c517ae01d8ec.PNG)
