### ISSUE TITLE
bug error 400

### ISSUE THREAD

**Issue by thechosenone0-1** [kgretzky/evilginx2#977]
im having issues setting with evilginix I've not been able to figure out what im doing wrong this is my first time using this repo so i do apologies if i say or do something incorrectly 

![image](https://github.com/kgretzky/evilginx2/assets/148886335/a992511b-aca8-43fc-bcc5-9effba1df9b5)

**Comment by thechosenone0-1** [comment]
i've managed to fix the error code 400 but now every time i set the lure and try to get it to work im now getting another error 

"We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

**Comment by only1anonymousmaster** [comment]
> i've managed to fix the error code 400 but now every time i set the lure and try to get it to work im now getting another error 
> 
> 
> 
> "We're unable to complete your request
> 
> 
> 
> invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."
> 
> 

Please how did you fix the error I have been having similar problems

**Comment by Sniper1470** [comment]
add me on @piperberlesimo to help you out on it

**Comment by stylez28** [comment]
> im having issues setting with evilginix I've not been able to figure out what im doing wrong this is my first time using this repo so i do apologies if i say or do something incorrectly
> 
> ![image](https://user-images.githubusercontent.com/148886335/279837539-a992511b-aca8-43fc-bcc5-9effba1df9b5.png)

How did u fix the error 400
